// frontend/src/components/folders/MoveToFolderDialog.vue
<template>
	<Dialog
		:open="open"
		title="Move assets"
		size="sm"
		:actions="[
			{
				label: 'Move',
				variant: 'solid',
				loading: move.loading,
				disabled: !target,
				onClick: submit,
			},
			{ label: 'Cancel' },
		]"
		@update:open="emit('update:open', $event)"
	>
		<FormControl
			v-model="target"
			type="select"
			label="Destination"
			:description="`${assetNames.length} asset${assetNames.length === 1 ? '' : 's'} selected.`"
			:options="options"
			placeholder="Choose a folder"
			:error="move.error?.message"
		/>
	</Dialog>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Dialog, FormControl, toast, useCall } from 'frappe-ui'
import type { Folder } from '@/types'
import { buildFolderOptions } from '@/lib/folderPaths'
import { serverMessage } from '@/lib/format'

const ROOT = '__root__'
const props = defineProps<{
	open: boolean
	assetNames: string[]
	folders: Folder[]
	currentFolder?: string | null
}>()
const emit = defineEmits<{ 'update:open': [value: boolean]; changed: [] }>()
const target = ref('')

watch(
	() => props.open,
	(open) => {
		if (open) target.value = ''
	},
)

const options = computed(() => [
	...(props.currentFolder ? [{ label: 'Project root', value: ROOT }] : []),
	...buildFolderOptions(props.folders)
		.filter((folder) => folder.name !== props.currentFolder)
		.map((folder) => ({ label: folder.path, value: folder.name })),
])

const move = useCall<unknown, { asset_names: string; folder: string | null }>({
	url: '/api/v2/method/vms.api.move_assets_to_folder',
	method: 'POST',
	immediate: false,
})

async function submit({ close }: { close: () => void }) {
	if (!target.value) return
	try {
		await move.submit({
			asset_names: JSON.stringify(props.assetNames),
			folder: target.value === ROOT ? null : target.value,
		})
		toast.success(
			`Moved ${props.assetNames.length} asset${props.assetNames.length === 1 ? '' : 's'}`,
		)
		emit('changed')
		close()
	} catch (error) {
		toast.error(serverMessage(error) || 'Could not move assets')
	}
}
</script>

// frontend-react/src/components/MoveToFolderDialog.tsx
import { useMemo, useState } from "react"
import { useFrappeGetDocList, useFrappePostCall } from "frappe-react-sdk"
import { toast } from "sonner"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { serverMessage } from "@/lib/utils"
import type { VMSFolder } from "@/types"
import { buildFolderOptions } from "@/lib/folderPaths"

interface MoveToFolderDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  assetNames: string[]
  project: string
  currentFolder?: string | null
  onComplete?: () => void
}

const ROOT_VALUE = "__root__"

export function MoveToFolderDialog({
  open,
  onOpenChange,
  assetNames,
  project,
  currentFolder,
  onComplete,
}: MoveToFolderDialogProps) {
  const [targetFolder, setTargetFolder] = useState<string>("")
  const [moving, setMoving] = useState(false)

  const { data: folders } = useFrappeGetDocList<VMSFolder>("VMS Folder", {
    fields: ["name", "folder_name", "parent_folder"],
    filters: [["project", "=", project], ["deleted_at", "is", "not set"]],
    orderBy: { field: "folder_name", order: "asc" },
    limit: 500,
  })

  const { call: moveAssets } = useFrappePostCall("vms.api.move_assets_to_folder")

  const handleMove = async () => {
    if (!targetFolder) {
      toast.error("Please select a destination")
      return
    }

    setMoving(true)
    try {
      const folder = targetFolder === ROOT_VALUE ? null : targetFolder
      await moveAssets({
        asset_names: JSON.stringify(assetNames),
        folder,
      })
      toast.success(
        `Moved ${assetNames.length} asset${assetNames.length > 1 ? "s" : ""}`
      )
      setTargetFolder("")
      onOpenChange(false)
      onComplete?.()
    } catch (e: unknown) {
      toast.error("Failed to move assets", {
        description: serverMessage(e) || "Try again in a moment.",
      })
    } finally {
      setMoving(false)
    }
  }

  // Filter out the current folder from options
  const availableFolders = useMemo(
    () =>
      buildFolderOptions(folders ?? []).filter((f) => f.name !== currentFolder),
    [folders, currentFolder],
  )

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Move to Folder</DialogTitle>
          <DialogDescription>
            Move {assetNames.length} asset{assetNames.length > 1 ? "s" : ""} to
            a folder.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-2">
          <Label>Destination</Label>
          <Select value={targetFolder} onValueChange={setTargetFolder}>
            <SelectTrigger className="w-full">
              <SelectValue>
                {(value: string | null) => {
                  if (!value) return "Select a folder..."
                  if (value === ROOT_VALUE) return "Project Root (no folder)"
                  return availableFolders.find((f) => f.name === value)?.path ?? value
                }}
              </SelectValue>
            </SelectTrigger>
            <SelectContent>
              {currentFolder && (
                <SelectItem value={ROOT_VALUE}>
                  Project Root (no folder)
                </SelectItem>
              )}
              {availableFolders.map((f) => (
                <SelectItem key={f.name} value={f.name}>
                  {f.ancestors.length > 0 && (
                    <span className="text-muted-foreground">
                      {f.ancestors.join(" / ")} /{" "}
                    </span>
                  )}
                  {f.folderName}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={moving}
          >
            Cancel
          </Button>
          <Button onClick={handleMove} disabled={moving || !targetFolder}>
            {moving ? "Moving..." : "Move"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
