// frontend/src/components/assets/RenameAssetDialog.vue
<template>
	<Dialog
		:open="open"
		title="Rename asset"
		size="sm"
		:actions="[{ label: 'Rename', variant: 'solid', onClick: submit }, { label: 'Cancel' }]"
		@update:open="emit('update:open', $event)"
	>
		<FormControl
			v-model="stem"
			label="File name"
			required
			autofocus
			:error="rename.error?.message"
			@keydown.enter="submit({ close: closeDialog })"
		>
			<template v-if="extension" #suffix>
				<span class="text-sm text-ink-gray-5">{{ extension }}</span>
			</template>
		</FormControl>
	</Dialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { Dialog, FormControl, toast, useCall } from 'frappe-ui'
import type { Asset } from '@/types'

const props = defineProps<{ open: boolean; asset: Asset }>()
const emit = defineEmits<{ 'update:open': [value: boolean]; changed: [] }>()

const stem = ref(fileParts(props.asset.file_name).stem)
const extension = ref(fileParts(props.asset.file_name).extension)

watch(
	() => props.open,
	(open) => {
		if (!open) return
		const parts = fileParts(props.asset.file_name)
		stem.value = parts.stem
		extension.value = parts.extension
	},
)

const rename = useCall<Asset, { asset_name: string; new_file_name: string }>({
	url: '/api/v2/method/vms.api.rename_asset',
	method: 'POST',
	immediate: false,
})

function closeDialog() {
	emit('update:open', false)
}

async function submit({ close }: { close: () => void }) {
	const name = `${stem.value.trim()}${extension.value}`
	if (!name || name === props.asset.file_name) return close()
	await rename.submit({ asset_name: props.asset.name, new_file_name: name })
	toast.success('Asset renamed')
	emit('changed')
	close()
}

function fileParts(fileName: string) {
	const dot = fileName.lastIndexOf('.')
	return dot > 0
		? { stem: fileName.slice(0, dot), extension: fileName.slice(dot) }
		: { stem: fileName, extension: '' }
}
</script>

// frontend-react/src/components/RenameAssetDialog.tsx
import { useState, useEffect } from "react"
import { useFrappePostCall } from "frappe-react-sdk"
import { toast } from "sonner"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

interface RenameAssetDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  assetName: string
  currentFileName: string
  onComplete?: () => void
}

export function RenameAssetDialog({
  open,
  onOpenChange,
  assetName,
  currentFileName,
  onComplete,
}: RenameAssetDialogProps) {
  const lastDot = currentFileName.lastIndexOf(".")
  const hasExtension = lastDot > 0
  const initialStem = hasExtension ? currentFileName.slice(0, lastDot) : currentFileName
  const extension = hasExtension ? currentFileName.slice(lastDot) : ""

  const [stem, setStem] = useState(initialStem)
  const [renaming, setRenaming] = useState(false)

  const { call: renameAsset } = useFrappePostCall("vms.api.rename_asset")

  useEffect(() => {
    if (open) {
      const dot = currentFileName.lastIndexOf(".")
      setStem(dot > 0 ? currentFileName.slice(0, dot) : currentFileName)
    }
  }, [open, currentFileName])

  const trimmedStem = stem.trim()
  const newFileName = trimmedStem + extension
  const isUnchanged = newFileName === currentFileName

  const handleRename = async () => {
    if (!trimmedStem || isUnchanged) return

    setRenaming(true)
    try {
      await renameAsset({ asset_name: assetName, new_file_name: newFileName })
      toast.success("Asset renamed")
      onOpenChange(false)
      onComplete?.()
    } catch (e: unknown) {
      const message = e instanceof Error ? e.message : "Failed to rename asset"
      toast.error(message)
    } finally {
      setRenaming(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Rename Asset</DialogTitle>
          <DialogDescription>
            Enter a new name for this asset.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-2">
          <Label>File Name</Label>
          <div className="flex items-center gap-0">
            <Input
              autoFocus
              value={stem}
              onChange={(e) => setStem(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") handleRename()
              }}
              className={extension ? "rounded-r-none" : ""}
            />
            {extension && (
              <span className="flex h-9 items-center rounded-r-md border border-l-0 bg-muted px-3 text-sm text-muted-foreground">
                {extension}
              </span>
            )}
          </div>
        </div>
        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={renaming}
          >
            Cancel
          </Button>
          <Button
            onClick={handleRename}
            disabled={renaming || !trimmedStem || isUnchanged}
          >
            {renaming ? "Renaming..." : "Rename"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
