// frontend/src/components/CommandPalette.tsx
import { useCallback, useEffect, useState } from "react"
import { useNavigate, useLocation } from "react-router"
import { useFrappeGetCall } from "frappe-react-sdk"
import {
  CommandDialog,
  Command,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  CommandSeparator,
  CommandShortcut,
} from "@/components/ui/command"
import { CircleUser, ClipboardList, CloudUpload, FileVideo, FolderClosed, Images, LayoutDashboard, Settings, UserPlus } from "lucide-react"

interface CommandPaletteProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onOpenSettings: (tab?: string) => void
  onOpenUpload: () => void
}

interface SearchResult {
  name: string
  file_name: string
  project?: string
  project_name?: string
  category?: string
  file_type?: string
}

interface ProjectResult {
  name: string
  project_name: string
  status?: string
}

export function CommandPalette({
  open,
  onOpenChange,
  onOpenSettings,
  onOpenUpload,
}: CommandPaletteProps) {
  const navigate = useNavigate()
  const location = useLocation()
  const [query, setQuery] = useState("")

  // Detect current project context from URL
  const projectMatch = location.pathname.match(/\/projects\/([^/]+)/)
  const currentProjectId = projectMatch ? projectMatch[1] : null

  // Search assets when query has 2+ chars
  const shouldSearch = query.trim().length >= 2
  const { data: searchData } = useFrappeGetCall<{
    message: { results: SearchResult[] }
  }>(
    shouldSearch ? "vms.api.search_assets" : null,
    shouldSearch
      ? {
          query: query.trim(),
          project: currentProjectId || undefined,
          limit: 8,
        }
      : undefined,
    undefined,
    {
      revalidateOnFocus: false,
    }
  )

  const searchResults = searchData?.message?.results || []

  // Search projects when query has 2+ chars and not already in a project context
  const shouldSearchProjects = shouldSearch && !currentProjectId
  const { data: projectSearchData } = useFrappeGetCall<{
    message: { results: ProjectResult[] }
  }>(
    shouldSearchProjects ? "vms.api.search_projects" : null,
    shouldSearchProjects
      ? { query: query.trim(), limit: 5 }
      : undefined,
    undefined,
    { revalidateOnFocus: false }
  )

  const projectResults = projectSearchData?.message?.results || []

  const runCommand = useCallback(
    (command: () => void) => {
      onOpenChange(false)
      command()
    },
    [onOpenChange]
  )

  // Reset query when dialog closes
  useEffect(() => {
    if (!open) {
      setQuery("")
    }
  }, [open])

  return (
    <CommandDialog open={open} onOpenChange={onOpenChange}>
      <Command>
        <CommandInput
          placeholder={
            currentProjectId
              ? "Search in project or type a command..."
              : "Type a command or search..."
          }
          value={query}
          onValueChange={setQuery}
        />
        <CommandList>
          {/* Hide empty state when forceMount results exist */}
          {!(shouldSearch && (searchResults.length > 0 || projectResults.length > 0)) && (
            <CommandEmpty>No results found.</CommandEmpty>
          )}

          {/* Search Results */}
          {shouldSearch && searchResults.length > 0 && (
            <>
              <CommandGroup
                heading={currentProjectId ? "Files in project" : "Files"}
                forceMount
              >
                {searchResults.map((result) => (
                  <CommandItem
                    key={result.name}
                    value={`file-${result.name}`}
                    forceMount
                    onSelect={() =>
                      runCommand(() =>
                        navigate(`/review/${result.name}`)
                      )
                    }
                  >
                    <FileVideo className="size-4" />
                    <span className="flex-1 truncate">{result.file_name}</span>
                    {!currentProjectId && result.project_name && (
                      <span className="text-xs text-muted-foreground">
                        in {result.project_name}
                      </span>
                    )}
                    {result.category && (
                      <span className="text-xs text-muted-foreground">
                        {result.category}
                      </span>
                    )}
                  </CommandItem>
                ))}
              </CommandGroup>
              <CommandSeparator />
            </>
          )}

          {/* Project Search Results */}
          {shouldSearchProjects && projectResults.length > 0 && (
            <>
              <CommandGroup heading="Projects" forceMount>
                {projectResults.map((project) => (
                  <CommandItem
                    key={project.name}
                    value={`project-${project.name}`}
                    forceMount
                    onSelect={() =>
                      runCommand(() =>
                        navigate(`/projects/${project.name}`)
                      )
                    }
                  >
                    <FolderClosed className="size-4" />
                    <span className="flex-1 truncate">
                      {project.project_name}
                    </span>
                    {project.status && (
                      <span className="text-xs text-muted-foreground">
                        {project.status}
                      </span>
                    )}
                  </CommandItem>
                ))}
              </CommandGroup>
              <CommandSeparator />
            </>
          )}

          {/* Navigation Commands */}
          <CommandGroup heading="Navigation">
            <CommandItem
              value="dashboard"
              keywords={["home", "overview"]}
              onSelect={() => runCommand(() => navigate("/"))}
            >
              <LayoutDashboard className="size-4" />
              <span>Go to Dashboard</span>
            </CommandItem>
            <CommandItem
              value="uncategorised"
              keywords={["uploads", "unassigned", "media", "inbox"]}
              onSelect={() => runCommand(() => navigate("/uncategorised"))}
            >
              <Images className="size-4" />
              <span>Go to Uncategorised</span>
            </CommandItem>
            <CommandItem
              value="projects"
              keywords={["folders", "videos"]}
              onSelect={() => runCommand(() => navigate("/projects"))}
            >
              <FolderClosed className="size-4" />
              <span>Go to Projects</span>
            </CommandItem>
            <CommandItem
              value="audit logs"
              keywords={["history", "activity"]}
              onSelect={() => runCommand(() => navigate("/audit-logs"))}
            >
              <ClipboardList className="size-4" />
              <span>Go to Audit Logs</span>
            </CommandItem>
          </CommandGroup>

          <CommandSeparator />

          {/* Actions */}
          <CommandGroup heading="Actions">
            <CommandItem
              value="upload files"
              keywords={["add", "import"]}
              onSelect={() =>
                runCommand(() => onOpenUpload())
              }
            >
              <CloudUpload className="size-4" />
              <span>Upload Files</span>
              <CommandShortcut>U</CommandShortcut>
            </CommandItem>
            <CommandItem
              value="settings"
              keywords={["preferences", "config"]}
              onSelect={() =>
                runCommand(() => onOpenSettings("general"))
              }
            >
              <Settings className="size-4" />
              <span>Open Settings</span>
            </CommandItem>
            <CommandItem
              value="invite user"
              keywords={["add user", "team"]}
              onSelect={() =>
                runCommand(() => onOpenSettings("users"))
              }
            >
              <UserPlus className="size-4" />
              <span>Invite User</span>
            </CommandItem>
            <CommandItem
              value="profile"
              keywords={["account", "user", "me"]}
              onSelect={() =>
                runCommand(() => onOpenSettings("profile"))
              }
            >
              <CircleUser className="size-4" />
              <span>Profile</span>
            </CommandItem>
          </CommandGroup>
        </CommandList>
      </Command>
    </CommandDialog>
  )
}

/**
 * Hook to register Cmd+K keyboard shortcut
 */
export function useCommandPalette() {
  const [open, setOpen] = useState(false)

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault()
        setOpen((prev) => !prev)
      }
    }

    document.addEventListener("keydown", handleKeyDown)
    return () => document.removeEventListener("keydown", handleKeyDown)
  }, [])

  return { open, setOpen }
}

// frontend/src/components/shell/CommandPalette.vue
<template>
	<!-- Server search decides which assets and projects match, so the client
	     filter is off and the static commands are narrowed by hand. -->
	<CommandPalette
		v-model:open="commandPaletteOpen"
		v-model:query="query"
		:filterable="false"
		title="Search"
		@select="run"
	>
		<CommandPaletteInput :placeholder="placeholder" />

		<CommandPaletteList>
			<CommandPaletteGroup v-if="assetResults.length" :label="assetGroupLabel">
				<CommandPaletteItem
					v-for="asset in assetResults"
					:key="asset.name"
					:value="{ kind: 'asset', name: asset.name }"
					:data-value="`file-${asset.name}`"
					data-testid="palette-asset"
				>
					<template #prefix>
						<span
							:class="[
								fileKindStyle(asset.file_type).icon,
								fileKindStyle(asset.file_type).ink,
								'mr-2 size-4',
							]"
						/>
					</template>
					{{ asset.file_name }}
					<template #suffix>
						<span class="text-xs text-ink-gray-5">
							<template v-if="!currentProjectId && asset.project_name">
								in {{ asset.project_name }}
							</template>
							<template v-if="asset.category"> · {{ asset.category }}</template>
						</span>
					</template>
				</CommandPaletteItem>
			</CommandPaletteGroup>

			<CommandPaletteGroup v-if="projectResults.length" label="Projects">
				<CommandPaletteItem
					v-for="project in projectResults"
					:key="project.name"
					:value="{ kind: 'project', name: project.name }"
					:data-value="`project-${project.name}`"
					data-testid="palette-project"
				>
					<template #prefix>
						<span class="lucide-folder mr-2 size-4 text-ink-gray-5" />
					</template>
					{{ project.project_name }}
					<template v-if="project.status" #suffix>
						<span class="text-xs text-ink-gray-5">{{ project.status }}</span>
					</template>
				</CommandPaletteItem>
			</CommandPaletteGroup>

			<CommandPaletteGroup v-if="navigation.length" label="Navigation">
				<CommandPaletteItem
					v-for="command in navigation"
					:key="command.id"
					:value="command"
					:data-value="command.id"
				>
					<template #prefix>
						<span :class="[command.icon, 'mr-2 size-4 text-ink-gray-5']" />
					</template>
					{{ command.label }}
				</CommandPaletteItem>
			</CommandPaletteGroup>

			<CommandPaletteGroup v-if="actions.length" label="Actions">
				<CommandPaletteItem
					v-for="command in actions"
					:key="command.id"
					:value="command"
					:data-value="command.id"
				>
					<template #prefix>
						<span :class="[command.icon, 'mr-2 size-4 text-ink-gray-5']" />
					</template>
					{{ command.label }}
					<template v-if="command.combo" #suffix>
						<KeyboardShortcut :combo="command.combo" />
					</template>
				</CommandPaletteItem>
			</CommandPaletteGroup>
		</CommandPaletteList>

		<CommandPaletteEmpty>
			{{ searching ? 'Searching…' : 'No results found.' }}
		</CommandPaletteEmpty>

		<CommandPaletteFooter>
			<KeyboardShortcut combo="Enter" /> to run · <KeyboardShortcut combo="Escape" /> to close
		</CommandPaletteFooter>
	</CommandPalette>
</template>

<script setup lang="ts">
import { computed, onScopeDispose, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { KeyboardShortcut, useCall, type KeyboardShortcutCombo } from 'frappe-ui'
import {
	CommandPalette,
	CommandPaletteEmpty,
	CommandPaletteFooter,
	CommandPaletteGroup,
	CommandPaletteInput,
	CommandPaletteItem,
	CommandPaletteList,
	type CommandPaletteValue,
} from 'frappe-ui/experimental'
import { useOverlays } from '@/composables/useOverlays'
import { fileKindStyle } from '@/lib/fileType'

interface AssetResult {
	name: string
	file_name: string
	project?: string
	project_name?: string
	category?: string
	file_type?: string
}

interface ProjectResult {
	name: string
	project_name: string
	status?: string
}

interface Command {
	kind: 'command'
	id: string
	label: string
	icon: string
	keywords: string[]
	combo?: KeyboardShortcutCombo
	run: () => void
}

type Pick = Command | { kind: 'asset' | 'project'; name: string }

const MIN_QUERY = 2
const DEBOUNCE_MS = 300

const route = useRoute()
const router = useRouter()
const { commandPaletteOpen, createProjectOpen, openSettings, openUpload } = useOverlays()

const query = ref('')
const debounced = ref('')
let timer: ReturnType<typeof setTimeout> | undefined

/** `/projects/:id` and `/projects/:id/folder/:f` scope the asset search. */
const currentProjectId = computed(() => {
	const match = route.path.match(/^\/projects\/([^/]+)/)
	return match ? match[1] : null
})

const placeholder = computed(() =>
	currentProjectId.value ? 'Search in project or type a command…' : 'Type a command or search…',
)
const assetGroupLabel = computed(() => (currentProjectId.value ? 'Files in project' : 'Files'))

const assetSearch = useCall<
	{ results: AssetResult[] },
	{ query: string; project?: string; limit: number }
>({
	url: '/api/v2/method/vms.api.search_assets',
	method: 'GET',
	immediate: false,
})

const projectSearch = useCall<{ results: ProjectResult[] }, { query: string; limit: number }>({
	url: '/api/v2/method/vms.api.search_projects',
	method: 'GET',
	immediate: false,
})

const shouldSearch = computed(
	() => query.value.trim().length >= MIN_QUERY && debounced.value.length >= MIN_QUERY,
)
const searching = computed(
	() =>
		query.value.trim().length >= MIN_QUERY &&
		(debounced.value !== query.value.trim() || assetSearch.loading || projectSearch.loading),
)
const assetResults = computed(() => (shouldSearch.value ? (assetSearch.data?.results ?? []) : []))
const projectResults = computed(() =>
	shouldSearch.value && !currentProjectId.value ? (projectSearch.data?.results ?? []) : [],
)

const commands: Command[] = [
	nav('dashboard', 'Go to Dashboard', 'lucide-home', ['home', 'overview'], '/'),
	nav(
		'uncategorised',
		'Go to Uncategorised',
		'lucide-inbox',
		['inbox', 'uploads'],
		'/uncategorised',
	),
	nav('projects', 'Go to Projects', 'lucide-folder', ['folders', 'videos'], '/projects'),
	nav(
		'audit-logs',
		'Go to Audit Logs',
		'lucide-scroll-text',
		['history', 'activity'],
		'/audit-logs',
	),
	nav('trash', 'Go to Trash', 'lucide-trash-2', ['deleted', 'bin'], '/trash'),
	action('upload', 'Upload Files', 'lucide-upload', ['add', 'import'], () => openUpload(), 'U'),
	action('new-project', 'New Project', 'lucide-folder-plus', ['create'], () => {
		createProjectOpen.value = true
	}),
	action(
		'settings',
		'Open Settings',
		'lucide-settings',
		['preferences', 'config'],
		() => openSettings('general'),
		'Mod+Comma',
	),
	action('invite', 'Invite User', 'lucide-user-plus', ['add user', 'team'], () =>
		openSettings('users'),
	),
	action('profile', 'Profile', 'lucide-circle-user', ['account', 'me'], () =>
		openSettings('profile'),
	),
]

const navigation = computed(() => matching(commands.filter((c) => c.id.startsWith('nav:'))))
const actions = computed(() => matching(commands.filter((c) => c.id.startsWith('action:'))))

watch(query, (value) => {
	clearTimeout(timer)
	const trimmed = value.trim()
	if (trimmed.length < MIN_QUERY) {
		debounced.value = ''
		return
	}
	timer = setTimeout(() => {
		debounced.value = trimmed
	}, DEBOUNCE_MS)
})

watch([debounced, currentProjectId], ([value, project]) => {
	if (value.length < MIN_QUERY) return
	void assetSearch.submit({ query: value, project: project ?? undefined, limit: 8 })
	if (!project) void projectSearch.submit({ query: value, limit: 5 })
})

onScopeDispose(() => clearTimeout(timer))

function matching(list: Command[]): Command[] {
	const needle = query.value.trim().toLowerCase()
	if (!needle) return list
	return list.filter(
		(c) => c.label.toLowerCase().includes(needle) || c.keywords.some((k) => k.includes(needle)),
	)
}

async function run(value: CommandPaletteValue) {
	const pick = value as Pick
	if (pick.kind === 'command') {
		pick.run()
		return
	}
	await router.push(pick.kind === 'asset' ? `/review/${pick.name}` : `/projects/${pick.name}`)
}

function nav(id: string, label: string, icon: string, keywords: string[], to: string): Command {
	return {
		kind: 'command',
		id: `nav:${id}`,
		label,
		icon,
		keywords,
		run: () => void router.push(to),
	}
}

function action(
	id: string,
	label: string,
	icon: string,
	keywords: string[],
	run: () => void,
	combo?: KeyboardShortcutCombo,
): Command {
	return { kind: 'command', id: `action:${id}`, label, icon, keywords, run, combo }
}
</script>
