// frontend-react/src/components/CreateFolderDialog.tsx
import { useState } from "react"
import { useFrappePostCall } from "frappe-react-sdk"
import { toast } from "sonner"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

interface CreateFolderDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  project: string
  /** Folder the new one goes inside. Null/undefined creates it at the project root. */
  parentFolder?: string | null
  /** Name of the parent folder, for the dialog copy. */
  parentFolderName?: string | null
  onComplete?: () => void
}

export function CreateFolderDialog({
  open,
  onOpenChange,
  project,
  parentFolder,
  parentFolderName,
  onComplete,
}: CreateFolderDialogProps) {
  const [folderName, setFolderName] = useState("")
  const { call: createFolder, loading } = useFrappePostCall("vms.api.create_folder")

  const handleCreate = async () => {
    const trimmed = folderName.trim()
    if (!trimmed) {
      toast.error("Folder name cannot be empty")
      return
    }

    try {
      await createFolder({ folder_name: trimmed, project, parent_folder: parentFolder ?? undefined })
      toast.success(`Folder "${trimmed}" created`)
      setFolderName("")
      onOpenChange(false)
      onComplete?.()
    } catch (e: unknown) {
      const message = e instanceof Error ? e.message : "Failed to create folder"
      toast.error(message)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>New Folder</DialogTitle>
          <DialogDescription>
            {parentFolder
              ? `Create a new folder inside “${parentFolderName ?? "this folder"}”.`
              : "Create a new folder in this project."}
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-2">
          <Label htmlFor="folder-name">Folder Name</Label>
          <Input
            id="folder-name"
            value={folderName}
            onChange={(e) => setFolderName(e.target.value)}
            placeholder="Enter folder name"
            onKeyDown={(e) => {
              if (e.key === "Enter" && !loading) handleCreate()
            }}
            autoFocus
          />
        </div>
        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={loading}
          >
            Cancel
          </Button>
          <Button onClick={handleCreate} disabled={loading || !folderName.trim()}>
            {loading ? "Creating..." : "Create"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// frontend/src/components/folders/CreateFolderDialog.vue
<template>
	<Dialog
		:open="open"
		title="New folder"
		size="sm"
		:actions="[
			{
				label: 'Create',
				variant: 'solid',
				loading: create.loading,
				disabled: !name.trim(),
				onClick: submit,
			},
			{ label: 'Cancel' },
		]"
		@update:open="emit('update:open', $event)"
	>
		<FormControl
			v-model="name"
			label="Folder name"
			:description="
				parentName ? `Created inside ${parentName}.` : 'Created at the project root.'
			"
			required
			autofocus
			:error="create.error?.message"
			@keydown.enter.prevent="submit({ close: closeDialog })"
		/>
	</Dialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { Dialog, FormControl, toast, useCall } from 'frappe-ui'
import type { Folder } from '@/types'
import { serverMessage } from '@/lib/format'

const props = defineProps<{
	open: boolean
	project: string
	parentFolder?: string | null
	parentName?: string
}>()
const emit = defineEmits<{ 'update:open': [value: boolean]; created: [folder: Folder] }>()
const name = ref('')

function closeDialog() {
	emit('update:open', false)
}

watch(
	() => props.open,
	(open) => {
		if (open) name.value = ''
	},
)

const create = useCall<Folder, { folder_name: string; project: string; parent_folder?: string }>({
	url: '/api/v2/method/vms.api.create_folder',
	method: 'POST',
	immediate: false,
})

async function submit({ close }: { close: () => void }) {
	const folderName = name.value.trim()
	if (!folderName) return
	try {
		const folder = await create.submit({
			folder_name: folderName,
			project: props.project,
			parent_folder: props.parentFolder || undefined,
		})
		if (folder) emit('created', folder)
		toast.success(`Folder “${folderName}” created`)
		close()
	} catch (error) {
		toast.error(serverMessage(error) || 'Could not create folder')
	}
}
</script>
