// frontend/src/components/MoveFolderDialog.tsx
import { useMemo, useState } from "react"
import { useFrappeGetDocList, useFrappePostCall } from "frappe-react-sdk"
import { toast } from "sonner"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import type { VMSFolder } from "@/types"
import { buildFolderOptions, collectDescendants } from "@/lib/folderPaths"

interface MoveFolderDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  folder: VMSFolder
  project: string
  onComplete?: () => void
}

const ROOT_VALUE = "__root__"

export function MoveFolderDialog({
  open,
  onOpenChange,
  folder,
  project,
  onComplete,
}: MoveFolderDialogProps) {
  const [target, setTarget] = useState<string>("")
  const { call: moveFolder, loading } = useFrappePostCall("vms.api.move_folder")

  // Reset on close rather than in an effect on open — the dialog is unmounted-ish
  // between uses anyway, and a stale destination from the last folder would be wrong.
  const handleOpenChange = (next: boolean) => {
    if (!next) setTarget("")
    onOpenChange(next)
  }

  const { data: folders } = useFrappeGetDocList<VMSFolder>("VMS Folder", {
    fields: ["name", "folder_name", "parent_folder"],
    filters: [["project", "=", project], ["deleted_at", "is", "not set"]],
    orderBy: { field: "folder_name", order: "asc" },
    limit: 500,
  })

  // A folder can't move into itself or into anything beneath it, and moving it
  // where it already is would be a no-op.
  const destinations = useMemo(() => {
    const all = folders ?? []
    const blocked = collectDescendants(all, folder.name)
    return buildFolderOptions(all).filter(
      (f) => !blocked.has(f.name) && f.name !== folder.parent_folder,
    )
  }, [folders, folder.name, folder.parent_folder])

  const handleMove = async () => {
    if (!target) {
      toast.error("Please select a destination")
      return
    }

    try {
      const parent = target === ROOT_VALUE ? null : target
      await moveFolder({ folder_name_id: folder.name, parent_folder: parent })
      toast.success(`Moved "${folder.folder_name}"`)
      handleOpenChange(false)
      onComplete?.()
    } catch (e: unknown) {
      const message = e instanceof Error ? e.message : "Failed to move folder"
      toast.error(message)
    }
  }

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Move Folder</DialogTitle>
          <DialogDescription>
            Move “{folder.folder_name}” and everything inside it to another folder.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-2">
          <Label>Destination</Label>
          <Select value={target} onValueChange={setTarget}>
            <SelectTrigger className="w-full">
              <SelectValue>
                {(value: string | null) => {
                  if (!value) return "Select a folder..."
                  if (value === ROOT_VALUE) return "Project Root (no folder)"
                  return destinations.find((f) => f.name === value)?.path ?? value
                }}
              </SelectValue>
            </SelectTrigger>
            <SelectContent>
              {folder.parent_folder && (
                <SelectItem value={ROOT_VALUE}>Project Root (no folder)</SelectItem>
              )}
              {destinations.map((f) => (
                <SelectItem key={f.name} value={f.name}>
                  {f.ancestors.length > 0 && (
                    <span className="text-muted-foreground">
                      {f.ancestors.join(" / ")} /{" "}
                    </span>
                  )}
                  {f.folderName}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => handleOpenChange(false)} disabled={loading}>
            Cancel
          </Button>
          <Button onClick={handleMove} disabled={loading || !target}>
            {loading ? "Moving..." : "Move"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// frontend/src/components/folders/MoveFolderDialog.vue
<template>
	<Dialog
		:open="open"
		title="Move folder"
		size="sm"
		:actions="[
			{
				label: 'Move',
				variant: 'solid',
				loading: move.loading,
				disabled: !target,
				onClick: submit,
			},
			{ label: 'Cancel' },
		]"
		@update:open="emit('update:open', $event)"
	>
		<div class="space-y-4">
			<FormControl
				v-model="targetProject"
				type="select"
				label="Project"
				:options="projectOptions"
			/>
			<FormControl
				v-model="target"
				type="select"
				label="Destination"
				:options="folderOptions"
				placeholder="Choose a destination"
				:error="move.error?.message"
			/>
			<p v-if="targetProject !== sourceProject" class="text-p-sm text-ink-gray-5">
				Everything inside this folder moves to the selected project.
			</p>
		</div>
	</Dialog>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Dialog, FormControl, toast, useCall, useList } from 'frappe-ui'
import type { Folder, Project } from '@/types'
import { buildFolderOptions, collectDescendants } from '@/lib/folderPaths'
import { serverMessage } from '@/lib/format'

const ROOT = '__root__'
const props = defineProps<{ open: boolean; folder: Folder; sourceProject: string }>()
const emit = defineEmits<{ 'update:open': [value: boolean]; changed: [project: string] }>()
const targetProject = ref(props.sourceProject)
const target = ref('')

watch(
	() => props.open,
	(open) => {
		if (!open) return
		targetProject.value = props.sourceProject
		target.value = ''
	},
)
watch(targetProject, () => (target.value = ''))

const projects = useList<Pick<Project, 'name' | 'project_name'>>({
	doctype: 'VMS Project',
	fields: ['name', 'project_name'],
	orderBy: 'project_name asc',
	limit: 500,
	cacheKey: 'move-folder-projects',
})
const folders = useList<Pick<Folder, 'name' | 'folder_name' | 'parent_folder' | 'project'>>({
	doctype: 'VMS Folder',
	fields: ['name', 'folder_name', 'parent_folder', 'project'],
	filters: () => ({ project: targetProject.value, deleted_at: ['is', 'not set'] }),
	orderBy: 'folder_name asc',
	limit: 500,
	cacheKey: ['move-folder-destinations', targetProject],
})

const projectOptions = computed(() =>
	(projects.data ?? []).map((project) => ({ label: project.project_name, value: project.name })),
)
const folderOptions = computed(() => {
	const all = (folders.data ?? []) as Folder[]
	const crossProject = targetProject.value !== props.sourceProject
	const blocked = crossProject ? new Set<string>() : collectDescendants(all, props.folder.name)
	return [
		...(props.folder.parent_folder || crossProject
			? [{ label: 'Project root', value: ROOT }]
			: []),
		...buildFolderOptions(all)
			.filter(
				(folder) => !blocked.has(folder.name) && folder.name !== props.folder.parent_folder,
			)
			.map((folder) => ({ label: folder.path, value: folder.name })),
	]
})

const move = useCall<
	unknown,
	{ folder_name_id: string; parent_folder: string | null; target_project: string }
>({
	url: '/api/v2/method/vms.api.move_folder',
	method: 'POST',
	immediate: false,
})

async function submit({ close }: { close: () => void }) {
	if (!target.value) return
	try {
		await move.submit({
			folder_name_id: props.folder.name,
			parent_folder: target.value === ROOT ? null : target.value,
			target_project: targetProject.value,
		})
		toast.success(`Moved “${props.folder.folder_name}”`)
		emit('changed', targetProject.value)
		close()
	} catch (error) {
		toast.error(serverMessage(error) || 'Could not move folder')
	}
}
</script>
