// frontend/src/components/review/CommentItem.tsx
import { useState, useRef, useCallback } from "react"
import Lightbox from "yet-another-react-lightbox"
import Zoom from "yet-another-react-lightbox/plugins/zoom"
import Fullscreen from "yet-another-react-lightbox/plugins/fullscreen"
import "yet-another-react-lightbox/styles.css"
import { Button } from "@/components/ui/button"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog"
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { formatTimestamp } from "@/hooks/useVideoPlayer"
import { CommentEditor, type CommentEditorHandle } from "./CommentEditor"
import type { VMSReviewComment } from "@/types"
import { Check, CircleCheck, Clock, Copy, PenTool, Pencil, Reply, Trash2 } from "lucide-react"

interface CommentItemProps {
  comment: VMSReviewComment
  replies: VMSReviewComment[]
  onSeek: (time: number) => void
  onReply: (parentName: string, timestamp?: number | null) => void
  onResolve: (name: string, resolved: boolean) => void
  onDelete: (name: string) => void
  onEdit: (name: string, newText: string) => Promise<void>
  onViewAnnotation?: (commentName: string, timestamp?: number | null) => void
  onEditAnnotation?: (commentName: string, timestamp?: number | null) => Promise<void>
  currentUser?: string
  isNested?: boolean
  isGuest?: boolean
}

export function CommentItem({
  comment,
  replies,
  onSeek,
  onReply,
  onResolve,
  onDelete,
  onEdit,
  onViewAnnotation,
  onEditAnnotation,
  currentUser,
  isNested = false,
  isGuest = false,
}: CommentItemProps) {
  const [showReplies, setShowReplies] = useState(true)
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false)
  const [showEditDialog, setShowEditDialog] = useState(false)
  const [isEditing, setIsEditing] = useState(false)
  const [lightboxOpen, setLightboxOpen] = useState(false)
  const [lightboxIndex, setLightboxIndex] = useState(0)
  const [lightboxSlides, setLightboxSlides] = useState<{ src: string }[]>([])
  const [copied, setCopied] = useState(false)
  const editEditorRef = useRef<CommentEditorHandle>(null)

  const handleCopy = useCallback(async () => {
    const tmp = document.createElement("div")
    tmp.innerHTML = comment.comment_text
    const text = (tmp.textContent || tmp.innerText || "").trim()
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 1500)
    } catch {
      // clipboard may be unavailable (e.g. insecure context); silently ignore
    }
  }, [comment.comment_text])
  const handleCommentClick = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      const target = e.target as HTMLElement
      if (target.tagName === "IMG") {
        e.stopPropagation()
        const container = target.closest("[data-comment-body]")
        if (!container) return
        const imgs = Array.from(container.querySelectorAll("img"))
        const slides = imgs.map((img) => ({ src: img.src }))
        const index = imgs.indexOf(target as HTMLImageElement)
        setLightboxSlides(slides)
        setLightboxIndex(index >= 0 ? index : 0)
        setLightboxOpen(true)
      }
    },
    [],
  )

  const hasTimestamp = comment.video_timestamp != null
  const isGuestComment = !!comment.guest_name && !comment.commented_by
  const isOwnComment = !!currentUser && comment.commented_by === currentUser

  return (
    <div className={isNested ? "ml-8 border-l pl-3" : ""}>
      <div
        className={`group cursor-pointer rounded-md px-3 py-2 hover:bg-muted/50 ${comment.is_resolved ? "opacity-60" : ""}`}
        onClick={() => {
          if (comment.has_annotation === 1) {
            onViewAnnotation?.(comment.name, comment.video_timestamp)
          } else if (hasTimestamp) {
            onSeek(comment.video_timestamp!)
          }
        }}
      >
        <div className="flex items-start gap-2">
          <Avatar size="sm" className="mt-0.5 shrink-0">
            {comment.commenter_image && (
              <AvatarImage src={comment.commenter_image} alt={comment.commenter_name} />
            )}
            <AvatarFallback>
              {comment.commenter_name?.[0]?.toUpperCase() ?? "?"}
            </AvatarFallback>
          </Avatar>

          <div className="min-w-0 flex-1">
            <div className="flex items-center gap-2">
              <span className="text-sm font-medium truncate">
                {comment.commenter_name}
              </span>
              {isGuestComment && (
                <Badge variant="outline" className="text-[10px] shrink-0">Guest</Badge>
              )}
              {hasTimestamp && (
                <Badge
                  variant="secondary"
                  className="cursor-pointer font-mono text-[10px] shrink-0"
                  onClick={() =>
                    comment.has_annotation === 1
                      ? onViewAnnotation?.(comment.name, comment.video_timestamp)
                      : onSeek(comment.video_timestamp!)
                  }
                >
                  <Clock size={10} />
                  {formatTimestamp(comment.video_timestamp!)}
                </Badge>
              )}
              {comment.has_annotation === 1 && (
                <Badge
                  variant="secondary"
                  className="cursor-pointer text-[10px] shrink-0 gap-0.5"
                  onClick={() => onViewAnnotation?.(comment.name, comment.video_timestamp)}
                  title="View annotation"
                >
                  <PenTool size={10} />
                  Drawing
                </Badge>
              )}
              {comment.is_resolved === 1 && (
                <Badge variant="outline" className="text-[10px] shrink-0">
                  Resolved
                </Badge>
              )}
            </div>

            <div
              data-comment-body
              className="mt-0.5 text-sm text-foreground break-words [&_p]:mb-0 [&_.mention]:rounded [&_.mention]:bg-primary/10 [&_.mention]:px-1 [&_.mention]:py-0.5 [&_.mention]:font-medium [&_.mention]:text-primary [&_img]:mt-1.5 [&_img]:max-w-full [&_img]:rounded-md [&_img]:max-h-48 [&_img]:object-contain [&_img]:cursor-zoom-in"
              dangerouslySetInnerHTML={{ __html: comment.comment_text }}
              onClick={handleCommentClick}
            />

            <div className="mt-1 flex items-center gap-1">
              <span className="text-[10px] text-muted-foreground">
                {new Date(comment.creation).toLocaleString(undefined, {
                  month: "short",
                  day: "numeric",
                  hour: "numeric",
                  minute: "2-digit",
                })}
                {comment.is_edited === 1 && (
                  <span className="ml-1 italic">(edited)</span>
                )}
              </span>

              <div className="ml-auto flex items-center gap-0.5 opacity-0 transition-opacity group-hover:opacity-100" onClick={(e) => e.stopPropagation()}>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={handleCopy}
                  title={copied ? "Copied!" : "Copy comment"}
                >
                  {copied ? (
                    <Check size={14} className="text-green-500" />
                  ) : (
                    <Copy size={14} />
                  )}
                </Button>
                {!isNested && (
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    onClick={() => onReply(comment.name, comment.video_timestamp)}
                    title="Reply"
                  >
                    <Reply size={14} />
                  </Button>
                )}
                {isOwnComment && comment.has_annotation === 1 && (
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    onClick={() => onEditAnnotation?.(comment.name, comment.video_timestamp)}
                    title="Edit drawing"
                  >
                    <PenTool size={14} />
                  </Button>
                )}
                {isOwnComment && (
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    onClick={() => setShowEditDialog(true)}
                    title="Edit"
                  >
                    <Pencil size={14} />
                  </Button>
                )}
                {!isGuest && (
                  <>
                    <Button
                      variant="ghost"
                      size="icon-sm"
                      onClick={() => onResolve(comment.name, comment.is_resolved === 0)}
                      title={comment.is_resolved ? "Unresolve" : "Resolve"}
                    >
                      <CircleCheck size={14}
                        className={comment.is_resolved ? "text-green-500" : ""} />
                    </Button>
                    <Button
                      variant="ghost"
                      size="icon-sm"
                      onClick={() => setShowDeleteConfirm(true)}
                      title="Delete"
                    >
                      <Trash2 size={14} />
                    </Button>
                  </>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Replies */}
      {replies.length > 0 && (
        <div>
          {replies.length > 1 && (
            <button
              className="ml-8 px-3 py-0.5 text-[11px] text-muted-foreground hover:text-foreground"
              onClick={() => setShowReplies(!showReplies)}
            >
              {showReplies ? "Hide" : "Show"} {replies.length} {replies.length === 1 ? "reply" : "replies"}
            </button>
          )}
          {showReplies &&
            replies.map((reply) => (
              <CommentItem
                key={reply.name}
                comment={reply}
                replies={[]}
                onSeek={onSeek}
                onReply={onReply}
                onResolve={onResolve}
                onDelete={onDelete}
                onEdit={onEdit}
                onViewAnnotation={onViewAnnotation}
                onEditAnnotation={onEditAnnotation}
                currentUser={currentUser}
                isNested
                isGuest={isGuest}
              />
            ))}
        </div>
      )}

      <Lightbox
        open={lightboxOpen}
        close={() => setLightboxOpen(false)}
        index={lightboxIndex}
        slides={lightboxSlides}
        plugins={[Zoom, Fullscreen]}
      />

      <AlertDialog open={showDeleteConfirm} onOpenChange={setShowDeleteConfirm}>
        <AlertDialogContent size="sm">
          <AlertDialogHeader>
            <AlertDialogTitle>Delete comment</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this comment? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              variant="destructive"
              onClick={() => onDelete(comment.name)}
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      <Dialog open={showEditDialog} onOpenChange={setShowEditDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit comment</DialogTitle>
          </DialogHeader>
          <CommentEditor
            ref={editEditorRef}
            initialContent={comment.comment_text}
            placeholder="Edit your comment..."
            onSubmit={async () => {
              if (!editEditorRef.current || editEditorRef.current.isEmpty()) return
              setIsEditing(true)
              try {
                await onEdit(comment.name, editEditorRef.current.getHTML())
                setShowEditDialog(false)
              } finally {
                setIsEditing(false)
              }
            }}
          />
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setShowEditDialog(false)}
              disabled={isEditing}
            >
              Cancel
            </Button>
            <Button
              disabled={isEditing}
              onClick={async () => {
                if (!editEditorRef.current || editEditorRef.current.isEmpty()) return
                setIsEditing(true)
                try {
                  await onEdit(comment.name, editEditorRef.current.getHTML())
                  setShowEditDialog(false)
                } finally {
                  setIsEditing(false)
                }
              }}
            >
              {isEditing ? "Saving..." : "Save"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// frontend/src/components/review/CommentItem.vue
<template>
	<div :class="nested ? 'ml-8 border-l border-outline-gray-1 pl-2' : ''">
		<div
			class="group rounded-lg px-3 py-2"
			:class="[
				interactive ? 'cursor-pointer hover:bg-surface-gray-1' : '',
				comment.is_resolved ? 'opacity-60' : '',
			]"
			@click="openComment"
		>
			<div class="flex items-start gap-2.5">
				<Avatar
					class="mt-0.5 shrink-0"
					size="lg"
					:label="comment.commenter_name"
					:image="comment.commenter_image || undefined"
				/>
				<div class="min-w-0 flex-1">
					<div class="flex flex-wrap items-center gap-1.5">
						<span class="truncate text-sm-medium text-ink-gray-8">
							{{ comment.commenter_name }}
						</span>
						<Badge v-if="isGuestComment" variant="outline" size="sm">Guest</Badge>
						<Button
							v-if="hasTimestamp"
							variant="subtle"
							size="sm"
							class="font-mono"
							@click.stop="openTimestamp"
						>
							<span class="lucide-clock-3 size-3" />
							{{ formatTimestamp(comment.video_timestamp ?? 0) }}
						</Button>
						<Badge v-if="comment.has_annotation" theme="blue" variant="subtle" size="sm">
							<span class="lucide-pen-tool size-3" />
							Drawing
						</Badge>
						<Badge v-if="comment.is_resolved" variant="outline" size="sm">Resolved</Badge>
					</div>

					<div
						data-comment-body
						class="comment-body mt-1 break-words text-sm text-ink-gray-8"
						@click="handleBodyClick"
						v-html="comment.comment_text"
					/>

					<div class="mt-1.5 flex min-h-6 items-center gap-1">
						<span class="text-xs text-ink-gray-5" :title="formatDateTime(comment.creation)">
							{{ fromNow(comment.creation) }}
							<template v-if="comment.is_edited"> · edited</template>
						</span>
						<div
							class="ml-auto flex items-center gap-0.5 opacity-100 sm:opacity-0 sm:group-hover:opacity-100"
							@click.stop
						>
							<Button
								variant="ghost"
								size="sm"
								:aria-label="copied ? 'Copied' : 'Copy comment'"
								:title="copied ? 'Copied' : 'Copy comment'"
								@click="copyComment"
							>
								<span :class="copied ? 'lucide-check' : 'lucide-copy'" class="size-3.5" />
							</Button>
							<Button
								v-if="!nested"
								variant="ghost"
								size="sm"
								aria-label="Reply"
								title="Reply"
								@click="emit('reply', comment)"
							>
								<span class="lucide-reply size-3.5" />
							</Button>
							<Button
								v-if="isOwner && comment.has_annotation"
								variant="ghost"
								size="sm"
								aria-label="Edit drawing"
								title="Edit drawing"
								@click="emit('edit-annotation', comment)"
							>
								<span class="lucide-pen-tool size-3.5" />
							</Button>
							<Button
								v-if="isOwner"
								variant="ghost"
								size="sm"
								aria-label="Edit comment"
								title="Edit"
								@click="openEditor"
							>
								<span class="lucide-pencil size-3.5" />
							</Button>
							<Button
								v-if="!review.isGuest.value"
								variant="ghost"
								size="sm"
								:aria-label="comment.is_resolved ? 'Reopen comment' : 'Resolve comment'"
								:title="comment.is_resolved ? 'Reopen' : 'Resolve'"
								@click="emit('resolve', comment, !comment.is_resolved)"
							>
								<span class="lucide-circle-check size-3.5" />
							</Button>
							<Button
								v-if="!review.isGuest.value"
								variant="ghost"
								theme="red"
								size="sm"
								aria-label="Delete comment"
								title="Delete"
								@click="confirmDelete"
							>
								<span class="lucide-trash-2 size-3.5" />
							</Button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div v-if="replies.length">
			<Button
				v-if="replies.length > 1"
				variant="ghost"
				size="sm"
				class="ml-9"
				@click="repliesOpen = !repliesOpen"
			>
				<span :class="repliesOpen ? 'lucide-chevron-up' : 'lucide-chevron-down'" class="size-3" />
				{{ repliesOpen ? 'Hide' : 'Show' }} {{ replies.length }} replies
			</Button>
			<CommentItem
				v-for="reply in repliesOpen ? replies : []"
				:key="reply.name"
				:comment="reply"
				:replies="[]"
				nested
				@seek="(time) => emit('seek', time)"
				@reply="(item) => emit('reply', item)"
				@resolve="(item, resolved) => emit('resolve', item, resolved)"
				@remove="(item) => emit('remove', item)"
				@edit="(item, html) => emit('edit', item, html)"
				@view-annotation="(item) => emit('view-annotation', item)"
				@edit-annotation="(item) => emit('edit-annotation', item)"
			/>
		</div>

		<Dialog v-model:open="editOpen" title="Edit comment">
			<CommentEditor
				v-model="editDraft"
				placeholder="Edit your comment…"
				submit-label="Save"
				:submitting="saving"
				:prompt-for-guest="false"
				@submit="saveEdit"
			/>
		</Dialog>

		<Dialog v-model:open="previewOpen" bare size="xl">
			<template #default="{ close }">
				<div class="relative grid min-h-64 place-items-center bg-black-overlay-900 p-4">
					<Button
						variant="ghost"
						class="absolute right-3 top-3 text-ink-white"
						aria-label="Close image preview"
						@click="close"
					>
						<span class="lucide-x size-5" />
					</Button>
					<img :src="previewSource" alt="Comment attachment" class="max-h-[80vh] max-w-full object-contain" />
				</div>
			</template>
		</Dialog>
	</div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { Avatar, Badge, Button, Dialog, dialog } from 'frappe-ui'
import type { ReviewComment } from '@/types'
import CommentEditor from '@/components/review/CommentEditor.vue'
import { useReview } from '@/composables/useReview'
import { useSession } from '@/composables/useSession'
import { formatTimestamp } from '@/composables/useVideoPlayer'
import { formatDateTime, fromNow } from '@/lib/dates'

const props = withDefaults(
	defineProps<{ comment: ReviewComment; replies: ReviewComment[]; nested?: boolean }>(),
	{ nested: false },
)

const emit = defineEmits<{
	seek: [time: number]
	reply: [comment: ReviewComment]
	resolve: [comment: ReviewComment, resolved: boolean]
	remove: [comment: ReviewComment]
	edit: [comment: ReviewComment, html: string]
	'view-annotation': [comment: ReviewComment]
	'edit-annotation': [comment: ReviewComment]
}>()

const review = useReview()
const { userId } = useSession()
const repliesOpen = ref(true)
const copied = ref(false)
const editOpen = ref(false)
const editDraft = ref('')
const saving = ref(false)
const previewOpen = ref(false)
const previewSource = ref('')

const hasTimestamp = computed(() => props.comment.video_timestamp != null)
const interactive = computed(() => hasTimestamp.value || Boolean(props.comment.has_annotation))
const isGuestComment = computed(
	() => Boolean(props.comment.guest_name) && !props.comment.commented_by,
)
const isOwner = computed(
	() => Boolean(userId.value) && props.comment.commented_by === userId.value,
)

function openComment(event: MouseEvent) {
	if ((event.target as HTMLElement).closest('a, button, img')) return
	openTimestamp()
}

function openTimestamp() {
	if (props.comment.has_annotation) emit('view-annotation', props.comment)
	else if (props.comment.video_timestamp != null) emit('seek', props.comment.video_timestamp)
}

function handleBodyClick(event: MouseEvent) {
	const target = event.target as HTMLElement
	if (!(target instanceof HTMLImageElement)) return
	event.stopPropagation()
	previewSource.value = target.src
	previewOpen.value = true
}

async function copyComment() {
	const container = document.createElement('div')
	container.innerHTML = props.comment.comment_text
	try {
		await navigator.clipboard.writeText(container.textContent?.trim() ?? '')
		copied.value = true
		window.setTimeout(() => (copied.value = false), 1500)
	} catch {
		copied.value = false
	}
}

function openEditor() {
	editDraft.value = props.comment.comment_text
	editOpen.value = true
}

async function saveEdit(html: string) {
	if (saving.value) return
	saving.value = true
	try {
		emit('edit', props.comment, html)
		editOpen.value = false
	} finally {
		saving.value = false
	}
}

function confirmDelete() {
	dialog.danger({
		title: 'Delete comment?',
		message: props.replies.length
			? 'This comment and its replies will be deleted.'
			: 'This comment will be deleted.',
		onConfirm: () => emit('remove', props.comment),
	})
}
</script>

<style scoped>
.comment-body :deep(p) {
	margin: 0;
}

.comment-body :deep(.mention) {
	border-radius: 0.25rem;
	background: var(--surface-gray-2);
	padding: 0.125rem 0.25rem;
	font-weight: 500;
}

.comment-body :deep(img) {
	margin-top: 0.375rem;
	max-height: 12rem;
	max-width: 100%;
	cursor: zoom-in;
	border-radius: 0.5rem;
	object-fit: contain;
}
</style>
