// frontend/src/components/review/ImageViewer.tsx
import { useRef, useEffect, useState } from "react"
import { useFrappePostCall } from "frappe-react-sdk"
import { useReviewContext } from "@/hooks/useReviewContext"
import { useFullscreen } from "@/hooks/useFullscreen"
import { AnnotationCanvas } from "./AnnotationCanvas"

interface ImageViewerProps {
  assetName: string
}

export function ImageViewer({ assetName }: ImageViewerProps) {
  const { replayAnnotation, annotationMode, dismissReplay, token } = useReviewContext()

  const containerRef = useRef<HTMLDivElement>(null)
  const imageWrapperRef = useRef<HTMLDivElement>(null)
  const [imageUrl, setImageUrl] = useState<string | null>(null)

  const { call: getViewUrl } = useFrappePostCall("vms.review_api.get_review_view_url")
  const { isFullscreen, toggle: toggleFullscreen } = useFullscreen(containerRef)

  useEffect(() => {
    if (!assetName) return
    const params: Record<string, string> = { asset_name: assetName }
    if (token) params.token = token
    getViewUrl(params).then((res) => {
      setImageUrl(res.message.url)
    })
  }, [assetName, token, getViewUrl])

  const isCanvasActive = annotationMode || !!replayAnnotation

  return (
    <div ref={containerRef} className="flex flex-col overflow-hidden rounded-lg border bg-black md:h-full">
      <div
        ref={imageWrapperRef}
        className="relative flex flex-1 items-center justify-center bg-black min-h-[300px] md:min-h-0"
        onDoubleClick={toggleFullscreen}
      >
        {imageUrl ? (
          <img
            src={imageUrl}
            alt="Review image"
            className="max-h-full max-w-full object-contain"
            onClick={isCanvasActive ? undefined : () => {}}
            draggable={false}
          />
        ) : (
          <div className="flex items-center justify-center text-muted-foreground text-sm">
            Loading image...
          </div>
        )}
        <AnnotationCanvas
          videoContainerRef={imageWrapperRef}
          isActive={isCanvasActive}
          readOnly={!!replayAnnotation}
          annotationData={replayAnnotation}
        />
      </div>
      {isFullscreen && (
        <div className="absolute bottom-2 right-2 text-xs text-muted-foreground/50">
          Double-click to exit fullscreen
        </div>
      )}
    </div>
  )
}

// frontend/src/components/review/ImageViewer.vue
<template>
	<div
		ref="container"
		class="relative flex min-h-[300px] flex-1 items-center justify-center overflow-hidden rounded-lg bg-black md:min-h-0"
		data-testid="review-image-viewer"
		@dblclick="toggle"
	>
		<img
			v-if="view.data?.url"
			:src="view.data.url"
			:alt="review.asset.value?.file_name || 'Review image'"
			class="max-h-full max-w-full object-contain"
			draggable="false"
		/>
		<ErrorMessage v-else-if="view.error" message="This image could not be loaded." />
		<LoadingIndicator v-else class="text-ink-gray-4" />

		<AnnotationCanvas
			:target="container"
			:active="review.annotation.mode.value !== 'off'"
			:read-only="review.annotation.mode.value === 'view'"
			:annotation-data="review.annotation.data.value"
		/>
	</div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { ErrorMessage, LoadingIndicator, useCall } from 'frappe-ui'
import type { ViewUrlResponse } from '@/types'
import AnnotationCanvas from '@/components/review/AnnotationCanvas.vue'
import { useFullscreen } from '@/composables/useFullscreen'
import { useReview } from '@/composables/useReview'

const props = defineProps<{ assetName: string }>()
const review = useReview()
const container = ref<HTMLElement | null>(null)
const { toggle } = useFullscreen(container)

const view = useCall<ViewUrlResponse, { asset_name: string; token?: string }>({
	url: '/api/v2/method/vms.review_api.get_review_view_url',
	method: 'GET',
	params: {
		asset_name: props.assetName,
		...(review.token ? { token: review.token } : {}),
	},
	cacheKey: ['review-image-url', props.assetName, review.token ?? 'session'],
})
</script>
