// frontend/src/components/review/ReviewHeader.tsx
import { useState } from "react"
import { useNavigate } from "react-router"
import { YoutubeIcon } from "@/components/icons/YoutubeIcon"
import { Button, buttonVariants } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog"
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu"
import { Spinner } from "@/components/ui/spinner"
import { useDownload } from "@/hooks/useDownload"
import { useReviewContext } from "@/hooks/useReviewContext"
import { toast } from "sonner"
import { ArrowLeft, Captions, Copy, Download, GitFork, Layers, Link, Scissors, Settings2, Share2, Video } from "lucide-react"

interface ReviewHeaderProps {
  assetName: string
  fileName: string
  fileType?: string
  category?: string
  project?: { name: string; project_name: string } | null
  folder?: { name: string; folder_name: string } | null
  isPublicReview?: boolean
  reviewToken?: string | null
  onTogglePublicReview?: (enable: boolean) => Promise<void>
  transcriptionStatus?: string
  onTranscribe?: () => Promise<void>
  isTranscribing?: boolean
  onOpenTranscription?: () => void
  assetStatus?: string
  splitProgress?: { stage: string; current: number; total: number } | null
  onOpenSplit?: () => void
  splitFrom?: { name: string; file_name: string } | null
  splitParts?: { name: string; file_name: string }[] | null
  proxyStatus?: string
  onGenerateProxy?: () => Promise<void>
  isGeneratingProxy?: boolean
  youtubeUploadStatus?: string
  youtubeVideoUrl?: string
  /** Channel the asset was uploaded to; "" before any upload. */
  youtubeChannelName?: string
  onOpenYouTubeUpload?: () => void
  onResetYouTubeUpload?: () => void
  version?: number
  onOpenVersions?: () => void
}

export function ReviewHeader({
  assetName,
  fileName,
  fileType,
  category,
  project,
  folder,
  isPublicReview = false,
  reviewToken,
  onTogglePublicReview,
  transcriptionStatus,
  onTranscribe,
  isTranscribing,
  onOpenTranscription,
  assetStatus,
  splitProgress,
  onOpenSplit,
  splitFrom,
  splitParts,
  proxyStatus,
  onGenerateProxy,
  isGeneratingProxy,
  youtubeUploadStatus,
  youtubeVideoUrl,
  youtubeChannelName,
  onOpenYouTubeUpload,
  onResetYouTubeUpload,
  version,
  onOpenVersions,
}: ReviewHeaderProps) {
  const navigate = useNavigate()
  const { isGuest, token } = useReviewContext()
  const { downloadOne, isDownloading } = useDownload(token)
  const [toggling, setToggling] = useState(false)
  const [publicLinkOpen, setPublicLinkOpen] = useState(false)
  const isVideo = !fileType || fileType.startsWith("video/") || fileType.startsWith("audio/")

  // Return to the folder the asset lives in, not just the project root,
  // so the breadcrumb stays where the user left off.
  const projectUrl = project ? `/projects/${project.name}` : null
  const folderUrl = projectUrl && folder ? `${projectUrl}/folder/${folder.name}` : null

  const handleBack = () => {
    navigate(folderUrl || projectUrl || "/uncategorised")
  }

  const shareUrl = reviewToken
    ? `${window.location.origin}/vms/review/${assetName}?token=${reviewToken}`
    : ""

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl)
      toast.success("Link copied to clipboard")
    } catch {
      toast.error("Failed to copy link")
    }
  }

  const handleToggle = async (checked: boolean) => {
    if (!onTogglePublicReview) return
    setToggling(true)
    try {
      await onTogglePublicReview(checked)
    } finally {
      setToggling(false)
    }
  }

  return (
    <div className="flex items-center gap-2 border-b px-3 py-2 md:gap-3 md:px-4 md:py-2.5">
      {!isGuest && (
        <Button variant="ghost" size="icon-sm" onClick={handleBack}>
          <ArrowLeft size={18} />
        </Button>
      )}

      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-1.5 md:gap-2">
          {!isGuest && project && (
            <>
              <span
                className="hidden cursor-pointer text-xs text-muted-foreground hover:text-foreground truncate md:inline"
                onClick={() => navigate(projectUrl!)}
              >
                {project.project_name}
              </span>
              <span className="hidden text-xs text-muted-foreground md:inline">/</span>
              {folder && (
                <>
                  <span
                    className="hidden cursor-pointer text-xs text-muted-foreground hover:text-foreground truncate md:inline"
                    onClick={() => navigate(folderUrl!)}
                  >
                    {folder.folder_name}
                  </span>
                  <span className="hidden text-xs text-muted-foreground md:inline">/</span>
                </>
              )}
            </>
          )}
          <span className="text-xs font-medium truncate md:text-sm">{fileName}</span>
          {category && <Badge variant="outline" className="hidden shrink-0 text-[10px] md:inline-flex">{category}</Badge>}
          {splitFrom && (
            <Badge
              variant="secondary"
              className="hidden shrink-0 cursor-pointer text-[10px] gap-1 md:inline-flex"
              onClick={() => navigate(`/review/${splitFrom.name}`)}
            >
              <GitFork size={10} />
              Split from {splitFrom.file_name}
            </Badge>
          )}
          {splitParts && splitParts.length > 0 && (
            <Popover>
              <PopoverTrigger>
                <Badge variant="secondary" className="hidden shrink-0 cursor-pointer text-[10px] gap-1 md:inline-flex">
                  <GitFork size={10} />
                  {splitParts.length} {splitParts.length === 1 ? "part" : "parts"}
                </Badge>
              </PopoverTrigger>
              <PopoverContent className="w-64" align="start">
                <div className="space-y-1">
                  <p className="text-xs font-medium text-muted-foreground mb-2">Split parts</p>
                  {splitParts.map((part) => (
                    <div
                      key={part.name}
                      className="flex items-center gap-2 rounded px-2 py-1.5 text-xs cursor-pointer hover:bg-muted"
                      onClick={() => navigate(`/review/${part.name}`)}
                    >
                      <span className="truncate">{part.file_name}</span>
                    </div>
                  ))}
                </div>
              </PopoverContent>
            </Popover>
          )}
          {isGuest && (
            <Badge variant="secondary" className="text-[10px] shrink-0">Guest</Badge>
          )}
        </div>
      </div>

      {/* Versions button — auth users only, remains as-is */}
      {!isGuest && onOpenVersions && (
        <>
          <Button
            variant="outline"
            size="icon-sm"
            className="md:hidden"
            onClick={onOpenVersions}
            title="Version history"
          >
            <Layers size={16} />
          </Button>
          <Button
            variant="outline"
            size="sm"
            className="hidden md:inline-flex"
            onClick={onOpenVersions}
          >
            <Layers data-icon="inline-start" size={16} />
            {version && version > 1 ? `v${version}` : "Versions"}
          </Button>
        </>
      )}

      {/* Tools dropdown — auth users only */}
      {!isGuest && isVideo && (
        <DropdownMenu>
          <DropdownMenuTrigger className={buttonVariants({ variant: "outline", size: "sm" })}>
            <Settings2 data-icon="inline-start" size={16} />
            <span className="hidden md:inline">Tools</span>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            {/* Transcribe */}
            {transcriptionStatus === "Processing" ? (
              <DropdownMenuItem disabled>
                <Spinner className="size-3.5" />
                Transcribing...
              </DropdownMenuItem>
            ) : (
              <DropdownMenuItem onClick={onOpenTranscription}>
                <Captions size={16} />
                {transcriptionStatus === "Complete" ? "Transcript" : "Transcribe"}
              </DropdownMenuItem>
            )}

            {/* Split */}
            {assetStatus === "Processing" ? (
              <DropdownMenuItem disabled>
                <Spinner className="size-3.5" />
                {splitProgress?.stage === "downloading"
                  ? "Downloading..."
                  : splitProgress?.stage === "splitting"
                    ? "Splitting..."
                    : splitProgress?.stage === "uploading"
                      ? `Uploading ${splitProgress.current}/${splitProgress.total}...`
                      : "Splitting..."}
              </DropdownMenuItem>
            ) : (
              <DropdownMenuItem onClick={onOpenSplit}>
                <Scissors size={16} />
                Split
              </DropdownMenuItem>
            )}

            {/* Generate Proxy */}
            {!proxyStatus && (
              <DropdownMenuItem
                onClick={onGenerateProxy}
                disabled={isGeneratingProxy}
              >
                <Video size={16} />
                Generate Proxy
              </DropdownMenuItem>
            )}
            {proxyStatus === "Processing" && (
              <DropdownMenuItem disabled>
                <Spinner className="size-3.5" />
                Generating proxy...
              </DropdownMenuItem>
            )}
            {proxyStatus === "Ready" && (
              <DropdownMenuItem disabled>
                <Video size={16} />
                Proxy ready
              </DropdownMenuItem>
            )}
            {proxyStatus === "Error" && (
              <DropdownMenuItem
                onClick={onGenerateProxy}
                disabled={isGeneratingProxy}
              >
                <Video size={16} />
                Retry Proxy Generation
              </DropdownMenuItem>
            )}
          </DropdownMenuContent>
        </DropdownMenu>
      )}

      {/* Share dropdown — auth users only */}
      {!isGuest && (
        <DropdownMenu>
          <DropdownMenuTrigger className={buttonVariants({ variant: "outline", size: "sm" })}>
            <Share2 data-icon="inline-start" size={16} />
            <span className="hidden md:inline">Share</span>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            {/* Download */}
            <DropdownMenuItem
              onClick={() => downloadOne(assetName, fileName)}
              disabled={isDownloading}
            >
              <Download size={16} />
              Download
            </DropdownMenuItem>

            {/* Public Link */}
            <DropdownMenuItem onClick={() => setPublicLinkOpen(true)}>
              <Link size={16} />
              Public Link
            </DropdownMenuItem>

            <DropdownMenuSeparator />

            {/* YouTube */}
            {isVideo && (() => {
              if (youtubeUploadStatus === "Queued" || youtubeUploadStatus === "Uploading") {
                return (
                  <DropdownMenuItem disabled>
                    <Spinner className="size-3.5" />
                    {youtubeUploadStatus === "Queued" ? "Queued..." : "Uploading..."}
                  </DropdownMenuItem>
                )
              }
              if (youtubeUploadStatus === "Complete" && youtubeVideoUrl) {
                return (
                  <>
                    <DropdownMenuItem onClick={() => window.open(youtubeVideoUrl, "_blank")}>
                      <YoutubeIcon size={16} />
                      <span className="flex flex-col items-start">
                        View on YouTube
                        {youtubeChannelName && (
                          <span className="text-xs text-muted-foreground">
                            {youtubeChannelName}
                          </span>
                        )}
                      </span>
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={onResetYouTubeUpload}>
                      <YoutubeIcon size={16} />
                      Re-upload to YouTube
                    </DropdownMenuItem>
                  </>
                )
              }
              if (youtubeUploadStatus === "Error") {
                return (
                  <DropdownMenuItem onClick={onOpenYouTubeUpload}>
                    <YoutubeIcon size={16} />
                    Retry YouTube Upload
                  </DropdownMenuItem>
                )
              }
              return (
                <DropdownMenuItem onClick={onOpenYouTubeUpload}>
                  <YoutubeIcon size={16} />
                  YouTube
                </DropdownMenuItem>
              )
            })()}
          </DropdownMenuContent>
        </DropdownMenu>
      )}

      {/* Guest download button */}
      {isGuest && (
        <Button
          variant="outline"
          size="sm"
          onClick={() => downloadOne(assetName, fileName)}
          disabled={isDownloading}
        >
          <Download data-icon="inline-start" size={16} />
          Download
        </Button>
      )}

      {/* Public Link Dialog */}
      <Dialog open={publicLinkOpen} onOpenChange={setPublicLinkOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Public Review Link</DialogTitle>
            <DialogDescription>
              Share this link to allow anyone to view and comment on this asset.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <Label htmlFor="public-review-toggle" className="text-sm font-medium">
                Enable public link
              </Label>
              <Switch
                id="public-review-toggle"
                checked={isPublicReview}
                onCheckedChange={handleToggle}
                disabled={toggling}
              />
            </div>
            {isPublicReview && shareUrl && (
              <div className="flex items-center gap-2">
                <Input
                  value={shareUrl}
                  readOnly
                  className="text-xs"
                  onClick={(e) => (e.target as HTMLInputElement).select()}
                />
                <Button variant="outline" size="icon-sm" onClick={handleCopy}>
                  <Copy size={14} />
                </Button>
              </div>
            )}
            {isPublicReview && !shareUrl && (
              <p className="text-xs text-muted-foreground">Generating link...</p>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// frontend/src/components/review/ReviewHeader.vue
<template>
	<PageHeaderBase
		class="flex min-h-12 items-center gap-2 border-b border-outline-gray-1 bg-surface-base px-3 sm:px-4"
	>
		<Button variant="ghost" icon="lucide-arrow-left" aria-label="Back" @click="goBack" />
		<div class="flex min-w-0 flex-1 items-center gap-2">
			<h1 class="truncate text-base-semibold text-ink-gray-9">{{ asset.file_name }}</h1>
			<Button
				v-if="asset.version"
				variant="subtle"
				:label="`v${asset.version}`"
				@click="review.panels.versions.value = true"
			/>
			<Badge
				v-if="asset.status !== 'Ready'"
				:label="asset.status"
				:theme="assetStatusTheme(asset.status)"
			/>
		</div>

		<Button
			v-if="review.isGuest.value"
			variant="subtle"
			icon-left="lucide-download"
			label="Download"
			:loading="isDownloading"
			@click="downloadOne(asset.name, asset.file_name)"
		/>

		<template v-else>
			<Popover v-model:open="shareOpen" align="end">
				<template #trigger>
					<Button variant="solid" icon-left="lucide-share-2" label="Share" />
				</template>
				<div class="w-80 space-y-4 p-3">
					<Switch
						v-model="publicReview"
						label="Public review link"
						description="Anyone with this link can view and comment."
						:disabled="togglingPublic"
					/>
					<div v-if="publicReview && shareUrl" class="flex items-center gap-2">
						<TextInput
							:model-value="shareUrl"
							readonly
							aria-label="Review link"
							class="min-w-0 flex-1"
						/>
						<Button
							icon="lucide-copy"
							aria-label="Copy review link"
							@click="copyLink"
						/>
					</div>
				</div>
			</Popover>

			<Dropdown :options="menuOptions" align="end">
				<Button variant="ghost" icon="lucide-more-horizontal" aria-label="More actions" />
			</Dropdown>
		</template>
	</PageHeaderBase>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import {
	Badge,
	Button,
	Dropdown,
	PageHeaderBase,
	Popover,
	Switch,
	TextInput,
	toast,
	type DropdownOption,
} from 'frappe-ui'
import type { ReviewAsset } from '@/types'
import { assetStatusTheme } from '@/lib/status'
import { useDownload } from '@/composables/useDownload'
import { useReview } from '@/composables/useReview'
import YoutubeIcon from '@/components/common/YoutubeIcon.vue'

const props = defineProps<{
	asset: ReviewAsset
	proxyStatus?: string
	generatingProxy?: boolean
	togglingPublic?: boolean
}>()

const emit = defineEmits<{
	'toggle-public': [enabled: boolean]
	'generate-proxy': []
}>()

const router = useRouter()
const review = useReview()
const shareOpen = ref(false)
const { downloadOne, isDownloading } = useDownload(review.token)

const publicReview = computed({
	get: () => props.asset.is_public_review === 1,
	set: (enabled: boolean) => emit('toggle-public', enabled),
})

const shareUrl = computed(() => {
	if (!props.asset.review_token) return ''
	return `${window.location.origin}/vms/review/${props.asset.name}?token=${props.asset.review_token}`
})

const menuOptions = computed<DropdownOption[]>(() => {
	const options: DropdownOption[] = [
		{
			label: 'Download',
			icon: 'lucide-download',
			onClick: () => downloadOne(props.asset.name, props.asset.file_name),
		},
		{
			label: 'New version',
			icon: 'lucide-upload',
			onClick: () => (review.panels.versions.value = true),
		},
	]

	if (!props.asset.file_type?.startsWith('image/')) {
		options.push(
			{
				label:
					props.asset.transcription_status === 'Complete' ? 'Transcript' : 'Transcribe',
				icon: 'lucide-captions',
				onClick: () => (review.panels.transcription.value = true),
			},
			{
				label: 'Upload to YouTube',
				icon: YoutubeIcon,
				onClick: () => (review.panels.youtube.value = true),
			},
			{
				label: 'Split video',
				icon: 'lucide-scissors',
				onClick: () => (review.panels.split.value = true),
			},
			{
				label:
					props.proxyStatus === 'Error'
						? 'Retry streaming proxy'
						: 'Generate streaming proxy',
				icon: 'lucide-gauge',
				disabled: props.generatingProxy || props.proxyStatus === 'Processing',
				onClick: async () => {
					emit('generate-proxy')
				},
			},
		)
	}

	if (props.asset.project) {
		options.push({
			label: 'Open in project',
			icon: 'lucide-folder-open',
			onClick: async () => {
				await router.push(`/projects/${props.asset.project?.name}`)
			},
		})
	}
	return options
})

function goBack() {
	if (window.history.length > 1) router.back()
	else if (props.asset.project) void router.push(`/projects/${props.asset.project.name}`)
	else void router.push('/')
}

async function copyLink() {
	await navigator.clipboard.writeText(shareUrl.value)
	toast.success('Review link copied')
}
</script>
