// frontend/src/components/review/VideoPlayer.vue
<template>
	<div
		ref="container"
		class="flex w-full flex-col overflow-hidden rounded-lg bg-black md:h-full"
		data-testid="review-video-player"
	>
		<div
			ref="videoWrapper"
			class="relative flex min-h-0 flex-1 items-center justify-center bg-black"
		>
			<video
				ref="video"
				:src="view.data?.url"
				class="h-full w-full object-contain"
				playsinline
				@click="canvasActive ? undefined : player.togglePlay()"
			/>

			<div v-if="view.error" class="absolute inset-0 grid place-items-center p-6 text-center">
				<ErrorMessage message="This video could not be loaded." />
			</div>
			<div
				v-else-if="!view.data?.url || player.isBuffering.value"
				class="pointer-events-none absolute inset-0 grid place-items-center"
			>
				<LoadingIndicator class="text-ink-gray-3" />
			</div>

			<AnnotationCanvas
				:target="videoWrapper"
				:active="canvasActive"
				:read-only="review.annotation.mode.value === 'view'"
				:annotation-data="review.annotation.data.value"
			/>
		</div>

		<div class="shrink-0 border-t border-outline-gray-2 bg-surface-base">
			<VideoTimeline
				class="hidden md:block"
				:current-time="player.currentTime.value"
				:duration="player.duration.value"
				:comments="review.comments.list.value"
				@seek="player.seek"
				@comment="openComment"
			/>
			<VideoControls
				:is-playing="player.isPlaying.value"
				:current-time="player.currentTime.value"
				:duration="player.duration.value"
				:volume="player.volume.value"
				:is-muted="player.isMuted.value"
				:playback-rate="player.playbackRate.value"
				:is-looping="player.isLooping.value"
				:is-fullscreen="isFullscreen"
				@toggle-play="player.togglePlay"
				@toggle-mute="player.toggleMute"
				@volume-change="player.setVolume"
				@playback-rate-change="player.setPlaybackRate"
				@toggle-loop="player.toggleLoop"
				@toggle-fullscreen="toggle"
				@skip-backward="player.seek(player.currentTime.value - 10)"
				@skip-forward="player.seek(player.currentTime.value + 10)"
			/>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed, onMounted, onScopeDispose, ref, watch } from 'vue'
import { ErrorMessage, LoadingIndicator, useCall } from 'frappe-ui'
import type { AnnotationJson, ReviewComment, ViewUrlResponse } from '@/types'
import AnnotationCanvas from '@/components/review/AnnotationCanvas.vue'
import VideoControls from '@/components/review/VideoControls.vue'
import VideoTimeline from '@/components/review/VideoTimeline.vue'
import { useFullscreen } from '@/composables/useFullscreen'
import { useReview } from '@/composables/useReview'
import { useVideoPlayer } from '@/composables/useVideoPlayer'

const props = withDefaults(defineProps<{ assetName: string; preferProxy?: boolean }>(), {
	preferProxy: false,
})

const review = useReview()
const container = ref<HTMLElement | null>(null)
const videoWrapper = ref<HTMLElement | null>(null)
const video = ref<HTMLVideoElement | null>(null)
const player = useVideoPlayer(video)
const { isFullscreen, toggle } = useFullscreen(container, video)
const canvasActive = computed(() => review.annotation.mode.value !== 'off')

const view = useCall<ViewUrlResponse, { asset_name: string; token?: string }>({
	url: '/api/v2/method/vms.review_api.get_review_view_url',
	method: 'GET',
	params: {
		asset_name: props.assetName,
		...(review.token ? { token: review.token } : {}),
	},
	cacheKey: ['review-video-url', props.assetName, review.token ?? 'session'],
})

watch(
	video,
	(element) => {
		review.player.value = element
	},
	{ immediate: true },
)
watch(player.currentTime, (time) => {
	review.currentTime.value = time
})
watch(player.duration, (duration) => {
	review.duration.value = duration
})
watch(
	() => props.preferProxy,
	() => {
		void view.reload()
	},
)
watch(canvasActive, (active) => {
	if (active) video.value?.pause()
})

function openComment(comment: ReviewComment) {
	const time = comment.video_timestamp ?? 0
	if (!comment.annotation_data) {
		player.seek(time)
		return
	}
	try {
		review.annotation.view(JSON.parse(comment.annotation_data) as AnnotationJson, time)
	} catch {
		player.seek(time)
	}
}

function handleShortcut(event: KeyboardEvent) {
	const target = event.target as HTMLElement | null
	if (target?.matches('input, textarea, [contenteditable="true"]')) return
	const element = video.value
	if (!element) return

	const handled = [
		'Space',
		'KeyJ',
		'KeyK',
		'KeyL',
		'ArrowLeft',
		'ArrowRight',
		'KeyF',
		'KeyM',
	].includes(event.code)
	if (handled) event.preventDefault()

	if (event.code === 'Space' || event.code === 'KeyK') player.togglePlay()
	else if (event.code === 'KeyL') {
		player.setPlaybackRate(Math.min(8, element.playbackRate * 2))
		if (element.paused) void element.play()
	} else if (event.code === 'KeyJ') {
		element.pause()
		player.seek(player.currentTime.value - 1)
	} else if (event.code === 'ArrowLeft') {
		player.seek(player.currentTime.value - (event.shiftKey ? 10 / 30 : 1 / 30))
	} else if (event.code === 'ArrowRight') {
		player.seek(player.currentTime.value + (event.shiftKey ? 10 / 30 : 1 / 30))
	} else if (event.code === 'KeyF') toggle()
	else if (event.code === 'KeyM') player.toggleMute()
}

onMounted(() => document.addEventListener('keydown', handleShortcut))
onScopeDispose(() => document.removeEventListener('keydown', handleShortcut))
</script>

// frontend/src/components/review/VideoPlayer.tsx
import { useRef, useEffect, useState, useCallback } from "react"
import { useFrappePostCall } from "frappe-react-sdk"
import { useVideoPlayer } from "@/hooks/useVideoPlayer"
import { useFullscreen } from "@/hooks/useFullscreen"
import { useReviewContext } from "@/hooks/useReviewContext"
import { Spinner } from "@/components/ui/spinner"
import { VideoControls } from "./VideoControls"
import { VideoTimeline } from "./VideoTimeline"
import { AnnotationCanvas } from "./AnnotationCanvas"

interface VideoPlayerProps {
  assetName: string
}

export function VideoPlayer({ assetName }: VideoPlayerProps) {
  const {
    comments,
    setCurrentTime,
    seekToRef,
    annotationMode,
    replayAnnotation,
    fabricCanvas,
    viewAnnotation,
    token,
  } = useReviewContext()

  const videoRef = useRef<HTMLVideoElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)
  const videoWrapperRef = useRef<HTMLDivElement>(null)
  const [videoUrl, setVideoUrl] = useState<string | null>(null)

  const { call: getViewUrl } = useFrappePostCall("vms.review_api.get_review_view_url")

  const player = useVideoPlayer(videoRef)
  const { isFullscreen, toggle: toggleFullscreen } = useFullscreen(containerRef, videoRef)

  // Fetch video URL
  useEffect(() => {
    if (!assetName) return
    const params: Record<string, string> = { asset_name: assetName }
    if (token) params.token = token
    getViewUrl(params).then((res) => {
      setVideoUrl(res.message.url)
    })
  }, [assetName, token, getViewUrl])

  // Expose seek function to parent via context ref
  useEffect(() => {
    seekToRef.current = (time: number) => {
      player.seek(time)
      videoRef.current?.pause()
    }
  }, [seekToRef, player])

  // Notify context of time updates (drift-based replay dismissal handled in context)
  useEffect(() => {
    setCurrentTime(player.currentTime)
  }, [player.currentTime, setCurrentTime])

  // Pause video when annotation mode activates
  useEffect(() => {
    if (annotationMode || replayAnnotation) {
      videoRef.current?.pause()
    }
  }, [annotationMode, replayAnnotation])

  const SKIP_SECONDS = 10
  const FPS = 30

  const skipForward = useCallback(() => {
    player.seek(player.currentTime + SKIP_SECONDS)
  }, [player])

  const skipBackward = useCallback(() => {
    player.seek(player.currentTime - SKIP_SECONDS)
  }, [player])

  // JKL shuttle speeds: successive presses cycle through these
  const SHUTTLE_SPEEDS = [1, 2, 4, 8] as const
  const shuttleIndexRef = useRef(0)
  const shuttleDirRef = useRef<"fwd" | "rev" | null>(null)
  const rewindIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const playerRef = useRef(player)
  playerRef.current = player

  const clearRewind = useCallback(() => {
    if (rewindIntervalRef.current) {
      clearInterval(rewindIntervalRef.current)
      rewindIntervalRef.current = null
    }
  }, [])

  const startRewind = useCallback(
    (speed: number) => {
      clearRewind()
      const video = videoRef.current
      if (!video) return
      video.pause()
      // Seek backwards at `speed` x real-time, updating every 50ms
      rewindIntervalRef.current = setInterval(() => {
        const v = videoRef.current
        if (!v) return
        const step = speed * (50 / 1000)
        const next = v.currentTime - step
        if (next <= 0) {
          playerRef.current.seek(0)
          clearRewind()
          shuttleIndexRef.current = 0
          shuttleDirRef.current = null
        } else {
          playerRef.current.seek(next)
        }
      }, 50)
    },
    [clearRewind, videoRef],
  )

  // Clean up rewind interval on unmount
  useEffect(() => clearRewind, [clearRewind])

  // Keyboard shortcuts: JKL shuttle, Space, Arrow keys (frame/10-frame), M (mute), F (fullscreen)
  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      const tag = (e.target as HTMLElement)?.tagName
      if (tag === "INPUT" || tag === "TEXTAREA" || (e.target as HTMLElement)?.isContentEditable) return

      const video = videoRef.current
      if (!video) return

      switch (e.code) {
        case "Space":
          e.preventDefault()
          player.togglePlay()
          // Reset shuttle state on space
          clearRewind()
          shuttleIndexRef.current = 0
          shuttleDirRef.current = null
          break

        case "KeyK":
          e.preventDefault()
          // K always pauses and resets shuttle
          clearRewind()
          shuttleIndexRef.current = 0
          shuttleDirRef.current = null
          if (!video.paused) {
            video.pause()
          } else {
            video.play()
          }
          break

        case "KeyL": {
          e.preventDefault()
          clearRewind()
          if (shuttleDirRef.current === "fwd" && shuttleIndexRef.current < SHUTTLE_SPEEDS.length - 1) {
            shuttleIndexRef.current++
          } else if (shuttleDirRef.current !== "fwd") {
            shuttleIndexRef.current = 0
            shuttleDirRef.current = "fwd"
          }
          const speed = SHUTTLE_SPEEDS[shuttleIndexRef.current]
          video.playbackRate = speed
          if (video.paused) video.play()
          break
        }

        case "KeyJ": {
          e.preventDefault()
          // If currently playing forward, stop first
          if (!video.paused) video.pause()
          if (shuttleDirRef.current === "rev" && shuttleIndexRef.current < SHUTTLE_SPEEDS.length - 1) {
            shuttleIndexRef.current++
          } else if (shuttleDirRef.current !== "rev") {
            shuttleIndexRef.current = 0
            shuttleDirRef.current = "rev"
          }
          const speed = SHUTTLE_SPEEDS[shuttleIndexRef.current]
          startRewind(speed)
          break
        }

        case "ArrowLeft":
          e.preventDefault()
          clearRewind()
          shuttleIndexRef.current = 0
          shuttleDirRef.current = null
          if (e.shiftKey) {
            // Skip 10 frames
            player.seek(player.currentTime - 10 / FPS)
          } else {
            // Skip 1 frame
            player.seek(player.currentTime - 1 / FPS)
          }
          if (!video.paused) video.pause()
          break

        case "ArrowRight":
          e.preventDefault()
          clearRewind()
          shuttleIndexRef.current = 0
          shuttleDirRef.current = null
          if (e.shiftKey) {
            // Skip 10 frames
            player.seek(player.currentTime + 10 / FPS)
          } else {
            // Skip 1 frame
            player.seek(player.currentTime + 1 / FPS)
          }
          if (!video.paused) video.pause()
          break

        case "KeyM":
          e.preventDefault()
          player.toggleMute()
          break

        case "KeyF":
          e.preventDefault()
          toggleFullscreen()
          break
      }
    }
    document.addEventListener("keydown", onKeyDown)
    return () => document.removeEventListener("keydown", onKeyDown)
  }, [player, clearRewind, startRewind, toggleFullscreen, videoRef])

  const isCanvasActive = annotationMode || !!replayAnnotation

  return (
    <div ref={containerRef} className="flex flex-col overflow-hidden rounded-lg border bg-black md:h-full">
      <div ref={videoWrapperRef} className="relative flex items-center justify-center bg-black aspect-video md:aspect-auto md:min-h-0 md:flex-1">
        <video
          ref={videoRef}
          src={videoUrl ?? undefined}
          className="h-full w-full object-contain"
          onClick={isCanvasActive ? undefined : player.togglePlay}
          playsInline
        />
        {!videoUrl && (
          <div className="absolute inset-0 flex items-center justify-center text-muted-foreground text-sm">
            Loading video...
          </div>
        )}
        {videoUrl && player.isBuffering && (
          <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
            <Spinner className="size-10 text-white/80" />
          </div>
        )}
        <AnnotationCanvas
          videoContainerRef={videoWrapperRef}
          isActive={isCanvasActive}
          readOnly={!!replayAnnotation}
          annotationData={replayAnnotation}
        />
      </div>

      <div className="bg-card border-t">
        <VideoTimeline
          currentTime={player.currentTime}
          duration={player.duration}
          comments={comments}
          onSeek={player.seek}
          onCommentMarkerClick={viewAnnotation}
          tooltipContainer={isFullscreen ? containerRef.current : undefined}
        />
        <VideoControls
          isPlaying={player.isPlaying}
          currentTime={player.currentTime}
          duration={player.duration}
          volume={player.volume}
          isMuted={player.isMuted}
          playbackRate={player.playbackRate}
          isLooping={player.isLooping}
          onTogglePlay={player.togglePlay}
          onToggleMute={player.toggleMute}
          onVolumeChange={player.setVolume}
          onPlaybackRateChange={player.setPlaybackRate}
          onToggleLoop={player.toggleLoop}
          isFullscreen={isFullscreen}
          onToggleFullscreen={toggleFullscreen}
          onSkipBackward={skipBackward}
          onSkipForward={skipForward}
          popoverContainer={isFullscreen ? containerRef.current : undefined}
        />
      </div>
    </div>
  )
}
