// frontend/src/components/review/VideoControls.tsx
import { Button, buttonVariants } from "@/components/ui/button"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover"
import { cn } from "@/lib/utils"
import { formatTimecode } from "@/hooks/useVideoPlayer"
import { Maximize, Minimize, Pause, Play, Repeat, RotateCcw, RotateCw, Volume1, Volume2, VolumeX } from "lucide-react"

const SPEED_OPTIONS = [0.5, 1, 1.5, 2]

interface VideoControlsProps {
  isPlaying: boolean
  currentTime: number
  duration: number
  volume: number
  isMuted: boolean
  playbackRate: number
  isLooping: boolean
  onTogglePlay: () => void
  onToggleMute: () => void
  onVolumeChange: (vol: number) => void
  onPlaybackRateChange: (rate: number) => void
  onToggleLoop: () => void
  isFullscreen: boolean
  onToggleFullscreen: () => void
  onSkipBackward: () => void
  onSkipForward: () => void
  popoverContainer?: HTMLElement | null
}

export function VideoControls({
  isPlaying,
  currentTime,
  duration,
  volume,
  isMuted,
  playbackRate,
  isLooping,
  onTogglePlay,
  onToggleMute,
  onVolumeChange,
  onPlaybackRateChange,
  onToggleLoop,
  isFullscreen,
  onToggleFullscreen,
  onSkipBackward,
  onSkipForward,
  popoverContainer,
}: VideoControlsProps) {
  const VolumeIcon = isMuted || volume === 0
    ? VolumeX
    : volume < 0.5
      ? Volume1
      : Volume2

  return (
    <div className="flex items-center gap-1 px-2 py-1.5">
      <Button variant="ghost" size="icon-sm" onClick={onSkipBackward} title="Skip back 10s (←)">
        <RotateCcw size={18} />
      </Button>
      <Button variant="ghost" size="icon-sm" onClick={onTogglePlay}>
        {isPlaying ? <Pause size={18} /> : <Play size={18} />}
      </Button>
      <Button variant="ghost" size="icon-sm" onClick={onSkipForward} title="Skip forward 10s (→)">
        <RotateCw size={18} />
      </Button>

      <div className="hidden items-center gap-1 md:flex">
        <Button variant="ghost" size="icon-sm" onClick={onToggleMute}>
          <VolumeIcon size={18} />
        </Button>
        <input
          type="range"
          min={0}
          max={100}
          value={isMuted ? 0 : Math.round(volume * 100)}
          onChange={(e) => onVolumeChange(Number(e.target.value) / 100)}
          className="w-20 h-1.5 appearance-none rounded-full bg-white/20 cursor-pointer accent-primary [&::-webkit-slider-thumb]:appearance-none [&::-webkit-slider-thumb]:size-3 [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-white [&::-webkit-slider-thumb]:shadow-sm"
        />
      </div>

      <div className="mx-1 font-mono text-[10px] text-muted-foreground select-none md:text-xs">
        {formatTimecode(currentTime)} / {formatTimecode(duration)}
      </div>

      <div className="ml-auto flex items-center gap-1">
        <Popover>
          <PopoverTrigger
            className={cn(
              buttonVariants({ variant: "ghost", size: "sm" }),
              "hidden font-mono text-xs md:inline-flex cursor-pointer"
            )}
          >
            {playbackRate}x
          </PopoverTrigger>
          <PopoverContent className="w-auto min-w-0 p-1" align="end" container={popoverContainer}>
            <div className="flex flex-col">
              {SPEED_OPTIONS.map((rate) => (
                <Button
                  key={rate}
                  variant={playbackRate === rate ? "secondary" : "ghost"}
                  size="sm"
                  className="justify-start font-mono text-xs"
                  onClick={() => onPlaybackRateChange(rate)}
                >
                  {rate}x
                </Button>
              ))}
            </div>
          </PopoverContent>
        </Popover>

        <Button
          variant="ghost"
          size="icon-sm"
          onClick={onToggleLoop}
          className={`hidden md:inline-flex ${isLooping ? "text-primary" : "text-muted-foreground"}`}
        >
          <Repeat size={18} />
        </Button>

        <Button variant="ghost" size="icon-sm" onClick={onToggleFullscreen}>
          {isFullscreen ? <Minimize size={18} /> : <Maximize size={18} />}
        </Button>
      </div>
    </div>
  )
}

// frontend/src/components/review/VideoControls.vue
<template>
	<div class="flex items-center gap-1 px-2 py-1.5 text-ink-gray-7">
		<Button
			variant="ghost"
			icon="lucide-rotate-ccw"
			aria-label="Skip back 10 seconds"
			@click="$emit('skip-backward')"
		/>
		<Button
			variant="ghost"
			:icon="isPlaying ? 'lucide-pause' : 'lucide-play'"
			:aria-label="isPlaying ? 'Pause' : 'Play'"
			@click="$emit('toggle-play')"
		/>
		<Button
			variant="ghost"
			icon="lucide-rotate-cw"
			aria-label="Skip forward 10 seconds"
			@click="$emit('skip-forward')"
		/>

		<div class="hidden items-center gap-2 md:flex">
			<Button
				variant="ghost"
				:icon="volumeIcon"
				:aria-label="isMuted ? 'Unmute' : 'Mute'"
				@click="$emit('toggle-mute')"
			/>
			<Slider
				v-model="volumeModel"
				bare
				:min="0"
				:max="100"
				:step="1"
				class="w-20"
				aria-label="Volume"
			/>
		</div>

		<span class="mx-1 select-none font-mono text-xs text-ink-gray-5">
			{{ formatTimecode(currentTime) }} / {{ formatTimecode(duration) }}
		</span>

		<div class="ml-auto flex items-center gap-1">
			<Dropdown :options="speedOptions">
				<Button
					variant="ghost"
					:label="`${playbackRate}x`"
					class="hidden font-mono md:inline-flex"
				/>
			</Dropdown>
			<Button
				variant="ghost"
				icon="lucide-repeat"
				aria-label="Toggle loop"
				:class="isLooping ? 'text-ink-gray-9' : 'text-ink-gray-5'"
				class="hidden md:inline-flex"
				@click="$emit('toggle-loop')"
			/>
			<Button
				variant="ghost"
				:icon="isFullscreen ? 'lucide-minimize' : 'lucide-maximize'"
				:aria-label="isFullscreen ? 'Exit fullscreen' : 'Enter fullscreen'"
				@click="$emit('toggle-fullscreen')"
			/>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { Button, Dropdown, Slider } from 'frappe-ui'
import { formatTimecode } from '@/composables/useVideoPlayer'

const props = defineProps<{
	isPlaying: boolean
	currentTime: number
	duration: number
	volume: number
	isMuted: boolean
	playbackRate: number
	isLooping: boolean
	isFullscreen: boolean
}>()

const emit = defineEmits<{
	'toggle-play': []
	'toggle-mute': []
	'volume-change': [volume: number]
	'playback-rate-change': [rate: number]
	'toggle-loop': []
	'toggle-fullscreen': []
	'skip-backward': []
	'skip-forward': []
}>()

const volumeModel = computed<number[]>({
	get: () => [props.isMuted ? 0 : Math.round(props.volume * 100)],
	set: ([value]) => emit('volume-change', (value ?? 0) / 100),
})

const volumeIcon = computed(() => {
	if (props.isMuted || props.volume === 0) return 'lucide-volume-x'
	return props.volume < 0.5 ? 'lucide-volume-1' : 'lucide-volume-2'
})

const speedOptions = [0.5, 1, 1.5, 2].map((rate) => ({
	label: `${rate}x`,
	icon: rate === props.playbackRate ? 'lucide-check' : undefined,
	onClick: () => emit('playback-rate-change', rate),
}))
</script>
