// frontend-react/src/components/review/VideoTimeline.tsx
import { useCallback, useRef } from "react"
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import { formatTimestamp } from "@/hooks/useVideoPlayer"
import type { VMSReviewComment } from "@/types"

interface VideoTimelineProps {
  currentTime: number
  duration: number
  comments: VMSReviewComment[]
  onSeek: (time: number) => void
  onCommentMarkerClick?: (commentName: string, timestamp?: number | null) => void
  tooltipContainer?: HTMLElement | null
}

export function VideoTimeline({
  currentTime,
  duration,
  comments,
  onSeek,
  onCommentMarkerClick,
  tooltipContainer,
}: VideoTimelineProps) {
  const trackRef = useRef<HTMLDivElement>(null)

  const getTimeFromEvent = useCallback(
    (e: React.MouseEvent) => {
      const track = trackRef.current
      if (!track || !duration) return 0
      const rect = track.getBoundingClientRect()
      const ratio = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width))
      return ratio * duration
    },
    [duration],
  )

  const handleClick = useCallback(
    (e: React.MouseEvent) => {
      onSeek(getTimeFromEvent(e))
    },
    [getTimeFromEvent, onSeek],
  )

  const progress = duration > 0 ? (currentTime / duration) * 100 : 0

  // Only show markers for comments with timestamps
  const commentMarkers = comments.filter(
    (c) => c.video_timestamp != null && !c.parent_comment,
  )

  return (
    <div className="px-2 py-1">
      <div className="relative">
        {/* Track */}
        <div
          ref={trackRef}
          className="relative h-2 cursor-pointer rounded-full bg-muted"
          onClick={handleClick}
        >
          {/* Progress bar */}
          <div
            className="absolute inset-y-0 left-0 rounded-full bg-primary"
            style={{ width: `${progress}%` }}
          />

          {/* Playhead */}
          <div
            className="absolute top-1/2 -translate-x-1/2 -translate-y-1/2 size-3 rounded-full bg-primary shadow-sm"
            style={{ left: `${progress}%` }}
          />
        </div>

        {/* Comment markers — rendered as an overlay so tooltip anchors correctly */}
        {commentMarkers.map((comment) => {
          const pos = duration > 0 ? ((comment.video_timestamp! / duration) * 100) : 0
          return (
            <Tooltip key={comment.name}>
              <TooltipTrigger
                className="absolute top-1/2 -translate-x-1/2 -translate-y-1/2 size-2.5 rounded-full bg-amber-400 border border-amber-500 hover:scale-150 transition-transform cursor-pointer z-10 p-0 appearance-none outline-none"
                style={{ left: `${pos}%` }}
                onClick={(e) => {
                  e.stopPropagation()
                  if (onCommentMarkerClick) {
                    onCommentMarkerClick(comment.name, comment.video_timestamp)
                  } else {
                    onSeek(comment.video_timestamp!)
                  }
                }}
              />
              <TooltipContent side="top" sideOffset={8} container={tooltipContainer}>
                <span className="font-mono text-xs">
                  {formatTimestamp(comment.video_timestamp!)}
                </span>
                {" — "}
                <span className="text-xs">
                  {(() => {
                    const text = comment.comment_text.replace(/<[^>]*>/g, "")
                    return text.length > 40 ? text.slice(0, 40) + "..." : text
                  })()}
                </span>
              </TooltipContent>
            </Tooltip>
          )
        })}
      </div>
    </div>
  )
}

// frontend/src/components/review/VideoTimeline.vue
<template>
	<div class="px-3 py-2">
		<div
			ref="track"
			class="relative h-2 cursor-pointer rounded-full bg-surface-gray-3"
			role="slider"
			tabindex="0"
			aria-label="Video position"
			:aria-valuemin="0"
			:aria-valuemax="Math.round(duration)"
			:aria-valuenow="Math.round(currentTime)"
			@click="seekFromPointer"
			@keydown.left.prevent="$emit('seek', Math.max(0, currentTime - 1))"
			@keydown.right.prevent="$emit('seek', Math.min(duration, currentTime + 1))"
		>
			<div
				class="absolute inset-y-0 left-0 rounded-full bg-surface-gray-7"
				:style="progressStyle"
			/>
			<span
				class="absolute top-1/2 size-3 -translate-x-1/2 -translate-y-1/2 rounded-full bg-surface-gray-9 shadow-sm"
				:style="progressLeft"
			/>

			<Tooltip v-for="comment in markers" :key="comment.name" :text="markerLabel(comment)">
				<button
					type="button"
					class="absolute top-1/2 z-10 size-2.5 -translate-x-1/2 -translate-y-1/2 rounded-full border border-outline-amber-5 bg-surface-amber-6 transition-transform hover:scale-150"
					:style="{ left: `${markerPosition(comment.video_timestamp ?? 0)}%` }"
					:aria-label="markerLabel(comment)"
					@click.stop="$emit('comment', comment)"
				/>
			</Tooltip>
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { Tooltip } from 'frappe-ui'
import type { ReviewComment } from '@/types'
import { formatTimestamp } from '@/composables/useVideoPlayer'

const props = defineProps<{
	currentTime: number
	duration: number
	comments: ReviewComment[]
}>()

const emit = defineEmits<{
	seek: [time: number]
	comment: [comment: ReviewComment]
}>()

const track = ref<HTMLElement | null>(null)
const progress = computed(() =>
	props.duration > 0 ? (props.currentTime / props.duration) * 100 : 0,
)
const progressStyle = computed(() => ({ width: `${progress.value}%` }))
const progressLeft = computed(() => ({ left: `${progress.value}%` }))
const markers = computed(() =>
	props.comments.filter((comment) => comment.video_timestamp != null && !comment.parent_comment),
)

function seekFromPointer(event: MouseEvent) {
	if (!track.value || !props.duration) return
	const bounds = track.value.getBoundingClientRect()
	const ratio = Math.max(0, Math.min(1, (event.clientX - bounds.left) / bounds.width))
	emit('seek', ratio * props.duration)
}

function markerPosition(time: number) {
	return props.duration > 0 ? Math.min(100, Math.max(0, (time / props.duration) * 100)) : 0
}

function markerLabel(comment: ReviewComment) {
	const text = comment.comment_text.replace(/<[^>]*>/g, '').trim()
	const summary = text.length > 40 ? `${text.slice(0, 40)}…` : text
	return `${formatTimestamp(comment.video_timestamp ?? 0)} — ${summary}`
}
</script>
