// frontend-react/src/pages/AuditLogPage.tsx
import { useState } from "react"
import { useFrappeGetCall } from "frappe-react-sdk"
import { format } from "date-fns"
import {
  flexRender,
  getCoreRowModel,
  getSortedRowModel,
  useReactTable,
  type ColumnDef,
  type SortingState,
} from "@tanstack/react-table"
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/components/ui/empty"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/components/ui/command"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"
import { UserAvatar } from "@/components/UserAvatar"
import { Skeleton } from "@/components/ui/skeleton"
import { formatBytes } from "@/lib/utils"
import type { VMSAuditLog } from "@/types"
import type { DateRange } from "react-day-picker"
import { ArrowUpDown, Calendar as CalendarIcon, Check, ChevronDown, ChevronUp, ClipboardList, Search, X } from "lucide-react"

const columns: ColumnDef<VMSAuditLog>[] = [
  {
    accessorKey: "action",
    header: "Action",
    cell: ({ row }) => {
      const action = row.getValue<string>("action")
      return (
        <Badge
          variant={
            action === "Delete"
              ? "destructive"
              : action === "Rename"
                ? "outline"
                : "secondary"
          }
        >
          {action}
        </Badge>
      )
    },
    enableSorting: false,
  },
  {
    accessorKey: "file_name",
    header: ({ column }) => (
      <SortableHeader column={column} label="File Name" />
    ),
    cell: ({ row }) => (
      <span className="max-w-[200px] truncate font-medium block">
        {row.original.file_name || row.original.asset_name}
      </span>
    ),
  },
  {
    accessorKey: "project_name",
    header: "Project",
    cell: ({ row }) => (
      <span className="text-muted-foreground">
        {row.original.project_name || "—"}
      </span>
    ),
    enableSorting: false,
  },
  {
    accessorKey: "user_full_name",
    header: "User",
    cell: ({ row }) => (
      <div className="flex items-center gap-2">
        <UserAvatar
          name={row.original.user_full_name}
          image={row.original.user_image}
        />
        <span className="text-sm">{row.original.user_full_name}</span>
      </div>
    ),
    enableSorting: false,
  },
  {
    accessorKey: "timestamp",
    header: ({ column }) => (
      <SortableHeader column={column} label="Timestamp" />
    ),
    cell: ({ row }) => (
      <span className="text-muted-foreground">
        {formatTimestamp(row.getValue("timestamp"))}
      </span>
    ),
  },
  {
    accessorKey: "file_size",
    header: ({ column }) => (
      <SortableHeader column={column} label="Size" className="justify-end" />
    ),
    cell: ({ row }) => {
      const size = row.getValue<number | undefined>("file_size")
      return (
        <span className="text-right text-muted-foreground block">
          {size ? formatBytes(size) : "—"}
        </span>
      )
    },
  },
]

function SortableHeader({
  column,
  label,
  className = "",
}: {
  column: { toggleSorting: (desc?: boolean) => void; getIsSorted: () => false | "asc" | "desc" }
  label: string
  className?: string
}) {
  const sorted = column.getIsSorted()
  return (
    <Button
      variant="ghost"
      size="sm"
      className={`-ml-3 h-8 ${className}`}
      onClick={() => column.toggleSorting(sorted === "asc")}
    >
      {label}
      {sorted === "asc" ? (
        <ChevronUp className="ml-1 size-3.5" />
      ) : sorted === "desc" ? (
        <ChevronDown className="ml-1 size-3.5" />
      ) : (
        <ArrowUpDown className="ml-1 size-3.5" />
      )}
    </Button>
  )
}

function formatTimestamp(ts: string) {
  const d = new Date(ts)
  return d.toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  })
}

export function AuditLogPage() {
  const [action, setAction] = useState<string>("")
  const [user, setUser] = useState<string>("")
  const [project, setProject] = useState<string>("")
  const [projectOpen, setProjectOpen] = useState(false)
  const [search, setSearch] = useState("")
  const [dateRange, setDateRange] = useState<DateRange | undefined>()
  const [page, setPage] = useState(1)
  const [sorting, setSorting] = useState<SortingState>([])
  const pageSize = 20

  const { data: filterData } = useFrappeGetCall<{
    message: {
      users: { value: string; label: string }[]
      projects: { value: string; label: string }[]
    }
  }>("vms.api.get_audit_log_filters")

  const { data, isLoading } = useFrappeGetCall<{
    message: {
      logs: VMSAuditLog[]
      total: number
      page: number
      page_size: number
      total_pages: number
    }
  }>("vms.api.get_audit_logs", {
    action: action && action !== "all" ? action : undefined,
    user: user && user !== "all" ? user : undefined,
    project: project && project !== "all" ? project : undefined,
    search: search || undefined,
    from_date: dateRange?.from
      ? format(dateRange.from, "yyyy-MM-dd")
      : undefined,
    to_date: dateRange?.to ? format(dateRange.to, "yyyy-MM-dd") : undefined,
    page,
    page_size: pageSize,
  })

  const logs = data?.message?.logs ?? []
  const total = data?.message?.total ?? 0
  const totalPages = data?.message?.total_pages ?? 1
  const users = filterData?.message?.users ?? []
  const projects = filterData?.message?.projects ?? []

  const hasActiveFilters =
    (action && action !== "all") ||
    (user && user !== "all") ||
    (project && project !== "all") ||
    search ||
    dateRange?.from

  const table = useReactTable({
    data: logs,
    columns,
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    onSortingChange: setSorting,
    state: { sorting },
    manualPagination: true,
    pageCount: totalPages,
  })

  function clearFilters() {
    setAction("")
    setUser("")
    setProject("")
    setSearch("")
    setDateRange(undefined)
    setPage(1)
  }

  return (
    <div className="flex flex-1 flex-col gap-6 p-4 md:p-6">
      <div>
        <h1 className="text-2xl font-bold">Audit Logs</h1>
        <p className="text-sm text-muted-foreground">
          Track asset downloads, deletions, and renames
        </p>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="relative">
          <Search className="absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search file name..."
            value={search}
            onChange={(e) => {
              setSearch(e.target.value)
              setPage(1)
            }}
            className="w-56 pl-9"
          />
        </div>
        <Select
          value={action}
          onValueChange={(v) => {
            setAction(v)
            setPage(1)
          }}
        >
          <SelectTrigger className="w-36">
            <SelectValue placeholder="All actions" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All actions</SelectItem>
            <SelectItem value="Download">Download</SelectItem>
            <SelectItem value="Delete">Delete</SelectItem>
            <SelectItem value="Rename">Rename</SelectItem>
          </SelectContent>
        </Select>
        <Select
          value={user}
          onValueChange={(v) => {
            setUser(v)
            setPage(1)
          }}
        >
          <SelectTrigger className="w-44">
            <SelectValue placeholder="All users" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All users</SelectItem>
            {users.map((u) => (
              <SelectItem key={u.value} value={u.value}>
                {u.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Popover open={projectOpen} onOpenChange={setProjectOpen}>
          <PopoverTrigger
            render={<Button variant="outline" role="combobox" aria-expanded={projectOpen} />}
            className="w-44 justify-between font-normal"
          >
            <span className="truncate">
              {project && project !== "all"
                ? projects.find((p) => p.value === project)?.label ?? project
                : "All projects"}
            </span>
            <ChevronDown className="ml-auto size-4 shrink-0 opacity-50" />
          </PopoverTrigger>
          <PopoverContent className="w-44 p-0" align="start">
            <Command>
              <CommandInput placeholder="Search project..." />
              <CommandList>
                <CommandEmpty>No project found.</CommandEmpty>
                <CommandGroup>
                  {projects.map((p) => (
                    <CommandItem
                      key={p.value}
                      value={p.label}
                      onSelect={() => {
                        setProject(project === p.value ? "" : p.value)
                        setProjectOpen(false)
                        setPage(1)
                      }}
                      data-checked={project === p.value}
                    >
                      <Check className={`size-4 ${project === p.value ? "opacity-100" : "opacity-0"}`} />
                      {p.label}
                    </CommandItem>
                  ))}
                </CommandGroup>
              </CommandList>
            </Command>
          </PopoverContent>
        </Popover>
        <DateRangePicker value={dateRange} onChange={(range) => { setDateRange(range); setPage(1) }} />
        {hasActiveFilters && (
          <Button variant="ghost" size="sm" onClick={clearFilters}>
            <X className="mr-1 size-3.5" />
            Clear
          </Button>
        )}
        <span className="ml-auto text-sm text-muted-foreground">
          {total} {total === 1 ? "entry" : "entries"}
        </span>
      </div>

      {/* Table */}
      <div className="rounded-md border">
        <Table>
          <TableHeader>
            {table.getHeaderGroups().map((headerGroup) => (
              <TableRow key={headerGroup.id}>
                {headerGroup.headers.map((header) => (
                  <TableHead key={header.id}>
                    {header.isPlaceholder
                      ? null
                      : flexRender(
                          header.column.columnDef.header,
                          header.getContext(),
                        )}
                  </TableHead>
                ))}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {isLoading ? (
              Array.from({ length: 5 }).map((_, i) => (
                <TableRow key={i}>
                  <TableCell>
                    <Skeleton className="h-5 w-16 rounded-full" />
                  </TableCell>
                  <TableCell>
                    <Skeleton className="h-4 w-32" />
                  </TableCell>
                  <TableCell>
                    <Skeleton className="h-4 w-20" />
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <Skeleton className="size-6 rounded-full" />
                      <Skeleton className="h-4 w-24" />
                    </div>
                  </TableCell>
                  <TableCell>
                    <Skeleton className="h-4 w-28" />
                  </TableCell>
                  <TableCell className="text-right">
                    <Skeleton className="ml-auto h-4 w-16" />
                  </TableCell>
                </TableRow>
              ))
            ) : table.getRowModel().rows.length === 0 ? (
              <TableRow>
                <TableCell colSpan={columns.length} className="p-0">
                  <Empty className="border-0">
                    <EmptyHeader>
                      <EmptyMedia variant="icon">
                        <ClipboardList strokeWidth={1.5} />
                      </EmptyMedia>
                      <EmptyTitle>No audit logs found</EmptyTitle>
                      <EmptyDescription>
                        {hasActiveFilters
                          ? "Try adjusting your filters."
                          : "Activity will appear here as assets are downloaded, deleted, or renamed."}
                      </EmptyDescription>
                    </EmptyHeader>
                  </Empty>
                </TableCell>
              </TableRow>
            ) : (
              table.getRowModel().rows.map((row) => (
                <TableRow key={row.id}>
                  {row.getVisibleCells().map((cell) => (
                    <TableCell key={cell.id}>
                      {flexRender(
                        cell.column.columnDef.cell,
                        cell.getContext(),
                      )}
                    </TableCell>
                  ))}
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-end gap-2">
          <Button
            variant="outline"
            size="sm"
            disabled={page <= 1}
            onClick={() => setPage((p) => p - 1)}
          >
            Previous
          </Button>
          <span className="text-sm text-muted-foreground">
            Page {page} of {totalPages}
          </span>
          <Button
            variant="outline"
            size="sm"
            disabled={page >= totalPages}
            onClick={() => setPage((p) => p + 1)}
          >
            Next
          </Button>
        </div>
      )}
    </div>
  )
}

function DateRangePicker({
  value,
  onChange,
}: {
  value: DateRange | undefined
  onChange: (range: DateRange | undefined) => void
}) {
  const [open, setOpen] = useState(false)

  const label = value?.from
    ? value.to
      ? `${format(value.from, "MMM d, yyyy")} – ${format(value.to, "MMM d, yyyy")}`
      : format(value.from, "MMM d, yyyy")
    : "Date range"

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger
        className="inline-flex h-9 items-center gap-2 rounded-md border border-input bg-background px-3 text-sm text-muted-foreground hover:bg-accent hover:text-accent-foreground"
      >
        <CalendarIcon className="size-4" />
        <span>{label}</span>
      </PopoverTrigger>
      <PopoverContent className="w-auto p-0" align="start">
        <Calendar
          mode="range"
          selected={value}
          onSelect={(range) => {
            onChange(range)
            if (range?.from && range?.to) {
              setOpen(false)
            }
          }}
          numberOfMonths={2}
        />
      </PopoverContent>
    </Popover>
  )
}

// frontend/src/pages/AuditLogPage.vue
<template>
	<PageHeader>
		<PageHeaderTitle>
			<h1 class="truncate">Audit log</h1>
		</PageHeaderTitle>
	</PageHeader>

	<div class="space-y-4 px-3 py-5 pb-10 sm:px-5" data-testid="audit-log">
		<div class="flex flex-wrap items-center gap-2">
			<TextInput v-model="search" placeholder="Search file name" class="w-56">
				<template #prefix><span class="lucide-search size-4" aria-hidden="true" /></template>
			</TextInput>
			<Select v-model="action" :options="actionOptions" placeholder="All actions" class="w-36" />
			<Select v-model="user" :options="userOptions" placeholder="All users" class="w-44" />
			<Select v-model="project" :options="projectOptions" placeholder="All projects" class="w-44" />
			<DateRangePicker v-model="dateRange" placeholder="Any date" />
			<Button v-if="hasFilters" variant="ghost" label="Clear" icon-left="lucide-x" @click="clearFilters" />
			<span class="ml-auto text-sm text-ink-gray-5">{{ total }} entries</span>
		</div>

		<LoadingText v-if="logs.loading && !rows.length" :lines="5" />
		<ErrorMessage v-else-if="logs.error" :message="logs.error" />
		<EmptyState
			v-else-if="!rows.length"
			icon="lucide-clipboard-list"
			title="No audit entries"
			description="Downloads, deletions, restores, and renames will appear here."
		/>
		<List v-else :columns="COLUMNS" class="-mx-3 list-row-px-3" data-testid="audit-list">
			<ListHeader>
				<ListHeaderCell>Action</ListHeaderCell>
				<ListHeaderCellSort
					label="File name"
					:direction="sortDirection('file_name')"
					@click="toggleSort('file_name')"
				/>
				<ListHeaderCell>Project</ListHeaderCell>
				<ListHeaderCell>User</ListHeaderCell>
				<ListHeaderCellSort
					label="Time"
					:direction="sortDirection('timestamp')"
					@click="toggleSort('timestamp')"
				/>
				<ListHeaderCellSort
					label="Size"
					class="justify-end"
					:direction="sortDirection('file_size')"
					@click="toggleSort('file_size')"
				/>
			</ListHeader>
			<ListRows v-slot="{ item, value }" :items="sortedRows">
				<ListRow :value="value" class="h-12" data-testid="audit-row">
					<ListCell><Badge :label="item.action" :theme="actionTheme(item.action)" /></ListCell>
					<ListCell><span class="truncate text-base-medium text-ink-gray-8">{{ item.file_name || item.asset_name }}</span></ListCell>
					<ListCell><span class="truncate text-sm text-ink-gray-6">{{ item.project_name || '—' }}</span></ListCell>
					<ListCell>
						<div class="flex min-w-0 items-center gap-2">
							<UserAvatar :user="{ full_name: item.user_full_name, user_image: item.user_image }" />
							<span class="truncate text-sm text-ink-gray-7">{{ item.user_full_name }}</span>
						</div>
					</ListCell>
					<ListCell><span class="text-sm text-ink-gray-5">{{ formatDateTime(item.timestamp) }}</span></ListCell>
					<ListCell class="justify-end"><span class="text-sm tabular-nums text-ink-gray-6">{{ item.file_size ? formatBytes(item.file_size) : '—' }}</span></ListCell>
				</ListRow>
			</ListRows>
		</List>

		<div v-if="rows.length < total" class="flex justify-center">
			<Button label="Load more" :loading="logs.loading" @click="limit += PAGE_SIZE" />
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import {
	Badge,
	Button,
	DateRangePicker,
	ErrorMessage,
	LoadingText,
	PageHeader,
	PageHeaderTitle,
	Select,
	TextInput,
	useCall,
	usePageMeta,
} from 'frappe-ui'
import {
	List,
	ListCell,
	ListHeader,
	ListHeaderCell,
	ListHeaderCellSort,
	ListRow,
	ListRows,
} from 'frappe-ui/list'
import type { AuditAction, AuditLog } from '@/types'
import { formatDateTime } from '@/lib/dates'
import { formatBytes } from '@/lib/format'
import EmptyState from '@/components/common/EmptyState.vue'
import UserAvatar from '@/components/common/UserAvatar.vue'

usePageMeta(() => ({ title: 'Audit log · VMS' }))

const PAGE_SIZE = 20
const COLUMNS = ['7rem', 'minmax(10rem,1fr)', '10rem', '11rem', '11rem', '6rem']
const action = ref('')
const user = ref('')
const project = ref('')
const search = ref('')
const dateRange = ref<string[]>([])
const limit = ref(PAGE_SIZE)
const sort = ref<{ field: 'file_name' | 'timestamp' | 'file_size'; direction: 'asc' | 'desc' }>({
	field: 'timestamp',
	direction: 'desc',
})

interface AuditResponse {
	logs: AuditLog[]
	total: number
}
interface AuditParams {
	action?: string
	user?: string
	project?: string
	search?: string
	from_date?: string
	to_date?: string
	page: number
	page_size: number
}
interface FilterResponse {
	users: { value: string; label: string }[]
	projects: { value: string; label: string }[]
}

const filters = useCall<FilterResponse>({
	url: '/api/v2/method/vms.api.get_audit_log_filters',
	method: 'GET',
	cacheKey: 'audit-log-filters',
})
const logs = useCall<AuditResponse, AuditParams>({
	url: '/api/v2/method/vms.api.get_audit_logs',
	method: 'GET',
	params: () => ({
		action: action.value || undefined,
		user: user.value || undefined,
		project: project.value || undefined,
		search: search.value || undefined,
		from_date: dateRange.value[0] || undefined,
		to_date: dateRange.value[1] || undefined,
		page: 1,
		page_size: limit.value,
	}),
	refetch: true,
	cacheKey: ['audit-logs', action, user, project, search, dateRange, limit],
})

const rows = computed(() => logs.data?.logs ?? [])
const total = computed(() => logs.data?.total ?? 0)
const actionOptions = [
	{ label: 'All actions', value: '' },
	...['Download', 'Delete', 'Permanent Delete', 'Rename', 'Restore'].map((value) => ({ label: value, value })),
]
const userOptions = computed(() => [{ label: 'All users', value: '' }, ...(filters.data?.users ?? [])])
const projectOptions = computed(() => [{ label: 'All projects', value: '' }, ...(filters.data?.projects ?? [])])
const hasFilters = computed(() => Boolean(action.value || user.value || project.value || search.value || dateRange.value.length))
const sortedRows = computed(() => [...rows.value].sort(compareRows))

function compareRows(a: AuditLog, b: AuditLog) {
	const left = a[sort.value.field] ?? ''
	const right = b[sort.value.field] ?? ''
	const order = typeof left === 'number' && typeof right === 'number' ? left - right : String(left).localeCompare(String(right))
	return sort.value.direction === 'asc' ? order : -order
}

function toggleSort(field: typeof sort.value.field) {
	if (sort.value.field === field) sort.value.direction = sort.value.direction === 'asc' ? 'desc' : 'asc'
	else sort.value = { field, direction: 'asc' }
}

function sortDirection(field: typeof sort.value.field) {
	return sort.value.field === field ? sort.value.direction : undefined
}

function clearFilters() {
	action.value = ''
	user.value = ''
	project.value = ''
	search.value = ''
	dateRange.value = []
	limit.value = PAGE_SIZE
}

function actionTheme(value: AuditAction) {
	if (value === 'Delete' || value === 'Permanent Delete') return 'red'
	if (value === 'Restore') return 'green'
	if (value === 'Download') return 'blue'
	return 'gray'
}
</script>
