// frontend/src/pages/InboxPage.tsx
import { useState, useCallback } from "react"
import { useSelection } from "@/hooks/useSelection"
import { DropZoneOverlay } from "@/components/DropZoneOverlay"
import { CategoryBadge } from "@/components/CategoryBadge"
import { AssetTags } from "@/components/AssetTags"
import { AssetCardColor, CARD_COLOR_BORDER_CLASS } from "@/components/AssetCardColor"
import { useNavigate } from "react-router"
import { useFrappeGetCall } from "frappe-react-sdk"
import { HugeiconsIcon } from "@hugeicons/react"
import { CloudUploadIcon, Delete02Icon, Download04Icon, Film01Icon, GridViewIcon, Album01Icon, ListViewIcon, Move01Icon, PencilEdit01Icon } from "@hugeicons/core-free-icons"
import { Badge } from "@/components/ui/badge"
import { cn, formatBytes, formatDuration } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { AssetDropdownMenu, AssetContextMenu } from "@/components/AssetCardMenu"
import type { AssetMenuActions } from "@/components/AssetCardMenu"
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/components/ui/empty"
import { Checkbox } from "@/components/ui/checkbox"
import { useUploadContext } from "@/contexts/UploadContext"
import { MoveAssetDialog } from "@/components/MoveAssetDialog"
import { DeleteAssetDialog } from "@/components/DeleteAssetDialog"
import { RenameAssetDialog } from "@/components/RenameAssetDialog"
import { MediaPlayerDialog } from "@/components/MediaPlayerDialog"
import { useDownload } from "@/hooks/useDownload"
import { UserAvatar } from "@/components/UserAvatar"
import { Skeleton } from "@/components/ui/skeleton"
import type { VMSAsset } from "@/types"

const PAGE_SIZE = 20

interface PaginatedInboxAssets {
  assets: VMSAsset[]
  total: number
  page: number
  page_size: number
  total_pages: number
}

export function UncategorisedPage() {
  const navigate = useNavigate()
  const { openUpload } = useUploadContext()
  const [moveOpen, setMoveOpen] = useState(false)
  const [deleteOpen, setDeleteOpen] = useState(false)
  const [renameOpen, setRenameOpen] = useState(false)
  const [previewAsset, setPreviewAsset] = useState<VMSAsset | null>(null)
  const { selected, toggleSelect, toggleSelectAll, clearSelection } = useSelection()
  const [view, setView] = useState<"list" | "grid">("grid")
  const [page, setPage] = useState(1)
  const { downloadOne, downloadMany, isDownloading } = useDownload()

  const { data: inboxData, mutate } = useFrappeGetCall<{ message: PaginatedInboxAssets }>(
    "vms.api.get_inbox_assets",
    { page, page_size: PAGE_SIZE },
    `inbox-assets-p${page}`,
  )

  const assets = inboxData?.message?.assets ?? null
  const total = inboxData?.message?.total ?? 0
  const totalPages = inboxData?.message?.total_pages ?? 1

  const handleMoveComplete = (targetProject: string) => {
    clearSelection()
    navigate(`/projects/${targetProject}`)
  }

  const handleDeleteComplete = () => {
    clearSelection()
    mutate()
  }

  const handleAssetClick = useCallback(
    (asset: VMSAsset) => {
      if (asset.status !== "Ready") return
      if (asset.file_type?.startsWith("video/")) {
        navigate(`/review/${asset.name}`)
      } else {
        setPreviewAsset(asset)
      }
    },
    [navigate],
  )

  const handleBulkDownload = () => {
    if (!assets) return
    const toDownload = assets.filter((a) => selected.has(a.name))
    downloadMany(toDownload)
  }

  const handlePageDrop = useCallback((files: File[]) => {
    openUpload({
      existingFileNames: (assets ?? []).filter((a: VMSAsset) => a.status === "Ready").map((a: VMSAsset) => a.file_name),
      initialFiles: files,
      onComplete: () => mutate(),
    })
  }, [openUpload, assets, mutate])

  const openInboxUpload = useCallback(() => {
    openUpload({
      existingFileNames: (assets ?? []).filter((a: VMSAsset) => a.status === "Ready").map((a: VMSAsset) => a.file_name),
      onComplete: () => mutate(),
    })
  }, [openUpload, assets, mutate])

  // Individual asset menu handlers
  const handleMenuRename = useCallback(
    (asset: VMSAsset) => {
      clearSelection()
      toggleSelect(asset.name)
      setRenameOpen(true)
    },
    [clearSelection, toggleSelect],
  )

  const handleMenuDelete = useCallback(
    (asset: VMSAsset) => {
      clearSelection()
      toggleSelect(asset.name)
      setDeleteOpen(true)
    },
    [clearSelection, toggleSelect],
  )

  const handleMenuMove = useCallback(
    (asset: VMSAsset) => {
      clearSelection()
      toggleSelect(asset.name)
      setMoveOpen(true)
    },
    [clearSelection, toggleSelect],
  )

  const menuActions: AssetMenuActions = {
    onOpen: handleAssetClick,
    onDownload: (asset) => downloadOne(asset.name, asset.file_name),
    onUploadNewVersion: (asset) => openUpload({
      versionOf: asset,
      project: asset.project,
      category: asset.category,
      onComplete: () => mutate(),
    }),
    onRename: handleMenuRename,
    onDelete: handleMenuDelete,
    onMoveToFolder: handleMenuMove,
  }

  const allSelected = assets && assets.length > 0 && assets.every((a: VMSAsset) => selected.has(a.name))

  return (
    <DropZoneOverlay onDrop={handlePageDrop}>
    <div className="space-y-4 md:space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-xl font-bold md:text-2xl">Uncategorised{total > 0 ? ` (${total})` : ""}</h1>
          <p className="mt-1 text-sm text-muted-foreground md:text-base">
            Assets uploaded without a project. Move them into a project when
            ready.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          {selected.size > 0 && (
            <>
              <Button
                variant="outline"
                size="sm"
                onClick={handleBulkDownload}
                disabled={isDownloading}
              >
                <HugeiconsIcon
                  icon={Download04Icon}
                  strokeWidth={2}
                  data-icon="inline-start"
                />
                <span className="hidden sm:inline">
                  {isDownloading ? "Downloading..." : "Download"}
                </span>
                <span className="sm:hidden">
                  {selected.size}
                </span>
                <span className="hidden sm:inline"> ({selected.size})</span>
              </Button>
              {selected.size === 1 && (
                <Button variant="outline" size="sm" onClick={() => setRenameOpen(true)}>
                  <HugeiconsIcon
                    icon={PencilEdit01Icon}
                    strokeWidth={2}
                    data-icon="inline-start"
                  />
                  <span className="hidden sm:inline">Rename</span>
                </Button>
              )}
              <Button variant="outline" size="sm" onClick={() => setMoveOpen(true)}>
                <HugeiconsIcon
                  icon={Move01Icon}
                  strokeWidth={2}
                  data-icon="inline-start"
                />
                <span className="hidden sm:inline">Move ({selected.size})</span>
              </Button>
              <Button variant="outline" size="sm" onClick={() => setDeleteOpen(true)}>
                <HugeiconsIcon
                  icon={Delete02Icon}
                  strokeWidth={2}
                  data-icon="inline-start"
                />
                <span className="hidden sm:inline">Delete ({selected.size})</span>
              </Button>
            </>
          )}
          <Button size="sm" onClick={() => openInboxUpload()}>
            <HugeiconsIcon
              icon={CloudUploadIcon}
              strokeWidth={1.5}
              data-icon="inline-start"
            />
            Upload
          </Button>
        </div>
      </div>

      {!assets ? (
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {Array.from({ length: 8 }).map((_, i) => (
            <Card key={i} className="flex flex-col overflow-hidden pt-0">
              <Skeleton className="aspect-video w-full rounded-none" />
              <CardHeader>
                <Skeleton className="h-4 w-3/4" />
              </CardHeader>
              <CardContent className="mt-auto space-y-2">
                <div className="flex gap-1.5">
                  <Skeleton className="h-5 w-14 rounded-full" />
                  <Skeleton className="h-5 w-12 rounded-full" />
                </div>
                <div className="flex items-center gap-3">
                  <Skeleton className="size-5 rounded-full" />
                  <Skeleton className="h-3 w-16" />
                  <Skeleton className="h-3 w-20" />
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : assets.length === 0 ? (
        <Empty>
          <EmptyHeader>
            <EmptyMedia variant="icon">
              <HugeiconsIcon icon={Album01Icon} strokeWidth={1.5} />
            </EmptyMedia>
            <EmptyTitle>No uncategorised assets</EmptyTitle>
            <EmptyDescription>
              Upload files here to sort them into projects later.
            </EmptyDescription>
          </EmptyHeader>
          <Button size="sm" onClick={() => openInboxUpload()}>
            <HugeiconsIcon icon={CloudUploadIcon} strokeWidth={1.5} data-icon="inline-start" />
            Upload
          </Button>
        </Empty>
      ) : (
        <div className="space-y-2">
          <div className="flex items-center justify-between px-3 py-1">
            <div className="flex items-center gap-3">
              <Checkbox
                checked={allSelected ?? false}
                onCheckedChange={() => toggleSelectAll(assets ?? [])}
              />
              <span className="text-sm text-muted-foreground">
                {selected.size > 0
                  ? `${selected.size} selected`
                  : "Select all"}
              </span>
            </div>
            <ToggleGroup
              className="hidden sm:flex"
              value={[view]}
              onValueChange={(values) => { if (values.length > 0) setView(values[values.length - 1] as "list" | "grid") }}
              variant="outline"
              size="sm"
            >
              <ToggleGroupItem value="list" aria-label="List view">
                <HugeiconsIcon icon={ListViewIcon} strokeWidth={2} />
              </ToggleGroupItem>
              <ToggleGroupItem value="grid" aria-label="Grid view">
                <HugeiconsIcon icon={GridViewIcon} strokeWidth={2} />
              </ToggleGroupItem>
            </ToggleGroup>
          </div>

          {view === "list" ? (
            <div className="space-y-2">
              {assets.map((asset) => (
                <AssetContextMenu key={asset.name} asset={asset} actions={menuActions}>
                  <Card
                    size="sm"
                    className={cn(
                      "cursor-pointer transition-shadow hover:shadow-md",
                      asset.card_color && CARD_COLOR_BORDER_CLASS[asset.card_color],
                    )}
                    onClick={() => handleAssetClick(asset)}
                  >
                    <CardHeader>
                      <div className="flex min-w-0 items-center gap-3">
                        <div onClick={(e) => e.stopPropagation()}>
                          <Checkbox
                            checked={selected.has(asset.name)}
                            onCheckedChange={() => toggleSelect(asset.name)}
                          />
                        </div>
                        <div className="h-10 w-16 shrink-0 overflow-hidden rounded bg-muted">
                          {asset.thumbnail_url ? (
                            <img src={asset.thumbnail_url} alt="" className="h-full w-full object-cover" />
                          ) : (
                            <div className="flex h-full w-full items-center justify-center text-muted-foreground/40">
                              <HugeiconsIcon icon={Film01Icon} size={18} strokeWidth={1.5} />
                            </div>
                          )}
                        </div>
                        <div className="flex min-w-0 flex-1 items-center justify-between gap-2">
                          <CardTitle className="truncate text-sm">
                            {asset.file_name}
                          </CardTitle>
                          <div className="flex shrink-0 items-center gap-2">
                            <CategoryBadge
                              assetName={asset.name}
                              category={asset.category}
                              onChanged={() => mutate()}
                            />
                            <Badge
                              variant={
                                asset.status === "Ready" ? "secondary" : "outline"
                              }
                            >
                              {asset.status}
                            </Badge>
                            <AssetCardColor
                              assetName={asset.name}
                              color={asset.card_color}
                              onChanged={() => mutate()}
                            />
                            <div onClick={(e) => e.stopPropagation()}>
                              <AssetDropdownMenu asset={asset} actions={menuActions} />
                            </div>
                          </div>
                        </div>
                      </div>
                    </CardHeader>
                    <CardContent className="space-y-2 pl-10">
                      <AssetTags
                        assetName={asset.name}
                        tags={asset.tags ?? []}
                        compact
                        onChanged={() => mutate()}
                      />
                      <div className="flex items-center gap-4 text-xs text-muted-foreground">
                        <UserAvatar name={asset.uploader_name} image={asset.uploader_image} />
                        {!!asset.duration_seconds && (
                          <span className="tabular-nums">
                            {formatDuration(asset.duration_seconds)}
                          </span>
                        )}
                        {asset.file_size && (
                          <span>
                            {formatBytes(asset.file_size)}
                          </span>
                        )}
                        {asset.uploaded_at && (
                          <span>
                            Uploaded{" "}
                            {new Date(asset.uploaded_at).toLocaleDateString()}
                          </span>
                        )}
                      </div>
                    </CardContent>
                  </Card>
                </AssetContextMenu>
              ))}
            </div>
          ) : (
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              {assets.map((asset) => (
                <AssetContextMenu key={asset.name} asset={asset} actions={menuActions}>
                  <Card
                    className={cn(
                      "flex cursor-pointer flex-col overflow-hidden pt-0 transition-shadow hover:shadow-md",
                      asset.card_color && CARD_COLOR_BORDER_CLASS[asset.card_color],
                    )}
                    onClick={() => handleAssetClick(asset)}
                  >
                    <div className="relative flex aspect-video w-full items-center justify-center bg-muted">
                      {asset.thumbnail_url ? (
                        <img src={asset.thumbnail_url} alt="" className="h-full w-full object-contain" />
                      ) : (
                        <div className="flex h-full w-full items-center justify-center text-muted-foreground/40">
                          <HugeiconsIcon icon={Film01Icon} size={32} strokeWidth={1.5} />
                        </div>
                      )}
                      {!!asset.duration_seconds && (
                        <span className="absolute right-1.5 bottom-1.5 rounded bg-black/75 px-1.5 py-0.5 text-[11px] font-medium tabular-nums text-white">
                          {formatDuration(asset.duration_seconds)}
                        </span>
                      )}
                    </div>
                    <CardHeader>
                      <div className="flex min-w-0 items-center justify-between gap-2">
                        <div className="flex min-w-0 items-start gap-2">
                          <div onClick={(e) => e.stopPropagation()} className="mt-0.5">
                            <Checkbox
                              checked={selected.has(asset.name)}
                              onCheckedChange={() => toggleSelect(asset.name)}
                            />
                          </div>
                          <CardTitle className="truncate text-sm">
                            {asset.file_name}
                          </CardTitle>
                        </div>
                        <div className="flex shrink-0 items-center gap-0.5">
                          <AssetCardColor
                            assetName={asset.name}
                            color={asset.card_color}
                            onChanged={() => mutate()}
                          />
                          <div onClick={(e) => e.stopPropagation()}>
                            <AssetDropdownMenu asset={asset} actions={menuActions} />
                          </div>
                        </div>
                      </div>
                    </CardHeader>
                    <CardContent className="mt-auto space-y-2">
                      <div className="flex flex-wrap gap-1.5">
                        <CategoryBadge
                          assetName={asset.name}
                          category={asset.category}
                          onChanged={() => mutate()}
                        />
                        <Badge
                          variant={
                            asset.status === "Ready" ? "secondary" : "outline"
                          }
                        >
                          {asset.status}
                        </Badge>
                      </div>
                      <AssetTags
                        assetName={asset.name}
                        tags={asset.tags ?? []}
                        onChanged={() => mutate()}
                      />
                      <div className="flex items-center gap-3 text-xs text-muted-foreground">
                        <UserAvatar name={asset.uploader_name} image={asset.uploader_image} />
                        {asset.file_size && (
                          <span>
                            {formatBytes(asset.file_size)}
                          </span>
                        )}
                        {asset.uploaded_at && (
                          <span>
                            {new Date(asset.uploaded_at).toLocaleDateString()}
                          </span>
                        )}
                      </div>
                    </CardContent>
                  </Card>
                </AssetContextMenu>
              ))}
            </div>
          )}

          {totalPages > 1 && (
            <div className="flex items-center justify-end gap-2 pt-4">
              <Button
                variant="outline"
                size="sm"
                disabled={page <= 1}
                onClick={() => setPage(page - 1)}
              >
                Previous
              </Button>
              <span className="text-sm text-muted-foreground">
                Page {page} of {totalPages}
              </span>
              <Button
                variant="outline"
                size="sm"
                disabled={page >= totalPages}
                onClick={() => setPage(page + 1)}
              >
                Next
              </Button>
            </div>
          )}
        </div>
      )}


      <MoveAssetDialog
        open={moveOpen}
        onOpenChange={setMoveOpen}
        assetNames={Array.from(selected)}
        onComplete={handleMoveComplete}
      />

      <DeleteAssetDialog
        open={deleteOpen}
        onOpenChange={setDeleteOpen}
        assetNames={Array.from(selected)}
        onComplete={handleDeleteComplete}
      />

      {selected.size === 1 && (() => {
        const selectedAsset = assets?.find((a) => a.name === Array.from(selected)[0])
        return selectedAsset ? (
          <RenameAssetDialog
            open={renameOpen}
            onOpenChange={setRenameOpen}
            assetName={selectedAsset.name}
            currentFileName={selectedAsset.file_name}
            onComplete={() => mutate()}
          />
        ) : null
      })()}

      <MediaPlayerDialog
        open={!!previewAsset}
        onOpenChange={(open) => { if (!open) setPreviewAsset(null) }}
        assetName={previewAsset?.name ?? null}
        fileName={previewAsset?.file_name}
        fileType={previewAsset?.file_type}
      />
    </div>
    </DropZoneOverlay>
  )
}

// frontend/src/pages/InboxPage.vue
<template>
	<PageHeader>
		<PageHeaderTitle>
			<h1 class="truncate">
				Inbox
				<span v-if="total" class="text-ink-gray-5">{{ total }}</span>
			</h1>
		</PageHeaderTitle>
		<Button
			variant="solid"
			label="Upload"
			icon-left="lucide-upload"
			data-testid="inbox-upload"
			@click="openUpload({ onDone: reload })"
		/>
	</PageHeader>

	<div class="px-3 py-5 pb-10 sm:px-5" data-testid="inbox">
		<!-- Bulk toolbar -->
		<div
			v-if="selection.length"
			class="mb-3 flex flex-wrap items-center gap-2"
			data-testid="inbox-bulk-bar"
		>
			<span class="text-sm text-ink-gray-6">{{ selection.length }} selected</span>
			<Select
				v-model="bulkCategory"
				:options="categoryOptions"
				placeholder="Categorise"
				:disabled="bulkBusy"
				class="w-36"
				data-testid="inbox-bulk-categorise"
				@update:model-value="bulkCategorise"
			/>
			<Button
				label="Download"
				icon-left="lucide-download"
				:loading="isDownloading"
				@click="downloadMany(selectedAssets)"
			/>
			<Button variant="ghost" label="Clear" :disabled="bulkBusy" @click="selection = []" />
		</div>

		<LoadingText v-if="inbox.loading && !assets.length" :lines="4" />
		<div v-else-if="inbox.error && !assets.length" class="space-y-3 py-6">
			<ErrorMessage :message="inbox.error" />
			<Button label="Try again" icon-left="lucide-refresh-cw" @click="reload" />
		</div>

		<EmptyState
			v-else-if="!assets.length"
			icon="lucide-inbox"
			title="No uncategorised assets"
			description="Files uploaded without a project land here. Categorise them, then move them into a project."
			data-testid="inbox-empty"
		>
			<template #actions>
				<Button
					variant="solid"
					label="Upload"
					icon-left="lucide-upload"
					@click="openUpload({ onDone: reload })"
				/>
			</template>
		</EmptyState>

		<template v-else>
			<List
				v-model:selection="selection"
				selectable
				:columns="COLUMNS"
				class="-mx-3 list-row-px-3 max-sm:[--list-columns:auto_minmax(0,1fr)_auto]"
				data-testid="inbox-list"
			>
				<ListHeader class="max-sm:!hidden">
					<ListHeaderCell>Name</ListHeaderCell>
					<ListHeaderCell>Categorise</ListHeaderCell>
					<ListHeaderCell>Status</ListHeaderCell>
					<ListHeaderCell class="justify-end">Size</ListHeaderCell>
					<ListHeaderCell>Uploaded</ListHeaderCell>
					<ListHeaderCell />
				</ListHeader>
				<ListRows v-slot="{ item: groupRow }" :items="groupedRows">
					<ListGroup v-if="groupRow.dayGroup" :label="groupRow.dayGroup.label">
						<ListRow
							v-for="asset in groupRow.dayGroup.items"
							:key="asset.name"
							:value="asset.name"
							class="min-h-12"
							data-testid="inbox-row"
						>
							<ListCell>
								<div class="flex min-w-0 items-center gap-3">
									<div
										class="flex h-6 w-10 shrink-0 items-center justify-center overflow-hidden rounded bg-surface-gray-2"
									>
										<img
											v-if="asset.thumbnail_url"
											:src="asset.thumbnail_url"
											:alt="asset.file_name"
											class="size-full object-cover"
										/>
										<span
											v-else
											:class="[
												fileIcon(asset.file_type),
												'size-3.5 text-ink-gray-5',
											]"
											aria-hidden="true"
										/>
									</div>
									<div class="min-w-0">
										<RouterLink
											v-if="asset.status === 'Ready'"
											:to="`/review/${asset.name}`"
											class="block truncate text-base text-ink-gray-8 hover:underline"
											data-testid="inbox-row-name"
											@click.stop
										>
											{{ asset.file_name }}
										</RouterLink>
										<p v-else class="truncate text-base text-ink-gray-8">
											{{ asset.file_name }}
										</p>
										<p class="mt-0.5 truncate text-sm text-ink-gray-5">
											{{ asset.uploader_name || asset.uploaded_by }}
											<span class="sm:hidden">
												· {{ asset.status }} ·
												{{ formatBytes(asset.file_size ?? 0) }}
											</span>
										</p>
										<div class="mt-1.5 w-32 sm:hidden" @click.stop>
											<Select
												v-model="categoryDrafts[asset.name]"
												:options="categoryOptions"
												:disabled="bulkBusy || busy.has(asset.name)"
												aria-label="Categorise asset"
												@update:model-value="categorise(asset, $event)"
											/>
										</div>
									</div>
								</div>
							</ListCell>
							<ListCell class="max-sm:hidden" @click.stop>
								<Select
									v-model="categoryDrafts[asset.name]"
									:options="categoryOptions"
									:disabled="bulkBusy || busy.has(asset.name)"
									data-testid="inbox-row-categorise"
									@update:model-value="categorise(asset, $event)"
								/>
							</ListCell>
							<ListCell class="max-sm:hidden">
								<Badge
									:label="asset.status"
									:theme="assetStatusTheme(asset.status)"
								/>
							</ListCell>
							<ListCell
								class="justify-end text-sm text-ink-gray-7 tabular-nums max-sm:hidden"
							>
								{{ formatBytes(asset.file_size ?? 0) }}
							</ListCell>
							<ListCell class="text-sm max-sm:hidden">
								<RelativeTime :date="asset.uploaded_at || asset.creation" />
							</ListCell>
							<ListCell class="justify-end" @click.stop>
								<AssetActions :asset="asset" @changed="reload" />
							</ListCell>
						</ListRow>
					</ListGroup>
				</ListRows>
			</List>

			<div
				v-if="assets.length < total"
				class="mt-4 flex flex-wrap items-center justify-center gap-3"
				data-testid="inbox-load-more"
			>
				<span class="text-sm text-ink-gray-5">{{ assets.length }} of {{ total }}</span>
				<ErrorMessage v-if="inbox.error" :message="inbox.error" />
				<Button
					:label="inbox.error ? 'Try again' : 'Load more'"
					:loading="inbox.loading"
					@click="loadMore"
				/>
			</div>
		</template>
	</div>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { RouterLink } from 'vue-router'
import {
	Badge,
	Button,
	ErrorMessage,
	LoadingText,
	PageHeader,
	PageHeaderTitle,
	Select,
	toast,
	useCall,
	usePageMeta,
} from 'frappe-ui'
import {
	List,
	ListCell,
	ListGroup,
	ListHeader,
	ListHeaderCell,
	ListRow,
	ListRows,
} from 'frappe-ui/list'
import { ASSET_CATEGORIES, type Asset, type AssetCategory } from '@/types'
import { groupByDay } from '@/lib/dates'
import { formatBytes, serverMessage } from '@/lib/format'
import { assetStatusTheme } from '@/lib/status'
import { useDownload } from '@/composables/useDownload'
import { useOverlays } from '@/composables/useOverlays'
import AssetActions from '@/components/assets/AssetActions.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import RelativeTime from '@/components/common/RelativeTime.vue'

usePageMeta(() => ({ title: 'Inbox · VMS' }))

const PAGE_SIZE = 20
const COLUMNS = ['minmax(12rem,1fr)', '9rem', '6rem', '5rem', '7rem', '2.5rem']

const { openUpload } = useOverlays()
const { downloadMany, isDownloading } = useDownload()

const categoryOptions = ASSET_CATEGORIES.map((c) => ({ label: c, value: c }))

interface InboxResponse {
	assets: Asset[]
	total: number
	page: number
	page_size: number
	total_pages: number
}

interface InboxParams {
	start: number
	page_length: number
}

// Pages accumulate into `assets`; `start` is the offset of the page in flight.
const start = ref(0)
const assets = ref<Asset[]>([])
const total = ref(0)
const categoryDrafts = reactive<Record<string, AssetCategory | undefined>>({})

const inbox = useCall<InboxResponse, InboxParams>({
	url: '/api/v2/method/vms.api.get_inbox_assets',
	method: 'GET',
	params: () => ({ start: start.value, page_length: PAGE_SIZE }),
	cacheKey: 'inbox-assets',
	onSuccess: (data) => {
		total.value = data.total
		for (const asset of data.assets) categoryDrafts[asset.name] = asset.category
		assets.value = start.value === 0 ? data.assets : [...assets.value, ...data.assets]
	},
})

function reload() {
	selection.value = []
	start.value = 0
	void inbox.reload()
}

function loadMore() {
	start.value = assets.value.length
	void inbox.reload()
}

const groups = computed(() => groupByDay(assets.value, (a) => a.uploaded_at || a.creation))
const groupedRows = computed(() => {
	const groupStarts = new Map(groups.value.map((group) => [group.items[0]?.name, group]))
	return assets.value.map((asset) => ({ ...asset, dayGroup: groupStarts.get(asset.name) }))
})

const selection = ref<string[]>([])
const selectedAssets = computed(() => assets.value.filter((a) => selection.value.includes(a.name)))

const categoryCall = useCall<
	{ status: string; asset_name: string; category: string },
	{ asset_name: string; category: string }
>({
	url: '/api/v2/method/vms.api.update_asset_category',
	method: 'POST',
	immediate: false,
})

const busy = ref(new Set<string>())
const bulkBusy = ref(false)
const bulkCategory = ref<AssetCategory>()

async function setCategory(asset: Asset, category: AssetCategory) {
	if (asset.category === category) return
	await categoryCall.submit({ asset_name: asset.name, category })
	asset.category = category
	categoryDrafts[asset.name] = category
}

async function categorise(asset: Asset, value: string | number | undefined) {
	const category = toCategory(value)
	if (!category) return
	busy.value = new Set(busy.value).add(asset.name)
	try {
		await setCategory(asset, category)
	} catch (e) {
		categoryDrafts[asset.name] = asset.category
		toast.error(serverMessage(e) || 'Could not update category')
	} finally {
		const next = new Set(busy.value)
		next.delete(asset.name)
		busy.value = next
	}
}

async function bulkCategorise(value: string | number | undefined) {
	const category = toCategory(value)
	if (!category) return
	const targets = [...selectedAssets.value]
	bulkBusy.value = true
	let failed = 0
	try {
		for (const asset of targets) {
			try {
				await setCategory(asset, category)
			} catch {
				categoryDrafts[asset.name] = asset.category
				failed++
			}
		}
	} finally {
		bulkBusy.value = false
	}
	if (failed) toast.error(`${failed} asset(s) could not be updated`)
	else toast.success(`${targets.length} asset(s) marked ${category}`)
	bulkCategory.value = undefined
	selection.value = []
}

function toCategory(value: string | number | undefined): AssetCategory | null {
	return ASSET_CATEGORIES.includes(value as AssetCategory) ? (value as AssetCategory) : null
}

function fileIcon(fileType?: string): string {
	if (fileType?.startsWith('video/')) return 'lucide-film'
	if (fileType?.startsWith('image/')) return 'lucide-image'
	if (fileType?.startsWith('audio/')) return 'lucide-music'
	return 'lucide-file'
}
</script>
