// frontend/src/pages/SharedProjectPage.tsx
import { useState } from "react"
import { useParams, useSearchParams } from "react-router"
import { useFrappeGetCall, useFrappePostCall } from "frappe-react-sdk"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { formatBytes } from "@/lib/utils"
import { toast } from "sonner"
import { ArrowLeft, ArrowRight, Download, Film } from "lucide-react"

interface SharedProject {
  name: string
  project_name: string
  status: string
  description?: string
  thumbnail_url?: string
}

interface SharedAsset {
  name: string
  file_name: string
  category: string
  file_size?: number
  file_type?: string
  uploaded_at?: string
  creation: string
  thumbnail_url?: string
}

interface PaginatedAssets {
  assets: SharedAsset[]
  total: number
  page: number
  page_size: number
  total_pages: number
}

const PAGE_SIZE = 20

export function SharedProjectPage() {
  const { projectId } = useParams()
  const [searchParams] = useSearchParams()
  const token = searchParams.get("token")
  const [page, setPage] = useState(1)

  const { data: projectData, isLoading: projectLoading, error: projectError } = useFrappeGetCall<{ message: SharedProject }>(
    "vms.api.get_shared_project",
    { project: projectId!, token: token ?? "" },
    token ? `shared-project-${projectId}` : null,
  )

  const { data: assetsData, isLoading: assetsLoading } = useFrappeGetCall<{ message: PaginatedAssets }>(
    "vms.api.get_shared_project_assets",
    { project: projectId!, token: token ?? "", page, page_size: PAGE_SIZE },
    token ? `shared-assets-${projectId}-p${page}` : null,
  )

  const project = projectData?.message
  const assets = assetsData?.message?.assets ?? []
  const total = assetsData?.message?.total ?? 0
  const totalPages = assetsData?.message?.total_pages ?? 1

  if (!token) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background p-4">
        <div className="text-center">
          <h1 className="text-2xl font-bold">Invalid share link</h1>
          <p className="mt-2 text-muted-foreground">This link is missing a share token.</p>
        </div>
      </div>
    )
  }

  if (projectError) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background p-4">
        <div className="text-center">
          <h1 className="text-2xl font-bold">Link expired or invalid</h1>
          <p className="mt-2 text-muted-foreground">This share link is no longer valid.</p>
        </div>
      </div>
    )
  }

  if (projectLoading || !project) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <Spinner className="size-6" />
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-6xl p-4 md:p-8">
        {/* Header */}
        <div className="mb-6 space-y-2">
          <div className="flex items-center gap-3">
            <h1 className="text-2xl font-bold md:text-3xl">{project.project_name}</h1>
            <Badge variant="outline">{project.status}</Badge>
          </div>
          {project.description && (
            <div
              className="prose prose-sm max-w-none text-muted-foreground"
              dangerouslySetInnerHTML={{ __html: project.description }}
            />
          )}
          <p className="text-sm text-muted-foreground">
            {total} {total === 1 ? "file" : "files"} shared
          </p>
        </div>

        {/* Asset Grid */}
        {assetsLoading && assets.length === 0 ? (
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {Array.from({ length: 8 }).map((_, i) => (
              <Card key={i} className="flex flex-col overflow-hidden pt-0">
                <Skeleton className="aspect-video w-full rounded-none" />
                <CardHeader>
                  <Skeleton className="h-4 w-3/4" />
                </CardHeader>
                <CardContent className="mt-auto space-y-2">
                  <Skeleton className="h-3 w-1/2" />
                </CardContent>
              </Card>
            ))}
          </div>
        ) : assets.length === 0 ? (
          <div className="py-12 text-center text-muted-foreground">
            No files in this project.
          </div>
        ) : (
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {assets.map((asset) => (
              <SharedAssetCard
                key={asset.name}
                asset={asset}
                projectId={projectId!}
                token={token}
              />
            ))}
          </div>
        )}

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="mt-6 flex items-center justify-center gap-4">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page <= 1}
            >
              <ArrowLeft data-icon="inline-start" />
              Previous
            </Button>
            <span className="text-sm text-muted-foreground">
              Page {page} of {totalPages}
            </span>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={page >= totalPages}
            >
              Next
              <ArrowRight data-icon="inline-end" />
            </Button>
          </div>
        )}

        {/* Footer */}
        <div className="mt-12 border-t pt-4 text-center text-xs text-muted-foreground">
          Shared via VMS
        </div>
      </div>
    </div>
  )
}

function SharedAssetCard({
  asset,
  projectId,
  token,
}: {
  asset: SharedAsset
  projectId: string
  token: string
}) {
  const [downloading, setDownloading] = useState(false)
  const { call: callDownload } = useFrappePostCall("vms.api.get_shared_asset_download_url")

  const handleDownload = async () => {
    setDownloading(true)
    try {
      const res = await callDownload({ asset_name: asset.name, project: projectId, token })
      const url = (res as { message: { url: string } }).message.url
      const a = document.createElement("a")
      a.href = url
      a.download = asset.file_name
      a.click()
    } catch {
      toast.error("Failed to download file")
    } finally {
      setDownloading(false)
    }
  }

  const isVideo = asset.file_type?.startsWith("video/")

  return (
    <Card className="group flex flex-col overflow-hidden pt-0">
      <div className="relative flex aspect-video items-center justify-center bg-muted">
        {asset.thumbnail_url ? (
          <img
            src={asset.thumbnail_url}
            alt={asset.file_name}
            className="h-full w-full object-contain"
          />
        ) : (
          <div className="flex h-full items-center justify-center">
            <Film strokeWidth={1.5} size={32} className="text-muted-foreground" />
          </div>
        )}
        {isVideo && (
          <Badge variant="secondary" className="absolute bottom-2 left-2 text-[10px]">
            Video
          </Badge>
        )}
      </div>
      <CardHeader className="pb-2">
        <p className="truncate text-sm font-medium" title={asset.file_name}>
          {asset.file_name}
        </p>
      </CardHeader>
      <CardContent className="mt-auto flex items-center justify-between">
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          {asset.file_size && <span>{formatBytes(asset.file_size)}</span>}
          <Badge variant="outline" className="text-[10px]">{asset.category}</Badge>
        </div>
        <Button
          variant="ghost"
          size="icon-sm"
          onClick={handleDownload}
          disabled={downloading}
          title="Download"
        >
          <Download size={14} />
        </Button>
      </CardContent>
    </Card>
  )
}

// frontend/src/pages/SharedProjectPage.vue
<template>
	<!-- Guest page outside the shell: its own full-height root, no sidebar. -->
	<div class="flex h-screen flex-col bg-surface-base" data-testid="shared-project">
		<div v-if="!token" class="grid flex-1 place-items-center px-4">
			<EmptyState
				icon="lucide-link-2-off"
				title="Invalid share link"
				description="This link is missing a share token."
			/>
		</div>

		<div v-else-if="project.error" class="grid flex-1 place-items-center px-4">
			<EmptyState
				icon="lucide-link-2-off"
				title="Link expired or invalid"
				description="This share link is no longer valid."
			/>
		</div>

		<div v-else-if="!project.data" class="grid flex-1 place-items-center">
			<Spinner class="size-6 text-ink-gray-5" />
		</div>

		<template v-else>
			<PageHeaderBase class="flex min-h-12 shrink-0 items-center border-b px-3 sm:px-5">
				<PageHeaderTitle>
					<h1 class="truncate">{{ project.data.project_name }}</h1>
					<p class="truncate text-sm text-ink-gray-5" data-testid="shared-count">
						{{ total }} {{ total === 1 ? 'file' : 'files' }} shared
					</p>
				</PageHeaderTitle>
				<div class="ml-auto flex shrink-0 items-center gap-2">
					<Badge :label="project.data.status" theme="gray" variant="subtle" />
					<Button
						v-if="assets.length"
						variant="subtle"
						icon-left="lucide-download"
						label="Download all"
						:loading="downloadingAll"
						data-testid="shared-download-all"
						@click="downloadAll"
					/>
				</div>
			</PageHeaderBase>

			<div class="min-h-0 flex-1 overflow-y-auto px-3 py-5 pb-10 sm:px-5">
				<div class="mx-auto max-w-6xl space-y-5">
					<!-- eslint-disable vue/no-v-html -- server-rendered Frappe HTML -->
					<div
						v-if="project.data.description"
						class="prose prose-sm max-w-none text-ink-gray-6"
						v-html="project.data.description"
					/>
					<!-- eslint-enable vue/no-v-html -->

					<div
						v-if="assetsCall.loading && !assets.length"
						class="grid place-items-center py-12"
					>
						<Spinner class="size-5 text-ink-gray-5" />
					</div>

					<EmptyState
						v-else-if="!assets.length"
						icon="lucide-film"
						title="No files in this project"
					/>

					<div v-else class="grid grid-cols-[repeat(auto-fill,minmax(220px,1fr))] gap-3">
						<article
							v-for="asset in assets"
							:key="asset.name"
							class="group cursor-pointer overflow-hidden rounded-md border border-outline-gray-1 bg-surface-base transition hover:border-outline-gray-2 hover:shadow-sm"
							data-testid="shared-asset-card"
							@click="open(asset)"
						>
							<div class="relative aspect-video bg-surface-gray-2">
								<img
									v-if="asset.thumbnail_url"
									:src="asset.thumbnail_url"
									alt=""
									class="size-full object-cover"
								/>
								<div
									v-else
									class="grid size-full place-items-center text-ink-gray-4"
								>
									<span
										:class="[previewIcon(asset), 'size-8']"
										aria-hidden="true"
									/>
								</div>
							</div>
							<div class="flex items-start gap-2 p-3">
								<div class="min-w-0 flex-1">
									<p
										class="truncate text-base text-ink-gray-8"
										:title="asset.file_name"
									>
										{{ asset.file_name }}
									</p>
									<p
										class="mt-1 flex items-center gap-2 truncate text-sm text-ink-gray-5"
									>
										<span v-if="asset.file_size">{{
											formatBytes(asset.file_size)
										}}</span>
										<Badge
											:label="asset.category"
											theme="gray"
											variant="subtle"
										/>
									</p>
								</div>
								<Button
									variant="ghost"
									icon="lucide-download"
									label="Download"
									@click.stop="download(asset)"
								/>
							</div>
						</article>
					</div>

					<div v-if="totalPages > 1" class="flex items-center justify-center gap-3">
						<Button
							variant="outline"
							icon-left="lucide-arrow-left"
							label="Previous"
							:disabled="page <= 1"
							@click="page -= 1"
						/>
						<span class="text-sm text-ink-gray-5">
							Page {{ page }} of {{ totalPages }}
						</span>
						<Button
							variant="outline"
							icon-right="lucide-arrow-right"
							label="Next"
							:disabled="page >= totalPages"
							@click="page += 1"
						/>
					</div>

					<p
						class="border-t border-outline-gray-1 pt-4 text-center text-xs text-ink-gray-5"
					>
						Shared via VMS
					</p>
				</div>
			</div>
		</template>

		<MediaPreviewDialog
			v-if="preview"
			:open="Boolean(preview)"
			:url="preview.url"
			:name="preview.asset.file_name"
			:mime="preview.asset.file_type ?? ''"
			:download-url="preview.downloadUrl"
			@update:open="preview = null"
		/>
	</div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import {
	Badge,
	Button,
	PageHeaderBase,
	PageHeaderTitle,
	Spinner,
	toast,
	useCall,
	usePageMeta,
} from 'frappe-ui'
import type { ViewUrlResponse } from '@/types'
import EmptyState from '@/components/common/EmptyState.vue'
import MediaPreviewDialog from '@/components/common/MediaPreviewDialog.vue'
import { formatBytes, serverMessage } from '@/lib/format'

interface SharedProject {
	name: string
	project_name: string
	status: string
	description?: string
	thumbnail_url?: string
}

interface SharedAsset {
	name: string
	file_name: string
	category: string
	file_size?: number
	file_type?: string
	uploaded_at?: string
	creation: string
	thumbnail_url?: string
}

interface SharedAssetsResponse {
	assets: SharedAsset[]
	total: number
	page: number
	page_size: number
	total_pages: number
}

interface SharedAssetParams {
	asset_name: string
	project: string
	token: string
}

const PAGE_SIZE = 20

const props = defineProps<{ projectId: string }>()

const route = useRoute()

/** Share links carry their access token in the query string. */
const token = computed(() => {
	const value = route.query.token
	return typeof value === 'string' && value ? value : ''
})

const page = ref(1)
const preview = ref<{ asset: SharedAsset; url: string; downloadUrl?: string } | null>(null)
const downloadingAll = ref(false)

const project = useCall<SharedProject, { project: string; token: string }>({
	url: '/api/v2/method/vms.api.get_shared_project',
	method: 'GET',
	params: () => ({ project: props.projectId, token: token.value }),
	immediate: Boolean(token.value),
	cacheKey: ['shared-project', props.projectId],
})

const assetsCall = useCall<
	SharedAssetsResponse,
	{ project: string; token: string; page: number; page_size: number }
>({
	url: '/api/v2/method/vms.api.get_shared_project_assets',
	method: 'GET',
	params: () => ({
		project: props.projectId,
		token: token.value,
		page: page.value,
		page_size: PAGE_SIZE,
	}),
	immediate: Boolean(token.value),
	refetch: true,
	cacheKey: ['shared-project-assets', props.projectId],
})

const viewUrl = useCall<ViewUrlResponse, SharedAssetParams>({
	url: '/api/v2/method/vms.api.get_shared_asset_view_url',
	method: 'POST',
	immediate: false,
})

const downloadUrl = useCall<ViewUrlResponse, SharedAssetParams>({
	url: '/api/v2/method/vms.api.get_shared_asset_download_url',
	method: 'POST',
	immediate: false,
})

const assets = computed(() => assetsCall.data?.assets ?? [])
const total = computed(() => assetsCall.data?.total ?? 0)
const totalPages = computed(() => assetsCall.data?.total_pages ?? 1)

usePageMeta(() => ({
	title: project.data ? `${project.data.project_name} · VMS` : 'Shared project · VMS',
}))

function previewIcon(asset: SharedAsset): string {
	return asset.file_type?.startsWith('image/') ? 'lucide-image' : 'lucide-film'
}

function paramsFor(asset: SharedAsset): SharedAssetParams {
	return { asset_name: asset.name, project: props.projectId, token: token.value }
}

async function open(asset: SharedAsset) {
	try {
		const [view, dl] = await Promise.all([
			viewUrl.submit(paramsFor(asset)),
			downloadUrl.submit(paramsFor(asset)),
		])
		if (view?.url) preview.value = { asset, url: view.url, downloadUrl: dl?.url }
	} catch (error) {
		toast.error(serverMessage(error) || 'Could not open preview')
	}
}

/** Presigned download URLs carry Content-Disposition, so a plain navigation saves the file. */
async function download(asset: SharedAsset) {
	try {
		const result = await downloadUrl.submit(paramsFor(asset))
		if (result?.url) triggerDownload(result.url, asset.file_name)
	} catch (error) {
		toast.error(serverMessage(error) || 'Failed to download file')
	}
}

async function downloadAll() {
	downloadingAll.value = true
	try {
		for (const asset of assets.value) {
			await download(asset)
			// Give the browser a beat between downloads so none is dropped.
			await new Promise((resolve) => setTimeout(resolve, 300))
		}
	} finally {
		downloadingAll.value = false
	}
}

function triggerDownload(url: string, fileName: string) {
	const anchor = document.createElement('a')
	anchor.href = url
	anchor.download = fileName
	anchor.rel = 'noopener'
	document.body.appendChild(anchor)
	anchor.click()
	anchor.remove()
}
</script>
