// frontend/src/pages/TrashPage.tsx
import { useState } from "react"
import { useFrappeGetCall, useFrappePostCall } from "frappe-react-sdk"
import { toast } from "sonner"
import { formatDistanceToNow } from "date-fns"
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/components/ui/empty"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Checkbox } from "@/components/ui/checkbox"
import { Skeleton } from "@/components/ui/skeleton"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { UserAvatar } from "@/components/UserAvatar"
import { formatBytes } from "@/lib/utils"
import type { VMSAsset, VMSFolder } from "@/types"
import { LoadMoreControls } from "@/components/LoadMoreControls"
import { ArchiveRestore, Shredder, Trash2 } from "lucide-react"

const PAGE_SIZE = 20

export function TrashPage() {
  const [tab, setTab] = useState("assets")
  const [assetLimit, setAssetLimit] = useState(PAGE_SIZE)
  const [folderLimit, setFolderLimit] = useState(PAGE_SIZE)
  const [selectedAssets, setSelectedAssets] = useState<Set<string>>(new Set())
  const [selectedFolders, setSelectedFolders] = useState<Set<string>>(new Set())
  const [emptyTrashOpen, setEmptyTrashOpen] = useState(false)

  // Assets data
  const { data: assetData, isLoading: assetsLoading, mutate: mutateAssets } = useFrappeGetCall<{
    message: {
      assets: VMSAsset[]
      total: number
      page: number
      page_size: number
      total_pages: number
    }
  }>(
    "vms.api.get_trash_assets",
    { page: 1, page_size: assetLimit },
    `trash-assets-l${assetLimit}`,
    // growing the limit changes the SWR key; keep loaded rows on screen while the
    // bigger page fetches instead of flashing back to skeletons
    { keepPreviousData: true },
  )

  // Folders data
  const { data: folderData, isLoading: foldersLoading, mutate: mutateFolders } = useFrappeGetCall<{
    message: {
      folders: VMSFolder[]
      total: number
      page: number
      page_size: number
      total_pages: number
    }
  }>(
    "vms.api.get_trash_folders",
    { page: 1, page_size: folderLimit },
    `trash-folders-l${folderLimit}`,
    { keepPreviousData: true },
  )

  const { call: restoreAsset, loading: restoringAsset } = useFrappePostCall("vms.api.restore_asset")
  const { call: permanentlyDelete, loading: permDeleting } = useFrappePostCall("vms.api.permanently_delete_asset")
  const { call: restoreFolder, loading: restoringFolder } = useFrappePostCall("vms.api.restore_folder")
  const { call: permanentlyDeleteFolder, loading: permDeletingFolder } = useFrappePostCall("vms.api.permanently_delete_folder")
  const { call: emptyTrash, loading: emptying } = useFrappePostCall("vms.api.empty_trash")

  const assets = assetData?.message?.assets ?? []
  const assetTotal = assetData?.message?.total ?? 0

  const folders = folderData?.message?.folders ?? []
  const folderTotal = folderData?.message?.total ?? 0

  const totalItems = assetTotal + folderTotal

  const allAssetsSelected = assets.length > 0 && assets.every((a) => selectedAssets.has(a.name))
  const allFoldersSelected = folders.length > 0 && folders.every((f) => selectedFolders.has(f.name))

  const busy = restoringAsset || permDeleting || restoringFolder || permDeletingFolder || emptying

  // Asset handlers
  const toggleAssetSelect = (name: string) => {
    setSelectedAssets((prev) => {
      const next = new Set(prev)
      if (next.has(name)) next.delete(name)
      else next.add(name)
      return next
    })
  }

  const toggleAllAssets = () => {
    if (allAssetsSelected) setSelectedAssets(new Set())
    else setSelectedAssets(new Set(assets.map((a) => a.name)))
  }

  const handleRestoreAssets = async (names?: string[]) => {
    const toRestore = names ?? Array.from(selectedAssets)
    try {
      for (const name of toRestore) await restoreAsset({ asset_name: name })
      toast.success(`Restored ${toRestore.length} asset${toRestore.length > 1 ? "s" : ""}`)
      setSelectedAssets(new Set())
      mutateAssets()
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : "Failed to restore")
    }
  }

  const handlePermDeleteAssets = async (names?: string[]) => {
    const toDelete = names ?? Array.from(selectedAssets)
    try {
      for (const name of toDelete) await permanentlyDelete({ asset_name: name })
      toast.success(`Permanently deleted ${toDelete.length} asset${toDelete.length > 1 ? "s" : ""}`)
      setSelectedAssets(new Set())
      mutateAssets()
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : "Failed to delete")
    }
  }

  // Folder handlers
  const toggleFolderSelect = (name: string) => {
    setSelectedFolders((prev) => {
      const next = new Set(prev)
      if (next.has(name)) next.delete(name)
      else next.add(name)
      return next
    })
  }

  const toggleAllFolders = () => {
    if (allFoldersSelected) setSelectedFolders(new Set())
    else setSelectedFolders(new Set(folders.map((f) => f.name)))
  }

  const handleRestoreFolders = async (names?: string[]) => {
    const toRestore = names ?? Array.from(selectedFolders)
    try {
      for (const name of toRestore) await restoreFolder({ folder_name: name })
      toast.success(`Restored ${toRestore.length} folder${toRestore.length > 1 ? "s" : ""}`)
      setSelectedFolders(new Set())
      mutateFolders()
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : "Failed to restore")
    }
  }

  const handlePermDeleteFolders = async (names?: string[]) => {
    const toDelete = names ?? Array.from(selectedFolders)
    try {
      for (const name of toDelete) await permanentlyDeleteFolder({ folder_name: name })
      toast.success(`Permanently deleted ${toDelete.length} folder${toDelete.length > 1 ? "s" : ""}`)
      setSelectedFolders(new Set())
      mutateFolders()
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : "Failed to delete")
    }
  }

  const handleEmptyTrash = async () => {
    try {
      await emptyTrash({})
      toast.success("Trash emptied")
      setSelectedAssets(new Set())
      setSelectedFolders(new Set())
      setEmptyTrashOpen(false)
      mutateAssets()
      mutateFolders()
    } catch (e: unknown) {
      toast.error(e instanceof Error ? e.message : "Failed to empty trash")
    }
  }

  const selectedCount = tab === "assets" ? selectedAssets.size : selectedFolders.size

  return (
    <div className="flex flex-1 flex-col gap-6 p-4 md:p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Trash</h1>
          <p className="text-sm text-muted-foreground">
            {totalItems > 0
              ? `${totalItems} deleted item${totalItems !== 1 ? "s" : ""}`
              : "No items in trash"}
          </p>
        </div>
        <div className="flex gap-2">
          {tab === "assets" && selectedAssets.size > 0 && (
            <>
              <Button variant="outline" size="sm" onClick={() => handleRestoreAssets()} disabled={busy}>
                <ArchiveRestore className="mr-1.5 size-4" />
                Restore ({selectedAssets.size})
              </Button>
              <Button variant="destructive" size="sm" onClick={() => handlePermDeleteAssets()} disabled={busy}>
                <Shredder className="mr-1.5 size-4" />
                Delete forever ({selectedAssets.size})
              </Button>
            </>
          )}
          {tab === "folders" && selectedFolders.size > 0 && (
            <>
              <Button variant="outline" size="sm" onClick={() => handleRestoreFolders()} disabled={busy}>
                <ArchiveRestore className="mr-1.5 size-4" />
                Restore ({selectedFolders.size})
              </Button>
              <Button variant="destructive" size="sm" onClick={() => handlePermDeleteFolders()} disabled={busy}>
                <Shredder className="mr-1.5 size-4" />
                Delete forever ({selectedFolders.size})
              </Button>
            </>
          )}
          {totalItems > 0 && selectedCount === 0 && (
            <Button variant="destructive" size="sm" onClick={() => setEmptyTrashOpen(true)} disabled={busy}>
              <Shredder className="mr-1.5 size-4" />
              Empty Trash
            </Button>
          )}
        </div>
      </div>

      <Tabs value={tab} onValueChange={(v) => { setTab(v); setSelectedAssets(new Set()); setSelectedFolders(new Set()) }}>
        <TabsList>
          <TabsTrigger value="assets">
            Assets{assetTotal > 0 ? ` (${assetTotal})` : ""}
          </TabsTrigger>
          <TabsTrigger value="folders">
            Folders{folderTotal > 0 ? ` (${folderTotal})` : ""}
          </TabsTrigger>
        </TabsList>

        {/* Assets Tab */}
        <TabsContent value="assets">
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-10">
                    <Checkbox checked={allAssetsSelected} onCheckedChange={toggleAllAssets} aria-label="Select all" />
                  </TableHead>
                  <TableHead>File Name</TableHead>
                  <TableHead>Project</TableHead>
                  <TableHead>Category</TableHead>
                  <TableHead>Deleted By</TableHead>
                  <TableHead>Deleted</TableHead>
                  <TableHead className="text-right">Size</TableHead>
                  <TableHead className="w-24" />
                </TableRow>
              </TableHeader>
              <TableBody>
                {assetsLoading ? (
                  Array.from({ length: 5 }).map((_, i) => (
                    <TableRow key={i}>
                      <TableCell><Skeleton className="size-4" /></TableCell>
                      <TableCell><Skeleton className="h-4 w-32" /></TableCell>
                      <TableCell><Skeleton className="h-4 w-20" /></TableCell>
                      <TableCell><Skeleton className="h-5 w-16 rounded-full" /></TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Skeleton className="size-6 rounded-full" />
                          <Skeleton className="h-4 w-24" />
                        </div>
                      </TableCell>
                      <TableCell><Skeleton className="h-4 w-20" /></TableCell>
                      <TableCell className="text-right"><Skeleton className="ml-auto h-4 w-16" /></TableCell>
                      <TableCell><Skeleton className="h-8 w-20" /></TableCell>
                    </TableRow>
                  ))
                ) : assets.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={8} className="p-0">
                      <Empty className="border-0">
                        <EmptyHeader>
                          <EmptyMedia variant="icon">
                            <Trash2 strokeWidth={1.5} />
                          </EmptyMedia>
                          <EmptyTitle>No deleted assets</EmptyTitle>
                          <EmptyDescription>
                            Deleted assets will appear here.
                          </EmptyDescription>
                        </EmptyHeader>
                      </Empty>
                    </TableCell>
                  </TableRow>
                ) : (
                  assets.map((asset) => (
                    <TableRow key={asset.name}>
                      <TableCell>
                        <Checkbox
                          checked={selectedAssets.has(asset.name)}
                          onCheckedChange={() => toggleAssetSelect(asset.name)}
                          aria-label={`Select ${asset.file_name}`}
                        />
                      </TableCell>
                      <TableCell>
                        <span className="max-w-[200px] truncate font-medium block">{asset.file_name}</span>
                      </TableCell>
                      <TableCell>
                        <span className="text-muted-foreground">{asset.project_name || "—"}</span>
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline">{asset.category}</Badge>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <UserAvatar name={asset.deleter_name || ""} image={undefined} />
                          <span className="text-sm">{asset.deleter_name || "—"}</span>
                        </div>
                      </TableCell>
                      <TableCell>
                        <span className="text-sm text-muted-foreground">
                          {asset.deleted_at
                            ? formatDistanceToNow(new Date(asset.deleted_at), { addSuffix: true })
                            : "—"}
                        </span>
                      </TableCell>
                      <TableCell className="text-right">
                        <span className="text-muted-foreground">
                          {asset.file_size ? formatBytes(asset.file_size) : "—"}
                        </span>
                      </TableCell>
                      <TableCell>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleRestoreAssets([asset.name])}
                          disabled={busy}
                          title="Restore"
                        >
                          <ArchiveRestore className="size-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>

          <LoadMoreControls
            loaded={assets.length}
            total={assetTotal}
            pageSize={PAGE_SIZE}
            isLoading={assetsLoading}
            onLoadMore={() => setAssetLimit((l) => l + PAGE_SIZE)}
          />
        </TabsContent>

        {/* Folders Tab */}
        <TabsContent value="folders">
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-10">
                    <Checkbox checked={allFoldersSelected} onCheckedChange={toggleAllFolders} aria-label="Select all" />
                  </TableHead>
                  <TableHead>Folder Name</TableHead>
                  <TableHead>Project</TableHead>
                  <TableHead>Deleted By</TableHead>
                  <TableHead>Deleted</TableHead>
                  <TableHead className="w-24" />
                </TableRow>
              </TableHeader>
              <TableBody>
                {foldersLoading ? (
                  Array.from({ length: 3 }).map((_, i) => (
                    <TableRow key={i}>
                      <TableCell><Skeleton className="size-4" /></TableCell>
                      <TableCell><Skeleton className="h-4 w-32" /></TableCell>
                      <TableCell><Skeleton className="h-4 w-20" /></TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Skeleton className="size-6 rounded-full" />
                          <Skeleton className="h-4 w-24" />
                        </div>
                      </TableCell>
                      <TableCell><Skeleton className="h-4 w-20" /></TableCell>
                      <TableCell><Skeleton className="h-8 w-20" /></TableCell>
                    </TableRow>
                  ))
                ) : folders.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} className="p-0">
                      <Empty className="border-0">
                        <EmptyHeader>
                          <EmptyMedia variant="icon">
                            <Trash2 strokeWidth={1.5} />
                          </EmptyMedia>
                          <EmptyTitle>No deleted folders</EmptyTitle>
                          <EmptyDescription>
                            Deleted folders will appear here.
                          </EmptyDescription>
                        </EmptyHeader>
                      </Empty>
                    </TableCell>
                  </TableRow>
                ) : (
                  folders.map((folder) => (
                    <TableRow key={folder.name}>
                      <TableCell>
                        <Checkbox
                          checked={selectedFolders.has(folder.name)}
                          onCheckedChange={() => toggleFolderSelect(folder.name)}
                          aria-label={`Select ${folder.folder_name}`}
                        />
                      </TableCell>
                      <TableCell>
                        <span className="font-medium">{folder.folder_name}</span>
                      </TableCell>
                      <TableCell>
                        <span className="text-muted-foreground">{folder.project_name || "—"}</span>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <UserAvatar name={folder.deleter_name || ""} image={undefined} />
                          <span className="text-sm">{folder.deleter_name || "—"}</span>
                        </div>
                      </TableCell>
                      <TableCell>
                        <span className="text-sm text-muted-foreground">
                          {folder.deleted_at
                            ? formatDistanceToNow(new Date(folder.deleted_at), { addSuffix: true })
                            : "—"}
                        </span>
                      </TableCell>
                      <TableCell>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleRestoreFolders([folder.name])}
                          disabled={busy}
                          title="Restore"
                        >
                          <ArchiveRestore className="size-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>

          <LoadMoreControls
            loaded={folders.length}
            total={folderTotal}
            pageSize={PAGE_SIZE}
            isLoading={foldersLoading}
            onLoadMore={() => setFolderLimit((l) => l + PAGE_SIZE)}
          />
        </TabsContent>
      </Tabs>

      {/* Empty Trash confirmation */}
      <AlertDialog open={emptyTrashOpen} onOpenChange={setEmptyTrashOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Empty trash?</AlertDialogTitle>
            <AlertDialogDescription>
              This will permanently delete all {totalItems} item{totalItems !== 1 ? "s" : ""} in the trash
              ({assetTotal} asset{assetTotal !== 1 ? "s" : ""}, {folderTotal} folder{folderTotal !== 1 ? "s" : ""}).
              This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={emptying}>Cancel</AlertDialogCancel>
            <AlertDialogAction
              variant="destructive"
              onClick={handleEmptyTrash}
              disabled={emptying}
            >
              {emptying ? "Emptying..." : "Empty Trash"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}

// frontend/src/pages/TrashPage.vue
<template>
	<PageHeader>
		<PageHeaderTitle>
			<div class="min-w-0">
				<h1 class="truncate">Trash</h1>
				<p class="text-sm text-ink-gray-5">{{ itemSummary }}</p>
			</div>
		</PageHeaderTitle>
		<template #actions>
			<Button
				v-if="selected.length"
				:label="`Restore (${selected.length})`"
				icon-left="lucide-archive-restore"
				:loading="busy === 'restore'"
				@click="restoreSelected"
			/>
			<Button
				v-if="selected.length"
				:label="`Delete forever (${selected.length})`"
				icon-left="lucide-shredder"
				theme="red"
				:loading="busy === 'delete'"
				@click="confirmDelete(selected)"
			/>
			<Button
				v-else-if="totalItems"
				label="Empty trash"
				icon-left="lucide-shredder"
				theme="red"
				@click="confirmEmpty"
			/>
		</template>
	</PageHeader>

	<div class="space-y-4 px-3 py-5 pb-10 sm:px-5" data-testid="trash-page">
		<Tabs v-model="tab" :tabs="tabs" />

		<LoadingText v-if="current.loading && !currentItems.length" :lines="5" />
		<ErrorMessage v-else-if="current.error" :message="current.error" />
		<EmptyState
			v-else-if="!currentItems.length"
			icon="lucide-trash-2"
			:title="tab === 'assets' ? 'No deleted assets' : 'No deleted folders'"
			description="Deleted items will appear here until they are restored or permanently removed."
		/>

		<List
			v-else-if="tab === 'assets'"
			v-model:selection="selectedAssets"
			:columns="ASSET_COLUMNS"
			selectable
			:row-height="52"
			class="-mx-3 list-row-px-3 sm:-mx-5 sm:list-row-px-5"
		>
			<ListHeader>
				<ListHeaderCell>File name</ListHeaderCell>
				<ListHeaderCell>Project</ListHeaderCell>
				<ListHeaderCell>Category</ListHeaderCell>
				<ListHeaderCell>Deleted by</ListHeaderCell>
				<ListHeaderCell>Deleted</ListHeaderCell>
				<ListHeaderCell align="end">Size</ListHeaderCell>
				<ListHeaderCell />
			</ListHeader>
			<ListGroup label="Files">
				<ListRows :items="assets" row-key="name">
					<template #default="{ item }">
						<ListRow :value="item.name">
							<ListCell><span class="truncate text-base-medium text-ink-gray-8">{{ item.file_name }}</span></ListCell>
							<ListCell><span class="truncate text-sm text-ink-gray-6">{{ item.project_name || '—' }}</span></ListCell>
							<ListCell><Badge :label="item.category" theme="gray" /></ListCell>
							<ListCell><span class="truncate text-sm text-ink-gray-7">{{ item.deleter_name || '—' }}</span></ListCell>
							<ListCell><span class="text-sm text-ink-gray-5">{{ fromNow(item.deleted_at) || '—' }}</span></ListCell>
							<ListCell class="justify-end"><span class="text-sm tabular-nums text-ink-gray-6">{{ item.file_size ? formatBytes(item.file_size) : '—' }}</span></ListCell>
							<ListCell class="justify-end gap-1" @click.stop>
								<Button icon="lucide-archive-restore" label="Restore" variant="ghost" @click="restore([item.name])" />
								<Button icon="lucide-trash-2" label="Delete forever" variant="ghost" theme="red" @click="confirmDelete([item.name])" />
							</ListCell>
						</ListRow>
					</template>
				</ListRows>
			</ListGroup>
		</List>

		<List
			v-else
			v-model:selection="selectedFolders"
			:columns="FOLDER_COLUMNS"
			selectable
			:row-height="52"
			class="-mx-3 list-row-px-3 sm:-mx-5 sm:list-row-px-5"
		>
			<ListHeader>
				<ListHeaderCell>Folder name</ListHeaderCell>
				<ListHeaderCell>Project</ListHeaderCell>
				<ListHeaderCell>Deleted by</ListHeaderCell>
				<ListHeaderCell>Deleted</ListHeaderCell>
				<ListHeaderCell />
			</ListHeader>
			<ListGroup label="Folders">
				<ListRows :items="folders" row-key="name">
					<template #default="{ item }">
						<ListRow :value="item.name">
							<ListCell class="gap-2"><span class="lucide-folder size-4 text-ink-gray-4" /><span class="truncate text-base-medium text-ink-gray-8">{{ item.folder_name }}</span></ListCell>
							<ListCell><span class="truncate text-sm text-ink-gray-6">{{ item.project_name || '—' }}</span></ListCell>
							<ListCell><span class="truncate text-sm text-ink-gray-7">{{ item.deleter_name || '—' }}</span></ListCell>
							<ListCell><span class="text-sm text-ink-gray-5">{{ fromNow(item.deleted_at) || '—' }}</span></ListCell>
							<ListCell class="justify-end gap-1" @click.stop>
								<Button icon="lucide-archive-restore" label="Restore" variant="ghost" @click="restore([item.name])" />
								<Button icon="lucide-trash-2" label="Delete forever" variant="ghost" theme="red" @click="confirmDelete([item.name])" />
							</ListCell>
						</ListRow>
					</template>
				</ListRows>
			</ListGroup>
		</List>

		<div v-if="currentItems.length < currentTotal" class="flex justify-center">
			<Button label="Load more" :loading="current.loading" @click="loadMore" />
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Badge, Button, dialog, ErrorMessage, LoadingText, PageHeader, PageHeaderTitle, Tabs, toast, useCall, usePageMeta } from 'frappe-ui'
import { List, ListCell, ListGroup, ListHeader, ListHeaderCell, ListRow, ListRows } from 'frappe-ui/list'
import type { Asset, Folder } from '@/types'
import { fromNow } from '@/lib/dates'
import { formatBytes, serverMessage } from '@/lib/format'
import EmptyState from '@/components/common/EmptyState.vue'

usePageMeta(() => ({ title: 'Trash · VMS' }))

const PAGE_SIZE = 20
const ASSET_COLUMNS = ['minmax(10rem,1fr)', '10rem', '7rem', '10rem', '8rem', '6rem', '6rem']
const FOLDER_COLUMNS = ['minmax(10rem,1fr)', '10rem', '10rem', '8rem', '6rem']
const tab = ref<'assets' | 'folders'>('assets')
const assetLimit = ref(PAGE_SIZE)
const folderLimit = ref(PAGE_SIZE)
const selectedAssets = ref<string[]>([])
const selectedFolders = ref<string[]>([])
const busy = ref<'' | 'restore' | 'delete' | 'empty'>('')

interface AssetResponse { assets: Asset[]; total: number }
interface FolderResponse { folders: Folder[]; total: number }
interface PageParams { page: number; page_size: number }

const assetResource = useCall<AssetResponse, PageParams>({
	url: '/api/v2/method/vms.api.get_trash_assets', method: 'GET',
	params: () => ({ page: 1, page_size: assetLimit.value }), refetch: true,
	cacheKey: ['trash-assets', assetLimit],
})
const folderResource = useCall<FolderResponse, PageParams>({
	url: '/api/v2/method/vms.api.get_trash_folders', method: 'GET',
	params: () => ({ page: 1, page_size: folderLimit.value }), refetch: true,
	cacheKey: ['trash-folders', folderLimit],
})
const restoreAsset = useCall<unknown, { asset_name: string }>({ url: '/api/v2/method/vms.api.restore_asset', method: 'POST', immediate: false })
const deleteAsset = useCall<unknown, { asset_name: string }>({ url: '/api/v2/method/vms.api.permanently_delete_asset', method: 'POST', immediate: false })
const restoreFolder = useCall<unknown, { folder_name: string }>({ url: '/api/v2/method/vms.api.restore_folder', method: 'POST', immediate: false })
const deleteFolder = useCall<unknown, { folder_name: string }>({ url: '/api/v2/method/vms.api.permanently_delete_folder', method: 'POST', immediate: false })
const emptyTrash = useCall<unknown>({ url: '/api/v2/method/vms.api.empty_trash', method: 'POST', immediate: false })

const assets = computed(() => assetResource.data?.assets ?? [])
const folders = computed(() => folderResource.data?.folders ?? [])
const assetTotal = computed(() => assetResource.data?.total ?? 0)
const folderTotal = computed(() => folderResource.data?.total ?? 0)
const totalItems = computed(() => assetTotal.value + folderTotal.value)
const current = computed(() => tab.value === 'assets' ? assetResource : folderResource)
const currentItems = computed(() => tab.value === 'assets' ? assets.value : folders.value)
const currentTotal = computed(() => tab.value === 'assets' ? assetTotal.value : folderTotal.value)
const selected = computed(() => tab.value === 'assets' ? selectedAssets.value : selectedFolders.value)
const itemSummary = computed(() => totalItems.value ? `${totalItems.value} deleted item${totalItems.value === 1 ? '' : 's'}` : 'No items in trash')
const tabs = computed(() => [
	{ label: `Assets${assetTotal.value ? ` (${assetTotal.value})` : ''}`, value: 'assets' },
	{ label: `Folders${folderTotal.value ? ` (${folderTotal.value})` : ''}`, value: 'folders' },
])

watch(tab, () => { selectedAssets.value = []; selectedFolders.value = [] })

function loadMore() {
	if (tab.value === 'assets') assetLimit.value += PAGE_SIZE
	else folderLimit.value += PAGE_SIZE
}

async function reloadAll() {
	await Promise.all([assetResource.reload(), folderResource.reload()])
}

async function restore(names: string[]) {
	busy.value = 'restore'
	try {
		for (const name of names) {
			if (tab.value === 'assets') await restoreAsset.submit({ asset_name: name })
			else await restoreFolder.submit({ folder_name: name })
		}
		toast.success(`Restored ${names.length} item${names.length === 1 ? '' : 's'}`)
		selectedAssets.value = []; selectedFolders.value = []
		await reloadAll()
	} catch (error) { toast.error(serverMessage(error) || 'Could not restore items') }
	finally { busy.value = '' }
}

function restoreSelected() { return restore([...selected.value]) }

function confirmDelete(names: string[]) {
	dialog.danger({
		title: `Delete ${names.length} item${names.length === 1 ? '' : 's'} forever?`,
		message: 'This action cannot be undone.', confirmLabel: 'Delete forever',
		onConfirm: () => permanentlyDelete(names),
	})
}

async function permanentlyDelete(names: string[]) {
	busy.value = 'delete'
	try {
		for (const name of names) {
			if (tab.value === 'assets') await deleteAsset.submit({ asset_name: name })
			else await deleteFolder.submit({ folder_name: name })
		}
		toast.success(`Permanently deleted ${names.length} item${names.length === 1 ? '' : 's'}`)
		selectedAssets.value = []; selectedFolders.value = []
		await reloadAll()
	} catch (error) { toast.error(serverMessage(error) || 'Could not delete items') }
	finally { busy.value = '' }
}

function confirmEmpty() {
	dialog.danger({
		title: 'Empty trash?', message: `Permanently delete all ${totalItems.value} items? This action cannot be undone.`,
		confirmLabel: 'Empty trash', onConfirm: runEmpty,
	})
}

async function runEmpty() {
	busy.value = 'empty'
	try { await emptyTrash.submit(); toast.success('Trash emptied'); await reloadAll() }
	catch (error) { toast.error(serverMessage(error) || 'Could not empty trash') }
	finally { busy.value = '' }
}
</script>
