// frontend/src/components/AssetSortMenu.tsx
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { ArrowUpDownIcon, Tick02Icon } from "@hugeicons/core-free-icons"
import { HugeiconsIcon } from "@hugeicons/react"

export type AssetSortField = "creation" | "file_size" | "file_name"
export type AssetSortOrder = "asc" | "desc"

export interface AssetSort {
  field: AssetSortField
  order: AssetSortOrder
}

export const DEFAULT_ASSET_SORT: AssetSort = { field: "creation", order: "desc" }

const SORT_OPTIONS: { label: string; sort: AssetSort }[] = [
  { label: "Newest first", sort: { field: "creation", order: "desc" } },
  { label: "Oldest first", sort: { field: "creation", order: "asc" } },
  { label: "Name (A–Z)", sort: { field: "file_name", order: "asc" } },
  { label: "Name (Z–A)", sort: { field: "file_name", order: "desc" } },
  { label: "Largest first", sort: { field: "file_size", order: "desc" } },
  { label: "Smallest first", sort: { field: "file_size", order: "asc" } },
]

interface AssetSortMenuProps {
  value: AssetSort
  onChange: (sort: AssetSort) => void
}

export function AssetSortMenu({ value, onChange }: AssetSortMenuProps) {
  const active = SORT_OPTIONS.find(
    (o) => o.sort.field === value.field && o.sort.order === value.order
  )

  return (
    <DropdownMenu>
      <DropdownMenuTrigger render={<Button variant="outline" size="sm" />}>
        <HugeiconsIcon icon={ArrowUpDownIcon} strokeWidth={2} data-icon="inline-start" />
        <span className="hidden sm:inline">{active ? active.label : "Sort"}</span>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-48">
        {SORT_OPTIONS.map((option) => (
          <DropdownMenuItem
            key={`${option.sort.field}-${option.sort.order}`}
            onClick={() => onChange(option.sort)}
          >
            <span className="flex-1">{option.label}</span>
            {option === active && (
              <HugeiconsIcon icon={Tick02Icon} className="size-3.5" strokeWidth={2} />
            )}
          </DropdownMenuItem>
        ))}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

// frontend/src/components/assets/AssetSortMenu.vue
<template>
	<Dropdown :options="options" align="end">
		<Button :label="activeLabel" icon-left="lucide-arrow-up-down" variant="subtle" />
	</Dropdown>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { Button, Dropdown } from 'frappe-ui'

type AssetSortField = 'creation' | 'file_size' | 'file_name'
type AssetSortOrder = 'asc' | 'desc'
interface AssetSort {
	field: AssetSortField
	order: AssetSortOrder
}

const props = defineProps<{ modelValue: AssetSort }>()
const emit = defineEmits<{ 'update:modelValue': [value: AssetSort] }>()

const choices: { label: string; value: AssetSort }[] = [
	{ label: 'Newest first', value: { field: 'creation', order: 'desc' } },
	{ label: 'Oldest first', value: { field: 'creation', order: 'asc' } },
	{ label: 'Name (A–Z)', value: { field: 'file_name', order: 'asc' } },
	{ label: 'Name (Z–A)', value: { field: 'file_name', order: 'desc' } },
	{ label: 'Largest first', value: { field: 'file_size', order: 'desc' } },
	{ label: 'Smallest first', value: { field: 'file_size', order: 'asc' } },
]

const activeLabel = computed(
	() =>
		choices.find(
			({ value }) =>
				value.field === props.modelValue.field && value.order === props.modelValue.order,
		)?.label ?? 'Sort',
)

const options = computed(() =>
	choices.map(({ label, value }) => ({
		label,
		icon:
			value.field === props.modelValue.field && value.order === props.modelValue.order
				? 'lucide-check'
				: undefined,
		onClick: () => emit('update:modelValue', value),
	})),
)
</script>
