// frontend-react/src/components/AssetTags.tsx
import { useState, useRef, useEffect } from "react"
import { useFrappePostCall } from "frappe-react-sdk"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { toast } from "sonner"
import { Plus, Tag, X } from "lucide-react"

interface AssetTagsProps {
  assetName: string
  tags: string[]
  onChanged?: (tags: string[]) => void
  compact?: boolean
}

export function AssetTags({ assetName, tags, onChanged, compact = false }: AssetTagsProps) {
  const [current, setCurrent] = useState<string[]>(tags ?? [])
  const [open, setOpen] = useState(false)
  const [input, setInput] = useState("")
  const inputRef = useRef<HTMLInputElement | null>(null)

  const { call: addCall } = useFrappePostCall("vms.api.add_asset_tag")
  const { call: removeCall } = useFrappePostCall("vms.api.remove_asset_tag")

  useEffect(() => {
    setCurrent(tags ?? [])
  }, [tags])

  useEffect(() => {
    if (open) {
      requestAnimationFrame(() => inputRef.current?.focus())
    } else {
      setInput("")
    }
  }, [open])

  const addTag = async (raw: string) => {
    const tag = raw.trim()
    if (!tag) return
    if (current.some((t) => t.toLowerCase() === tag.toLowerCase())) {
      setInput("")
      return
    }
    const prev = current
    const optimistic = [...prev, tag]
    setCurrent(optimistic)
    setInput("")
    try {
      const res = await addCall({ asset_name: assetName, tag })
      const next = (res?.message?.tags ?? optimistic) as string[]
      setCurrent(next)
      onChanged?.(next)
    } catch {
      setCurrent(prev)
      toast.error("Failed to add tag")
    }
  }

  const removeTag = async (tag: string) => {
    const prev = current
    const optimistic = prev.filter((t) => t !== tag)
    setCurrent(optimistic)
    try {
      const res = await removeCall({ asset_name: assetName, tag })
      const next = (res?.message?.tags ?? optimistic) as string[]
      setCurrent(next)
      onChanged?.(next)
    } catch {
      setCurrent(prev)
      toast.error("Failed to remove tag")
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      e.preventDefault()
      addTag(input)
    } else if (e.key === "Backspace" && !input && current.length > 0) {
      e.preventDefault()
      removeTag(current[current.length - 1])
    }
  }

  const stopPropagation = (e: React.MouseEvent | React.KeyboardEvent) => e.stopPropagation()

  return (
    <div className="flex flex-wrap items-center gap-1" onClick={stopPropagation}>
      {current.map((tag) => (
        <Badge
          key={tag}
          variant="outline"
          className="group/tag gap-0.5 pr-1 text-[10px] font-normal"
        >
          <Tag className="size-2.5 text-muted-foreground" />
          <span className="max-w-[120px] truncate">{tag}</span>
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation()
              removeTag(tag)
            }}
            className="ml-0.5 rounded-full p-0.5 text-muted-foreground hover:bg-muted hover:text-foreground"
            aria-label={`Remove tag ${tag}`}
          >
            <X className="size-2.5" strokeWidth={2.5} />
          </button>
        </Badge>
      ))}
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger
          render={
            <Button
              variant="ghost"
              size="sm"
              className="h-5 gap-0.5 rounded-full px-1.5 text-[10px] text-muted-foreground hover:text-foreground"
              onClick={stopPropagation}
            />
          }
        >
          <Plus className="size-2.5" />
          {compact || current.length > 0 ? null : <span>Add tag</span>}
        </PopoverTrigger>
        <PopoverContent className="w-56 gap-2 p-3" onClick={stopPropagation} onKeyDown={stopPropagation}>
          <div className="text-xs font-medium text-muted-foreground">Add a tag</div>
          <Input
            ref={inputRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="e.g. Must use"
            className="h-8 text-sm"
            maxLength={50}
          />
          <div className="text-[10px] text-muted-foreground">
            Press Enter to add. Click × to remove.
          </div>
        </PopoverContent>
      </Popover>
    </div>
  )
}

// frontend/src/components/assets/AssetTags.vue
<template>
	<Dialog
		:open="open"
		title="Tags"
		size="sm"
		:actions="[{ label: 'Done', variant: 'solid' }]"
		@update:open="emit('update:open', $event)"
	>
		<div class="space-y-3">
			<div class="flex flex-wrap gap-1.5">
				<Badge
					v-for="tag in tags"
					:key="tag"
					variant="subtle"
					theme="gray"
					size="md"
					class="gap-1"
				>
					{{ tag }}
					<button
						type="button"
						class="ml-0.5 rounded text-ink-gray-5 hover:text-ink-gray-8"
						:aria-label="`Remove tag ${tag}`"
						@click="remove(tag)"
					>
						<span class="lucide-x size-3" aria-hidden="true" />
					</button>
				</Badge>
				<p v-if="!tags.length" class="text-sm text-ink-gray-5">No tags yet.</p>
			</div>
			<div class="flex items-end gap-2">
				<FormControl
					v-model="draft"
					label="Add tag"
					placeholder="e.g. b-roll"
					class="flex-1"
					:error="addCall.error?.message"
					@keydown.enter.prevent="add"
				/>
				<Button
					label="Add"
					:loading="addCall.loading"
					:disabled="!draft.trim()"
					@click="add"
				/>
			</div>
		</div>
	</Dialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { Badge, Button, Dialog, FormControl, toast, useCall } from 'frappe-ui'
import type { Asset } from '@/types'
import { serverMessage } from '@/lib/format'

const props = defineProps<{ open: boolean; asset: Asset }>()
const emit = defineEmits<{ 'update:open': [value: boolean]; changed: [] }>()

const tags = ref<string[]>([...(props.asset.tags ?? [])])
const draft = ref('')

watch(
	() => props.open,
	(open) => {
		if (open) {
			tags.value = [...(props.asset.tags ?? [])]
			draft.value = ''
		}
	},
)

interface TagParams {
	asset_name: string
	tag: string
}

const addCall = useCall<string[], TagParams>({
	url: '/api/v2/method/vms.api.add_asset_tag',
	method: 'POST',
	immediate: false,
})
const removeCall = useCall<string[], TagParams>({
	url: '/api/v2/method/vms.api.remove_asset_tag',
	method: 'POST',
	immediate: false,
})

async function add() {
	const tag = draft.value.trim()
	if (!tag) return
	try {
		const updated = await addCall.submit({ asset_name: props.asset.name, tag })
		tags.value = updated ?? [...tags.value, tag]
		draft.value = ''
		emit('changed')
	} catch (e) {
		toast.error(serverMessage(e))
	}
}

async function remove(tag: string) {
	try {
		const updated = await removeCall.submit({ asset_name: props.asset.name, tag })
		tags.value = updated ?? tags.value.filter((t) => t !== tag)
		emit('changed')
	} catch (e) {
		toast.error(serverMessage(e))
	}
}
</script>
