// frontend/src/components/MoveAssetDialog.tsx
import { useState } from "react"
import { useFrappeGetDocList, useFrappePostCall } from "frappe-react-sdk"
import { toast } from "sonner"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { serverMessage } from "@/lib/utils"
import type { VMSProject } from "@/types"

interface MoveAssetDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  assetNames: string[]
  onComplete?: (targetProject: string) => void
}

export function MoveAssetDialog({
  open,
  onOpenChange,
  assetNames,
  onComplete,
}: MoveAssetDialogProps) {
  const [targetProject, setTargetProject] = useState<string>("")
  const [moving, setMoving] = useState(false)

  const { data: projects } = useFrappeGetDocList<VMSProject>("VMS Project", {
    fields: ["name", "project_name"],
    orderBy: { field: "creation", order: "desc" },
    limit: 100,
  })

  const { call: moveAsset } = useFrappePostCall("vms.api.move_asset")

  const handleMove = async () => {
    if (!targetProject) {
      toast.error("Please select a project")
      return
    }

    setMoving(true)
    try {
      for (const assetName of assetNames) {
        await moveAsset({ asset_name: assetName, target_project: targetProject })
      }
      toast.success(
        `Moved ${assetNames.length} asset${assetNames.length > 1 ? "s" : ""} to project`
      )
      const movedTo = targetProject
      setTargetProject("")
      onOpenChange(false)
      onComplete?.(movedTo)
    } catch (e: unknown) {
      toast.error("Failed to move assets", {
        description: serverMessage(e) || "Try again in a moment.",
      })
    } finally {
      setMoving(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Move to Project</DialogTitle>
          <DialogDescription>
            Move {assetNames.length} asset{assetNames.length > 1 ? "s" : ""} to
            a project.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-2">
          <Label>Target Project</Label>
          <Select value={targetProject} onValueChange={setTargetProject}>
            <SelectTrigger className="w-full">
              <SelectValue>
                {(value: string | null) =>
                  value
                    ? (projects?.find((p) => p.name === value)?.project_name ?? value)
                    : "Select a project..."
                }
              </SelectValue>
            </SelectTrigger>
            <SelectContent>
              {projects?.map((p) => (
                <SelectItem key={p.name} value={p.name}>
                  {p.project_name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={moving}
          >
            Cancel
          </Button>
          <Button onClick={handleMove} disabled={moving || !targetProject}>
            {moving ? "Moving..." : "Move"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// frontend/src/components/assets/MoveAssetDialog.vue
<template>
	<Dialog
		:open="open"
		title="Move to project"
		size="sm"
		:actions="[
			{ label: 'Move', variant: 'solid', disabled: !target, onClick: submit },
			{ label: 'Cancel' },
		]"
		@update:open="emit('update:open', $event)"
	>
		<FormControl
			v-model="target"
			type="select"
			label="Project"
			placeholder="Choose a project"
			:options="projectOptions"
			:error="move.error?.message"
		/>
	</Dialog>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Dialog, FormControl, toast, useCall, useList } from 'frappe-ui'
import type { Asset, Project } from '@/types'

const props = defineProps<{ open: boolean; asset: Asset }>()
const emit = defineEmits<{ 'update:open': [value: boolean]; changed: [] }>()

const target = ref('')

watch(
	() => props.open,
	(open) => {
		if (open) target.value = ''
	},
)

const projects = useList<Pick<Project, 'name' | 'project_name'>>({
	doctype: 'VMS Project',
	fields: ['name', 'project_name'],
	orderBy: 'modified desc',
	limit: 200,
	cacheKey: 'move-asset-projects',
})

const projectOptions = computed(() =>
	(projects.data ?? [])
		.filter((p) => p.name !== props.asset.project)
		.map((p) => ({ label: p.project_name, value: p.name })),
)

const move = useCall<unknown, { asset_name: string; target_project: string }>({
	url: '/api/v2/method/vms.api.move_asset',
	method: 'POST',
	immediate: false,
})

async function submit({ close }: { close: () => void }) {
	if (!target.value) return
	await move.submit({ asset_name: props.asset.name, target_project: target.value })
	toast.success('Asset moved')
	emit('changed')
	close()
}
</script>
